import { useEffect, useMemo, useState } from 'react'
import RedesignShell from './redesign/RedesignShell'
import { useCurrentEvent } from '../hooks/useCurrentEvent'
import { api } from '../api'
import './ConferenceCenterPage.css'

const TABS=[['overview','Overview'],['calls','Calls & abstracts'],['tracks','Tracks'],['speakers','Speaker operations'],['partners','Exhibitors & sponsors'],['gallery','Photo gallery'],['integrations','Integrations'],['templates','Shared templates']]
const OPS={speakers:['meeting','release'],gallery:['gallery'],integrations:['integration']}
export default function ConferenceCenterPage(){
 const [eventId]=useCurrentEvent(),[data,setData]=useState(null),[tab,setTab]=useState('overview'),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const load=async()=>{if(!eventId)return;try{setData(await api.getConferenceCenter(eventId))}catch(e){setMessage(e.message)}}
 useEffect(()=>{load()},[eventId])
 const saveProfile=async(patch)=>{setBusy(true);try{await api.updateConferenceProfile(eventId,{...data.profile,...patch});await load();setMessage('Conference settings saved.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 const addTrack=async()=>{const name=prompt('Track name');if(!name)return;await api.createConferenceTrack(eventId,{name,description:'',color:'#0f766e',audience:'',sort_order:data.tracks.length,is_active:true});load()}
 const addOp=async(category)=>{const title=prompt(category==='gallery'?'Photo title':category==='integration'?'Integration name':category==='meeting'?'Meeting title':'Release title');if(!title)return;await api.createConferenceOperation(eventId,{category,title,status:'draft',data:{}});load()}
 const review=async(s,status,promote=false)=>{setBusy(true);try{await api.reviewConferenceSubmission(eventId,s.id,{status,review_notes:s.review_notes||'',promote});await load()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 if(!eventId)return <RedesignShell eventActive="conference"><main className="cc-page"><div className="cc-empty"><h1>Conference Center</h1><p>Select an event to begin.</p></div></main></RedesignShell>
 if(!data)return <RedesignShell eventActive="conference"><main className="cc-page"><div className="cc-empty"><h1>Conference Center</h1><p>{message||'Loading conference workspace…'}</p></div></main></RedesignShell>
 const p=data.profile, counts={submitted:data.submissions.filter(x=>x.status==='submitted').length,accepted:data.submissions.filter(x=>x.status==='accepted').length,tracks:data.tracks.length,ops:data.operations.length}
 const operationList=(OPS[tab]||[]).flatMap(c=>data.operations.filter(x=>x.category===c))
 return <RedesignShell eventActive="conference" eventScoped><main className="cc-page">
  <header className="cc-head"><div><span className="cc-kicker">Conference operations</span><h1>Conference Center</h1><p>One workspace connected to your existing programme, speakers, partners, media and guest experience.</p></div><a className="cc-public" href={p.public_url} target="_blank" rel="noreferrer">Open public call ↗</a></header>
  {message&&<div className="cc-message">{message}</div>}
  <nav className="cc-tabs">{TABS.map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
  {tab==='overview'&&<><section className="cc-stats"><article><b>{counts.submitted}</b><span>Awaiting review</span></article><article><b>{counts.accepted}</b><span>Accepted</span></article><article><b>{counts.tracks}</b><span>Programme tracks</span></article><article><b>{counts.ops}</b><span>Operational items</span></article></section><section className="cc-grid"><article className="cc-card"><h2>Start here</h2><ol><li>Open the submission types you need.</li><li>Share the public call link.</li><li>Review and accept applications.</li><li>Promote accepted people and organizations into Speakers or Partners.</li><li>Finish scheduling in Experience and Planner.</li></ol></article><article className="cc-card"><h2>Connected systems</h2>{[['Speakers','/addons-redesign?tab=speakers'],['Partners & sponsors','/addons-redesign?tab=partners'],['Programme & sessions','/experience-redesign'],['Planner & logistics','/planner-redesign'],['Media library','/media-redesign'],['Festio Live','/live-redesign']].map(x=><a className="cc-link" href={x[1]} key={x[0]}>{x[0]} <span>Open →</span></a>)}</article></section></>}
  {tab==='calls'&&<><section className="cc-card cc-settings"><div><h2>Public call</h2><p>Choose which applications the event accepts. The public URL remains stable.</p></div><label className="cc-switch"><input type="checkbox" checked={p.calls_open} onChange={e=>saveProfile({calls_open:e.target.checked})}/><span>{p.calls_open?'Open':'Closed'}</span></label><div className="cc-types">{['speaker','abstract','exhibitor','sponsor'].map(k=><label key={k}><input type="checkbox" checked={p.enabled_call_types.includes(k)} onChange={e=>saveProfile({enabled_call_types:e.target.checked?[...p.enabled_call_types,k]:p.enabled_call_types.filter(x=>x!==k)})}/>{k}</label>)}</div><code>{location.origin}{p.public_url}</code></section><section className="cc-card"><h2>Submissions</h2>{!data.submissions.length?<p className="cc-muted">No applications yet.</p>:<div className="cc-table">{data.submissions.map(s=><article key={s.id}><div><b>{s.name}</b><span>{s.kind} · {s.organization||s.email}</span><p>{s.title||s.summary||'No summary supplied'}</p></div><em className={`status-${s.status}`}>{s.status.replace('_',' ')}</em><div className="cc-actions"><button onClick={()=>review(s,'under_review')}>Review</button><button onClick={()=>review(s,'accepted',true)} disabled={busy||s.promoted_record_id}>{s.promoted_record_id?'Connected':'Accept & connect'}</button><button onClick={()=>review(s,'declined')}>Decline</button></div></article>)}</div>}</section></>}
  {tab==='tracks'&&<section className="cc-card"><div className="cc-title-row"><div><h2>Programme tracks</h2><p>Reusable classifications for submissions and sessions.</p></div><button className="primary" onClick={addTrack}>+ Add track</button></div><div className="cc-tile-grid">{data.tracks.map(t=><article key={t.id} style={{borderTopColor:t.color||'#0f766e'}}><b>{t.name}</b><span>{t.audience||'All audiences'}</span><p>{t.description||'Ready to assign to abstracts and sessions.'}</p></article>)}</div></section>}
  {tab==='partners'&&<section className="cc-card"><h2>Exhibitors & sponsors</h2><p>Applications are reviewed in Calls & abstracts. Accepted records are added once to the existing Partner Showcase.</p><a className="cc-cta" href="/addons-redesign?tab=partners">Open Partner Showcase →</a></section>}
  {['speakers','gallery','integrations'].includes(tab)&&<section className="cc-card"><div className="cc-title-row"><div><h2>{TABS.find(x=>x[0]===tab)[1]}</h2><p>{tab==='speakers'?'Coordinate meetings and track releases against canonical speaker records.':tab==='gallery'?'Curate event photography without replacing the Media Library.':'Record AMS and external connections; credentials stay outside public content.'}</p></div><div>{(OPS[tab]||[]).map(c=><button className="primary" onClick={()=>addOp(c)} key={c}>+ {c}</button>)}</div></div><div className="cc-tile-grid">{operationList.map(o=><article key={o.id}><b>{o.title}</b><span>{o.category} · {o.status}</span></article>)}</div>{!operationList.length&&<p className="cc-muted">Nothing configured yet.</p>}</section>}
  {tab==='templates'&&<section className="cc-card"><div className="cc-title-row"><div><h2>Organization templates</h2><p>Reusable conference setup owned by your organization, never tied to one event.</p></div><button className="primary" onClick={async()=>{const name=prompt('Template name');if(name){await api.createConferenceTemplate(eventId,{name,category:'conference',definition:{tracks:data.tracks.map(({name,description,color,audience,sort_order})=>({name,description,color,audience,sort_order}))}});load()}}}>Save current setup</button></div><div className="cc-tile-grid">{data.templates.map(t=><article key={t.id}><b>{t.name}</b><span>{t.category} · organization template</span></article>)}</div></section>}
 </main></RedesignShell>
}
