import {useSearchParams} from 'react-router-dom'
import { useEffect, useRef, useState } from 'react'
import RedesignShell, { Modal } from './redesign/RedesignShell'
import { useCurrentEvent } from '../hooks/useCurrentEvent'
import { api } from '../api'
import './ConferenceCenterPage.css'

const TABS=[['overview','Overview'],['calls','Calls & abstracts'],['tracks','Tracks'],['speakers','Speaker operations'],['partners','Exhibitors & sponsors'],['gallery','Photo gallery'],['integrations','Integrations'],['templates','Shared templates']]
const OPS={speakers:['meeting','release'],gallery:['gallery'],integrations:['integration']}
export default function ConferenceCenterPage(){
 const [eventId]=useCurrentEvent(),[data,setData]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[editor,setEditor]=useState(null),[submission,setSubmission]=useState(null),galleryInput=useRef(null)
 const [params,setParams]=useSearchParams();const tab=TABS.some(([id])=>id===params.get('tab'))?params.get('tab'):'overview';const setTab=value=>setParams({tab:value})
 const load=async()=>{if(!eventId)return;try{setData(await api.getConferenceCenter(eventId))}catch(e){setMessage(e.message)}}
 useEffect(()=>{load()},[eventId])
 const saveProfile=async(patch)=>{setBusy(true);try{await api.updateConferenceProfile(eventId,{...data.profile,...patch});await load();setMessage('Conference settings saved.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 const addTrack=()=>setEditor({kind:'track',name:'',description:'',color:'#0f766e',audience:'',sort_order:data.tracks.length,is_active:true})
 const saveEditor=async(e)=>{e.preventDefault();if(busy)return;setBusy(true);try{
   if(editor.kind==='track'){const {kind,id,...body}=editor; if(id)await api.updateConferenceTrack(eventId,id,body);else await api.createConferenceTrack(eventId,body)}
   else if(editor.kind==='template')await api.createConferenceTemplate(eventId,{name:editor.name,category:'conference',definition:{tracks:data.tracks.map(({name,description,color,audience,sort_order})=>({name,description,color,audience,sort_order}))}})
   else await api.createConferenceOperation(eventId,{category:editor.kind,title:editor.name,status:'draft',data:editor.data || {}})
   setEditor(null);await load();setMessage('Saved successfully.')
 }catch(e){setMessage(e.message)}finally{setBusy(false)}}
 const addOp=(category,extra={})=>setEditor({kind:category,name:'',data:extra})
 const uploadGallery=async(e)=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{const uploaded=await api.uploadConferenceGalleryImage(eventId,file);await addOp('gallery',{image_url:uploaded.url});setMessage('Photo uploaded. Add a title and save it to the gallery.')}catch(x){setMessage(x.message)}finally{e.target.value='';setBusy(false)}}
 const removeTrack=async(t)=>{if(!confirm(`Delete ${t.name}? Tracks already used by submissions will be protected.`))return;try{await api.deleteConferenceTrack(eventId,t.id);load()}catch(x){setMessage(x.message)}}
 const removeOp=async(o)=>{if(!confirm(`Remove ${o.title}?`))return;await api.deleteConferenceOperation(eventId,o.id);load()}
 const toggleOp=async(o)=>{await api.updateConferenceOperation(eventId,o.id,{status:o.status==='active'?'draft':'active'});load()}
 const review=async(s,status,promote=false)=>{setBusy(true);try{await api.reviewConferenceSubmission(eventId,s.id,{status,review_notes:s.review_notes||'',promote});setSubmission(null);await load();setMessage('Review saved.')}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 if(!eventId)return <RedesignShell eventActive="conference"><main className="cc-page"><div className="cc-empty"><h1>Conference Center</h1><p>Select an event to begin.</p></div></main></RedesignShell>
 if(!data)return <RedesignShell eventActive="conference"><main className="cc-page"><div className="cc-empty"><h1>Conference Center</h1><p>{message||'Loading conference workspace…'}</p></div></main></RedesignShell>
 const p=data.profile, counts={submitted:data.submissions.filter(x=>x.status==='submitted').length,accepted:data.submissions.filter(x=>x.status==='accepted').length,tracks:data.tracks.length,ops:data.operations.length}
 const operationList=(OPS[tab]||[]).flatMap(c=>data.operations.filter(x=>x.category===c))
 return <RedesignShell eventActive="conference" eventScoped><main className="cc-page">
  <header className="cc-head"><div><span className="cc-kicker">Conference operations</span><h1>Conference Center</h1><p>One workspace connected to your existing programme, speakers, partners, media and guest experience.</p></div><a className="cc-public" href={p.public_url} target="_blank" rel="noreferrer">Open public call ↗</a></header>
  {message&&<div className="cc-message">{message}</div>}
  <nav className="cc-tabs">{TABS.map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
  {tab==='overview'&&<><section className="cc-stats"><article><b>{counts.submitted}</b><span>Awaiting review</span></article><article><b>{counts.accepted}</b><span>Accepted</span></article><article><b>{counts.tracks}</b><span>Programme tracks</span></article><article><b>{counts.ops}</b><span>Operational items</span></article></section><section className="cc-grid"><article className="cc-card"><h2>Start here</h2><ol><li>Open the submission types you need.</li><li>Share the public call link.</li><li>Review and accept applications.</li><li>Promote accepted people and organizations into Speakers or Partners.</li><li>Finish scheduling in Experience and Planner.</li></ol></article><article className="cc-card"><h2>Connected systems</h2>{[['Speakers','/addons-redesign?tab=speakers'],['Partners & sponsors','/addons-redesign?tab=partners'],['Programme & sessions','/experience-redesign'],['Planner & logistics','/planner-redesign'],['Media library','/media-redesign'],['Festio Live','/live-redesign']].map(x=><a className="cc-link" href={x[1]} key={x[0]}>{x[0]} <span>Open →</span></a>)}</article></section></>}
  {tab==='calls'&&<><section className="cc-card cc-settings"><div><h2>Public call</h2><p>Choose which applications the event accepts. The public URL remains stable.</p></div><label className="cc-switch"><input type="checkbox" checked={p.calls_open} onChange={e=>saveProfile({calls_open:e.target.checked})}/><span>{p.calls_open?'Open':'Closed'}</span></label><div className="cc-types">{['speaker','abstract','exhibitor','sponsor'].map(k=><label key={k}><input type="checkbox" checked={p.enabled_call_types.includes(k)} onChange={e=>saveProfile({enabled_call_types:e.target.checked?[...p.enabled_call_types,k]:p.enabled_call_types.filter(x=>x!==k)})}/>{k}</label>)}</div><div className="cc-profile-fields"><label>Welcome message<textarea rows="3" defaultValue={p.welcome_text||''} onBlur={e=>saveProfile({welcome_text:e.target.value})}/></label><label>Submission deadline<input type="datetime-local" defaultValue={p.deadline?p.deadline.slice(0,16):''} onBlur={e=>saveProfile({deadline:e.target.value||null})}/></label></div><div className="cc-copy"><code>{location.origin}{p.public_url}</code><button onClick={()=>navigator.clipboard.writeText(`${location.origin}${p.public_url}`).then(()=>setMessage('Public call link copied.'))}>Copy link</button></div></section><section className="cc-card"><h2>Submissions</h2>{!data.submissions.length?<p className="cc-muted">No applications yet.</p>:<div className="cc-table">{data.submissions.map(s=><article key={s.id}><div><b>{s.name}</b><span>{s.kind} · {s.organization||s.email}</span><p>{s.title||s.summary||'No summary supplied'}</p></div><em className={`status-${s.status}`}>{s.status.replace('_',' ')}</em><div className="cc-actions"><button onClick={()=>setSubmission({...s})}>Review details</button><button onClick={()=>review(s,'accepted',true)} disabled={busy||s.promoted_record_id}>{s.promoted_record_id?'Connected':'Accept & connect'}</button><button onClick={()=>review(s,'declined')}>Decline</button></div></article>)}</div>}</section></>}
  {tab==='tracks'&&<section className="cc-card"><div className="cc-title-row"><div><h2>Programme tracks</h2><p>Reusable classifications for submissions and sessions.</p></div><button className="primary" onClick={addTrack}>+ Add track</button></div><div className="cc-tile-grid">{data.tracks.map(t=><article key={t.id} style={{borderTopColor:t.color||'#0f766e'}}><b>{t.name}</b><span>{t.audience||'All audiences'}</span><p>{t.description||'Ready to assign to abstracts and sessions.'}</p><div className="cc-card-actions"><button onClick={()=>setEditor({...t,kind:'track'})}>Edit</button><button onClick={()=>removeTrack(t)}>Delete</button></div></article>)}</div></section>}
  {tab==='partners'&&<section className="cc-card"><h2>Exhibitors & sponsors</h2><p>Applications are reviewed in Calls & abstracts. Accepted records are added once to the existing Partner Showcase.</p><a className="cc-cta" href="/addons-redesign?tab=partners">Open Partner Showcase →</a></section>}
  {['speakers','gallery','integrations'].includes(tab)&&<section className="cc-card"><div className="cc-title-row"><div><h2>{TABS.find(x=>x[0]===tab)[1]}</h2><p>{tab==='speakers'?'Coordinate meetings and track releases against canonical speaker records.':tab==='gallery'?'Curate event photography without replacing the Media Library.':'Record AMS and external connections; credentials stay outside public content.'}</p></div><div>{tab==='gallery'&&<><input ref={galleryInput} hidden type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={uploadGallery}/><button className="primary" disabled={busy} onClick={()=>galleryInput.current?.click()}>+ Upload photo</button></>}{tab!=='gallery'&&(OPS[tab]||[]).map(c=><button className="primary" onClick={()=>addOp(c)} key={c}>+ {c}</button>)}</div></div><div className="cc-tile-grid">{operationList.map(o=><article key={o.id}>{o.data?.image_url&&<img className="cc-gallery-image" src={o.data.image_url} alt=""/>}<b>{o.title}</b><span>{o.category} · {o.status}</span><div className="cc-card-actions"><button onClick={()=>toggleOp(o)}>{o.status==='active'?'Set draft':'Activate'}</button><button onClick={()=>removeOp(o)}>Remove</button></div></article>)}</div>{!operationList.length&&<p className="cc-muted">Nothing configured yet.</p>}</section>}
  {tab==='templates'&&<section className="cc-card"><div className="cc-title-row"><div><h2>Organization templates</h2><p>Reusable conference setup owned by your organization, never tied to one event.</p></div><button className="primary" onClick={()=>setEditor({kind:'template',name:''})}>Save current setup</button></div><div className="cc-tile-grid">{data.templates.map(t=><article key={t.id}><b>{t.name}</b><span>{t.category} · organization template</span><div className="cc-card-actions"><button onClick={async()=>{const r=await api.applyConferenceTemplate(eventId,t.id);setMessage(`Template applied. ${r.tracks_created} new track(s) created.`);load()}}>Apply</button><button onClick={async()=>{if(confirm(`Delete ${t.name}?`)){await api.deleteConferenceTemplate(eventId,t.id);load()}}}>Delete</button></div></article>)}</div></section>}
 {editor&&<Modal title={editor.id?'Edit track':`Add ${editor.kind}`} onClose={()=>!busy&&setEditor(null)}><form onSubmit={saveEditor}><label>Name<input className="rd-field" required maxLength={200} autoFocus value={editor.name} onChange={e=>setEditor({...editor,name:e.target.value})}/></label>{editor.kind==='track'&&<><label>Description<textarea className="rd-field" value={editor.description||''} onChange={e=>setEditor({...editor,description:e.target.value})}/></label><label>Audience<input className="rd-field" value={editor.audience||''} onChange={e=>setEditor({...editor,audience:e.target.value})}/></label><label>Colour<input type="color" value={editor.color||'#0f766e'} onChange={e=>setEditor({...editor,color:e.target.value})}/></label></>}<button className="rr-btn primary" disabled={busy}>{busy?'Saving…':'Save'}</button></form></Modal>}
 {submission&&<Modal title={submission.title||'Submission details'} onClose={()=>setSubmission(null)}><p><strong>{submission.name}</strong> · {submission.email}</p><p>{submission.organization}</p><p style={{whiteSpace:'pre-wrap'}}>{submission.summary||'No summary provided.'}</p>{submission.website_url&&<p>{submission.website_url}</p>}{Object.entries(submission.details||{}).map(([key,value])=><div key={key}><strong>{key.replaceAll('_',' ')}</strong><p style={{whiteSpace:'pre-wrap'}}>{typeof value==='object'?JSON.stringify(value,null,2):String(value)}</p></div>)}<label>Review notes<textarea className="rd-field" value={submission.review_notes||''} onChange={e=>setSubmission({...submission,review_notes:e.target.value})}/></label><div className="cc-actions"><button disabled={busy} onClick={()=>review(submission,'under_review')}>Save review</button><button disabled={busy||submission.promoted_record_id} onClick={()=>review(submission,'accepted',true)}>Accept & connect</button><button disabled={busy} onClick={()=>review(submission,'declined')}>Decline</button></div></Modal>}
 </main></RedesignShell>
}
