import { useEffect, useRef, useState } from 'react';
import RedesignShell from './redesign/RedesignShell';
import LegacyStudio from './DesignStudioRedesignPage';
import { useCurrentEvent } from '../hooks/useCurrentEvent';
import { useEventDetails } from '../hooks/useEventDetails';
import { api } from '../api';
import FlyerControls from '../components/design-studio/FlyerControls';
import {flyerRequest,flyerSettings,FLYER_SIZES} from '../components/design-studio/flyerModel.mjs';
import Images from '../components/design-studio/Images';
import AppearanceChoices from '../components/guesthub/AppearanceChoices';
import { payloadOf,signature,createDesignSaver,toPublicTheme,writeDraftPreview,FONTS } from '../components/design-studio/model.mjs';
import './DesignStudioWorkspace.css';
const STEPS=['Theme','Layout','Customize','Review & publish'];
const LAYOUTS={classic:['Classic','Familiar tabs and event information'],companion:['Companion','Pass and next step in one scroll'],journey:['Journey','Guidance for each event stage'],complete:['Complete Flow','Registration through event day'],app:['Event App','A dedicated home, programme and services']};
const SURFACES={rsvp:'RSVP',hub:'GuestHub',pass:'My Pass',flyer:'Flyer',email:'Email'};
const DEFAULT_COLORS={primary:'#194e3d',accent:'#dfbf75',background:'#f6f4eb',surface:'#ffffff',text:'#203b30'};
function Dialog({title,onClose,children}){const ref=useRef();useEffect(()=>{ref.current.showModal()},[]);return <dialog className="studio-dialog" ref={ref} onCancel={onClose} aria-labelledby="studio-dialog-title"><header><h2 id="studio-dialog-title">{title}</h2><button aria-label="Close" onClick={onClose}>×</button></header><div>{children}</div></dialog>}
export default function DesignStudioWorkspace(){const [eventId]=useCurrentEvent();if(new URLSearchParams(location.search).get('advanced')==='1')return <><div className="studio-return"><a href="/design-studio-redesign">← Guided Design Studio</a><span>Advanced tools · existing workflows</span></div><LegacyStudio/></>;return <Workspace key={eventId||'none'} eventId={eventId}/>}
function Workspace({eventId}){
 const {event}=useEventDetails(eventId);
 const [draft,setDraft]=useState(null),[saved,setSaved]=useState(null),[templates,setTemplates]=useState([]),[loadError,setLoadError]=useState('');
 const [step,setStep]=useState(0),[surface,setSurface]=useState(new URLSearchParams(location.search).get('surface')==='flyer'?'flyer':'rsvp'),[device,setDevice]=useState('desktop'),[mobilePreview,setMobilePreview]=useState(false),[keepBrand,setKeepBrand]=useState(false);
 const [saveState,setSaveState]=useState({status:'loading'}),[publishing,setPublishing]=useState(false),[uploading,setUploading]=useState(false),[publishError,setPublishError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[versions,setVersions]=useState([]);
 const [downloading,setDownloading]=useState(false);
 const [previewUrl,setPreviewUrl]=useState(''),[previewError,setPreviewError]=useState(''),[flyerUrl,setFlyerUrl]=useState(''),[flyerLoading,setFlyerLoading]=useState(false),[scale,setScale]=useState(1);
 const saver=useRef(),timer=useRef(),previewKey=useRef(crypto.randomUUID()),alive=useRef(true),canvas=useRef(),uploadBusy=useRef(false),publishLock=useRef(false);
 useEffect(()=>{alive.current=true;let cancelled=false;if(!eventId)return;Promise.all([api.getEventDesign(eventId),api.designTemplates()]).then(([value,catalog])=>{if(cancelled)return;setTemplates(catalog.templates||catalog||[]);setDraft(payloadOf(value));setSaved(value);saver.current=createDesignSaver(value,data=>api.saveEventDesign(eventId,data),state=>{if(!alive.current)return;setSaveState(state);if(state.saved)setSaved(state.saved)});setSaveState({status:'saved'});}).catch(e=>!cancelled&&setLoadError(e.message));return()=>{cancelled=true;alive.current=false;clearTimeout(timer.current);const pending=saver.current;if(pending)pending.flush().catch(()=>{}).finally(()=>pending.close())}},[eventId]);
 const draftSig=draft?signature(draft):'';
 useEffect(()=>{if(!draft||!saver.current)return;saver.current.edit(draft);clearTimeout(timer.current);timer.current=setTimeout(()=>saver.current.flush().catch(()=>{}),700);return()=>clearTimeout(timer.current)},[draftSig]);
 useEffect(()=>{const warn=e=>{if(['unsaved','saving','error'].includes(saveState.status)||uploading){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[saveState.status,uploading]);
 const theme=draft?toPublicTheme(draft,templates,eventId):null;
 useEffect(()=>{if(!theme||!eventId)return;const timeout=setTimeout(()=>{try{writeDraftPreview(previewKey.current,eventId,theme);setPreviewUrl(`/invite/${encodeURIComponent(eventId)}?studio-preview=1&studio-key=${previewKey.current}&studio-surface=${surface}&focus=hero&_p=${Date.now()}${surface==='pass'?'#/pass':''}`);setPreviewError('')}catch{setPreviewError('Browser storage is unavailable. Allow site storage to preview this draft.')}},350);return()=>clearTimeout(timeout)},[draftSig,surface,templates,eventId]);
 useEffect(()=>{if(!canvas.current)return;const resize=()=>setScale(Math.min(1,Math.max(.1,(canvas.current.clientWidth-28)/(device==='phone'?390:1280))));const observer=new ResizeObserver(resize);observer.observe(canvas.current);resize();return()=>observer.disconnect()},[device,draft,mobilePreview]);
 useEffect(()=>{if(surface!=='flyer'||!draft||!eventId)return;let cancelled=false,url;const timeout=setTimeout(async()=>{setFlyerLoading(true);setFlyerUrl('');try{const {blob}=await api.renderFlyer(eventId,flyerRequest({draft,event:event||{},theme,eventId,origin:location.origin,preview:true}),{download:false});url=URL.createObjectURL(blob);if(!cancelled){setFlyerUrl(url);setPreviewError('')}else URL.revokeObjectURL(url)}catch(e){if(!cancelled)setPreviewError(e.message)}finally{if(!cancelled)setFlyerLoading(false)}},800);return()=>{cancelled=true;clearTimeout(timeout);if(url)URL.revokeObjectURL(url)}},[surface,draftSig,eventId,event,templates]);
 function edit(updater){if(publishLock.current)return;setPublishError('');setNotice('');setDraft(d=>typeof updater==='function'?updater(d):({...d,...updater}))}
 const config=(area,key,value)=>edit(d=>({...d,[area]:{...d[area],[key]:value}}));
 const assets=patch=>edit(d=>({...d,asset_config:{...d.asset_config,...patch}}));
 async function downloadFlyer(format){if(downloading)return;setDownloading(true);setPreviewError('');try{await flush();await api.renderFlyer(eventId,flyerRequest({draft,event:event||{},theme,eventId,origin:location.origin,format}));setNotice('Flyer downloaded from your current draft.')}catch(e){setPreviewError(e.message)}finally{setDownloading(false)}}
 async function flush(){clearTimeout(timer.current);saver.current.edit(draft);return saver.current.flush()}
 async function openWebsite(){if(uploadBusy.current||publishLock.current)return;try{await flush();location.assign('/design-studio-redesign/website')}catch(e){setNotice(`Your design could not be saved. ${e.message}`)}}
 async function tools(tab){try{await flush();location.assign(`/design-studio-redesign?advanced=1&tab=${encodeURIComponent(tab)}`)}catch(e){setNotice(e.message)}}
 async function publish(){if(uploadBusy.current||publishLock.current)return;publishLock.current=true;setPublishing(true);setPublishError('');setModal('');let didPublish=false;try{const revision=await flush();await api.publishEventDesign(eventId,{expected_revision:revision});didPublish=true;const [record,live]=await Promise.all([api.getEventDesign(eventId),api.publicDesignTheme(eventId,{experience_enabled:event?.experience_enabled,live_program_enabled:event?.live_program_enabled,festiome_enabled:event?.festiome_enabled})]);saver.current.accept(record);setSaved(record);if(signature(record.published_snapshot)!==signature(draft))throw Error('The published snapshot differs from this draft.');const expected=toPublicTheme(draft,templates,eventId);for(const key of ['colors','font_pairing','wording','pass_options','page_config','logo_image_url','image_settings','cover_image_url']){if(JSON.stringify(live[key]??null)!==JSON.stringify(expected[key]??null))throw Error(`The live ${key.replaceAll('_',' ')} did not match.`)}setNotice(`Published version ${record.published_version}. Guest-facing design verified.`)}catch(e){setPublishError(`${didPublish?'Publication completed, but verification needs attention. Do not republish blindly. ':''}${e.message}`)}finally{publishLock.current=false;setPublishing(false)}}
 async function showHistory(){try{await flush();const r=await api.designVersions(eventId);setVersions(r.versions||[]);setModal('history')}catch(e){setNotice(e.message)}}
 async function restore(version){try{const revision=await flush();const record=await api.restoreDesignVersion(eventId,{version,expected_revision:revision});setDraft(payloadOf(record));saver.current.accept(record);setSaved(record);setModal('');setNotice(`Version ${version} restored as a draft. Review and publish to change the live design.`)}catch(e){setNotice(e.message)}}
 function expand(){if(!previewUrl)return;try{writeDraftPreview(previewKey.current,eventId,theme);window.open(previewUrl,'_blank','noopener,noreferrer')}catch{setPreviewError('Allow site storage to open this draft preview.')}}
 if(!eventId)return <RedesignShell topActive="design" withEventSidebar={false} eventScoped><h1>Design Studio</h1><p>Select an event to begin.</p></RedesignShell>;
 if(!draft)return <RedesignShell topActive="design" withEventSidebar={false} eventScoped><h1>Design Studio</h1><a href="/design-studio-redesign/website">Event website ↗</a>{loadError?<p role="alert">{loadError} <button onClick={()=>location.reload()}>Retry loading</button></p>:<p role="status">Loading your design…</p>}</RedesignShell>;
 const colors={...DEFAULT_COLORS,...theme.colors};const layout=draft.page_config?.experience?.guestHubLayout||event?.guest_hub_layout||'classic';const landing=draft.page_config?.experience?.rsvpLayout||event?.rsvp_landing_layout||'current';const busy=publishing||uploading;const changes=signature(draft)!==signature(saved?.published_snapshot||{});
 const updateLayout=(key,value)=>config('page_config','experience',{...draft.page_config?.experience,[key]:value});
 function toggle(area,key,label){return <label className="studio-toggle"><span>{label}</span><input type="checkbox" checked={draft.page_config?.[area]?.[key]!==false} onChange={e=>config('page_config',area,{...draft.page_config[area],[key]:e.target.checked})}/></label>}
 return <RedesignShell topActive="design" withEventSidebar={false} eventScoped><div className={`studio-v2 ${mobilePreview?'studio-show-preview':''}`}><header className="studio-heading"><div><span className="studio-eyebrow">YOUR EVENT. YOUR EXPRESSION.</span><h1>Design Studio</h1><p>{event?.name||'Your event'} · One connected look, from invitation to event day.</p></div><div className="studio-heading-actions"><span role="status">{({loading:'Loading…',saved:'All changes saved',unsaved:'Unsaved changes',saving:'Saving…',error:'Save needs attention'})[saveState.status]}</span><button className="studio-website-button" disabled={busy} onClick={openWebsite}>Event website ↗</button><button disabled={busy} onClick={showHistory}>↶ Version history</button></div></header>
 {saveState.status==='error'&&<div role="alert" className="studio-error">{saveState.error}<button onClick={()=>flush().catch(()=>{})}>Retry save</button><button onClick={()=>setModal('reload')}>Reload server design</button></div>}{notice&&<p className="studio-notice" role="status">{notice}</p>}{publishError&&<p className="studio-error" role="alert">{publishError}</p>}
 <nav className="studio-steps" aria-label="Design steps">{STEPS.map((label,i)=><button disabled={busy} key={label} onClick={()=>{setStep(i);setMobilePreview(false)}} aria-current={step===i?'step':undefined}><span>{i+1}</span>{label}</button>)}</nav><div className="studio-mobile-switch"><button aria-pressed={!mobilePreview} onClick={()=>setMobilePreview(false)}>Edit design</button><button aria-pressed={mobilePreview} onClick={()=>setMobilePreview(true)}>See preview</button></div>
 <div className="studio-workspace"><section className="studio-editor" aria-label="Design controls"><fieldset disabled={busy}><legend className="studio-sr">{STEPS[step]}</legend>
 {surface==='flyer'&&<FlyerControls draft={draft} event={event||{}} eventId={eventId} onAssets={assets} onWording={(k,v)=>config('wording_config',k,v)} onBusy={v=>{uploadBusy.current=v;setUploading(v)}} disabled={busy} onDownload={downloadFlyer} downloading={downloading}/>}
 {surface!=='flyer'&&step===0&&<><h2>Start with a feeling.</h2><p>A coordinated palette and type pairing. Apply a theme, then make it yours.</p><div className="studio-theme-grid">{templates.map(t=><button className={`studio-theme ${draft.selected_template_id===t.id?'selected':''}`} key={t.id} aria-pressed={draft.selected_template_id===t.id} onClick={()=>edit(d=>({...d,selected_template_id:t.id,selected_flyer_template_id:d.selected_flyer_template_id||t.id,theme_config:{...d.theme_config,...(!keepBrand?{colors:{...DEFAULT_COLORS,...t.defaultColors},fontPairing:t.fontPairing}:{}),guestAppTheme:'event'}}))}><span className="studio-theme-art" style={{background:t.defaultColors?.background,color:t.defaultColors?.primary}}><b>{event?.name||'Your event'}</b><i style={{background:t.defaultColors?.accent}}/></span><strong>{t.name}</strong><small>{t.style}</small></button>)}</div><label className="studio-toggle">Keep my colours and typography<input type="checkbox" checked={keepBrand} onChange={e=>setKeepBrand(e.target.checked)}/></label><h3>Your current palette</h3><div className="studio-swatches">{Object.entries(colors).map(([key,color])=><span key={key} title={key} style={{background:color}}/>)}</div><p>Applying a theme keeps your event content and access rules.</p></>}
 {surface!=='flyer'&&step===1&&<><h2>Choose the guest experience.</h2><p>Changes remain in your design draft until publication.</p><label className="studio-field">RSVP landing page<select value={landing} onChange={e=>{updateLayout('rsvpLayout',e.target.value);setSurface('rsvp')}}><option value="current">Current invitation</option><option value="welcome">Welcome — visual event introduction</option></select></label><h3>After registration · GuestHub</h3>{Object.entries(LAYOUTS).map(([id,[name,description]])=><button className={`studio-layout ${layout===id?'selected':''}`} key={id} aria-pressed={layout===id} onClick={()=>{updateLayout('guestHubLayout',id);setSurface('hub')}}><span aria-hidden="true">▤</span><span><strong>{name}</strong><small>{description}</small></span>{layout===id&&<span>✓</span>}</button>)}{layout==='app'&&<><h3>Default app appearance</h3><AppearanceChoices value={draft.theme_config.guestAppTheme||'event'} colors={colors} onChange={v=>config('theme_config','guestAppTheme',v)}/><p>Event colours uses your custom brand. Guests can choose their own appearance.</p></>}</>}
 {surface!=='flyer'&&step===2&&<><h2>Make it your event.</h2><p>Shared branding first. Then the details for each surface.</p><Images eventId={eventId} assets={draft.asset_config} onChange={assets} disabled={publishing} onBusy={v=>{uploadBusy.current=v;setUploading(v)}}/><h3>Shared brand</h3><div className="studio-colors">{Object.entries(colors).map(([key,value])=><label key={key}><input aria-label={`${key} colour`} type="color" value={/^#[0-9a-f]{6}$/i.test(value)?value:'#194e3d'} onChange={e=>config('theme_config','colors',{...colors,[key]:e.target.value})}/><span>{key}<small>{value}</small></span></label>)}</div><label className="studio-field">Typography<select aria-label="Typography" value={theme.font_pairing||'modern-sans'} onChange={e=>config('theme_config','fontPairing',e.target.value)}>{Object.keys(FONTS).map(f=><option key={f} value={f}>{f.replaceAll('-',' ')}</option>)}</select></label><label className="studio-field">Event display title<input value={draft.wording_config.eventTitle??''} placeholder={event?.name||'Use event name'} onChange={e=>config('wording_config','eventTitle',e.target.value)} maxLength={180}/></label><label className="studio-field">Welcome message<textarea aria-label="Welcome message" value={draft.wording_config.customMessage||''} onChange={e=>config('wording_config','customMessage',e.target.value)} maxLength={1500}/></label><h3>RSVP presentation</h3>{toggle('hero','showTitle','Show hero title')}{toggle('hero','showHost','Show host in hero')}{toggle('about','show','Show About section')}{toggle('details','showVenue','Show venue details')}{toggle('details','showAdmission','Show admission note')}<h3>Specialist tools</h3><p>Your existing flyer, pass and certificate functions remain available.</p><div className="studio-tool-links">{['Flyer','Festio Pass','Certificates','Event Page','FestioHub'].map(t=><button key={t} onClick={()=>tools(t)}>{t} tools ↗</button>)}</div></>}
 {step===3&&<><h2>Ready for a closer look?</h2><p>Review every affected surface before publishing.</p><div className="studio-notice"><strong>{saved?.is_published?`Published version ${saved.published_version}`:'Not published yet'}</strong><p>{changes?'Your draft has unpublished changes.':'Your draft matches the published version.'}</p></div><h3>Changes in this draft</h3>{Object.keys(payloadOf(draft)).filter(k=>JSON.stringify(draft[k])!==JSON.stringify(saved?.published_snapshot?.[k]??(k.startsWith('selected_')?null:{}))).map(k=><p className="studio-change" key={k}>{({theme_config:'Colours, typography and appearance',wording_config:'Wording',asset_config:'Images and artwork',page_config:'Layout and page sections',selected_template_id:'Theme family',selected_flyer_template_id:'Flyer template'})[k]}</p>)}<ul className="studio-checklist"><li>Review RSVP and GuestHub on desktop and phone.</li><li>Check the pass and uploaded artwork.</li><li>Publishing updates the design; it does not change registration or guest permissions.</li></ul><p>Email preview is illustrative. Delivered wording is managed by message templates.</p><button className="studio-primary" disabled={saveState.status==='error'||!draft.selected_template_id} onClick={()=>setModal('publish')}>Publish new version →</button>{!draft.selected_template_id&&<p>Select a theme before publishing.</p>}</>}
 </fieldset><footer className="studio-editor-footer"><button disabled={step===0||busy} onClick={()=>setStep(x=>x-1)}>← Back</button>{step<3&&<button className="studio-primary" disabled={busy} onClick={()=>setStep(x=>x+1)}>{['Choose layout','Customize design','Review changes'][step]} →</button>}</footer></section>
 <section className="studio-preview"><div className="studio-preview-head"><div><strong>Your guest’s view</strong><small>Current draft · Guest actions disabled in preview</small></div><div>{['desktop','phone'].map(d=><button key={d} aria-pressed={device===d} onClick={()=>setDevice(d)}>{d==='phone'?'Phone':'Desktop'}</button>)}{['rsvp','hub','pass'].includes(surface)&&<button aria-label="Open full-size draft preview" onClick={expand}>↗</button>}</div></div><nav className="studio-surfaces" aria-label="Preview surface">{Object.entries(SURFACES).map(([key,name])=><button key={key} aria-pressed={surface===key} onClick={()=>setSurface(key)}>{name}</button>)}</nav>{previewError&&<p className="studio-error" role="alert">{previewError}</p>}<div className="studio-canvas" ref={canvas}>{surface==='flyer'?<div className="studio-flyer-preview">{flyerLoading&&<p role="status">Rendering your flyer…</p>}{flyerUrl&&<img src={flyerUrl} alt="Rendered flyer draft"/>}<button onClick={()=>tools('Flyer')}>Existing templates & advanced tools ↗</button></div>:surface==='email'?<div className="studio-email" style={{background:colors.surface,color:colors.text,fontFamily:FONTS[theme.font_pairing]}}><header style={{background:colors.primary,color:'#fff'}}>{draft.asset_config.logo_image_url&&<img src={draft.asset_config.logo_image_url} alt="Event logo"/>}<h2>{draft.wording_config.eventTitle||event?.name}</h2></header>{draft.asset_config.image_settings?.surfaces?.email!==false&&draft.asset_config.cover_image_url&&<img className="studio-email-cover" src={draft.asset_config.cover_image_url} alt={draft.asset_config.image_settings?.alt||''}/>}<section><h3>Welcome to your event.</h3><p>{event?.event_date?new Date(event.event_date).toLocaleDateString():'Date to be announced'} · {event?.venue_name}</p><p>This is a branding preview. Actual email wording and recipient details come from your message templates.</p><span className="studio-primary">Open my GuestHub</span></section></div>:<div className="studio-frame" style={{width:(device==='phone'?390:1280)*scale,height:(device==='phone'?844:900)*scale}}><iframe title={`${SURFACES[surface]} draft preview`} src={previewUrl||undefined} style={{width:device==='phone'?390:1280,height:device==='phone'?844:900,transform:`scale(${scale})`}}/></div>}</div><p className="studio-preview-caption">{surface==='flyer'?FLYER_SIZES[flyerSettings(draft.asset_config).size]:device==='phone'?'390 × 844':'1280 × 900'} · Scaled to fit. No live guest action is recorded.</p></section></div>
 {modal==='publish'&&<Dialog title="Publish this design?" onClose={()=>setModal('')}><p>This will publish your current design to guest-facing pages and email branding.</p><button className="studio-primary" onClick={publish}>Confirm publication</button></Dialog>}{modal==='reload'&&<Dialog title="Reload server design?" onClose={()=>setModal('')}><p>This discards unsaved changes in this browser. Copy any text you need before reloading.</p><button onClick={()=>location.reload()}>Discard local edits and reload</button></Dialog>}{modal==='history'&&<Dialog title="Version history" onClose={()=>setModal('')}><p>Restore loads a previous version into your draft. Publish separately to update guests.</p>{versions.length?versions.slice().reverse().map(v=><div className="studio-version" key={v.version}><span>Version {v.version}<small>{v.published_at?new Date(v.published_at).toLocaleString():'Earlier publication'}</small></span><button onClick={()=>restore(v.version)}>Restore draft</button></div>):<p>No published versions yet.</p>}</Dialog>}
 </div></RedesignShell>
}
