import { useEffect,useMemo,useState } from 'react'
import { api } from '../api'
import { ErrorRetryState,LoadingSkeleton } from './redesign/RedesignPrimitives'
import { Icon } from './redesign/RedesignShell'
import { selectedOutcomeIds } from './guidedSetupPhaseOneModel.mjs'
import { PHASE_FOUR_PROGRESS_PREFIX,phaseFourReadiness } from './guidedSetupPhaseFourModel.mjs'
import './GuidedSetupPhaseTwo.css'
const TEST_KEYS={team:'team_review',planner:'planner_review',seating:'seating_test',orders:'orders_test',logistics:'logistics_test',access:'access_test',checkin:'checkin_test',journey:'journey_test',gifts:'gift_test',giving:'giving_test',finance:'finance_review'}
const statusOf=r=>r.complete?'Complete':r.blocked?'Blocked':'Ready'
export default function GuidedSetupPhaseFour({eventId,onBack,notify}){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState('')
 async function load(){if(!eventId){setLoading(false);return}setLoading(true);setError('');const calls=await Promise.allSettled([api.listEvents(),api.getSetupProgress(eventId),api.listMembers(eventId),api.plannerDashboard(eventId),api.listTasks(eventId),api.listTables(eventId),api.getFloorPlan(eventId),api.listMenuCategories(eventId),api.listShipments(eventId),api.listZones(eventId),api.listGates(eventId),api.listGuests(eventId),api.listExperienceWorkflows(eventId),api.listRegistryItems(eventId),api.getRegistrySettings(eventId),api.donationCampaign(eventId),api.donationContributions(eventId),api.donationAudit(eventId)]);try{if(calls[0].status==='rejected')throw calls[0].reason;if(calls[1].status==='rejected')throw calls[1].reason;const event=calls[0].value.find(x=>x.id===eventId);if(!event)throw new Error("That event isn't available on this account.");const v=(i,f)=>calls[i].status==='fulfilled'?calls[i].value:f;setData({event,progress:v(1,{}).steps||{},members:v(2,[]),planner:v(3,null),tasks:v(4,[]),tables:v(5,[]),floorPlan:v(6,null),menuCategories:v(7,[]),shipments:v(8,[]),zones:v(9,[]),gates:v(10,[]),guests:v(11,[]),workflows:v(12,[]),registryItems:v(13,[]),registrySettings:v(14,null),campaign:v(15,null),contributions:v(16,[]),donationAudit:v(17,[]),dataFailures:calls.slice(2).map((r,i)=>r.status==='rejected'?i:null).filter(i=>i!==null)})}catch(e){setError(e.message||'Phase 4 readiness could not be loaded')}finally{setLoading(false)}}
 useEffect(()=>{load()},[eventId]) // eslint-disable-line react-hooks/exhaustive-deps
 const readiness=useMemo(()=>data?phaseFourReadiness({...data,selectedOutcomes:selectedOutcomeIds(data.progress)}):null,[data])
 async function verify(id){const key=TEST_KEYS[id];if(!key)return;setSaving(id);try{await api.setSetupProgress(eventId,`${PHASE_FOUR_PROGRESS_PREFIX}${key}`,'completed');notify(`${id.replaceAll('_',' ')} verification recorded`);await load()}catch(e){notify(e.message||'Verification could not be saved',true)}finally{setSaving('')}}
 if(!eventId)return <div className="gsp-empty"><h2>Select an event</h2></div>
 if(loading)return <div className="rr-panel"><div className="rd-panel-body"><LoadingSkeleton rows={9}/></div></div>
 if(error)return <div className="rr-panel"><div className="rd-panel-body"><ErrorRetryState message={error} onRetry={load}/></div></div>
 if(!readiness.recipes.length)return <div className="gsp-empty"><h2>No operations selected</h2><p>Choose operations, seating, check-in, gifts or donations to add Phase 4 procedures.</p><button className="rr-btn primary" onClick={onBack}>Review guest experience</button></div>
 const percent=readiness.total?Math.round(readiness.complete/readiness.total*100):0
 return <div className="gst-guide"><header className="gsp-guide-head"><div><span className="gsp-eyebrow">Phase 4 · operations and giving</span><h2>{data.event.name}</h2><p>{readiness.complete} of {readiness.total} selected procedures complete · {readiness.blocked} blocked</p></div><div className="gst-head-actions"><button className="rr-btn secondary" onClick={onBack}>Guest experience</button><button className="rr-btn secondary" onClick={load}>Refresh status</button></div></header><div className="gsp-progress" aria-label={`${percent} percent complete`}><span style={{width:`${percent}%`}}/></div>{readiness.dataFailures.length>0&&<div className="gst-warning"><Icon name="info" size={17}/><span>Some optional operational services are unavailable. Their procedures remain visible and are not reported as complete.</span></div>}{readiness.next&&<section className={`gsp-next${readiness.next.blocked?' blocked':''}`}><div><span className="gsp-eyebrow">Next recommended action</span><h3>{readiness.next.title}</h3><p>{readiness.next.description}</p></div><a className="rr-btn primary" href={readiness.next.route}>{readiness.next.action} →</a></section>}<div className="gst-recipe-list">{readiness.recipes.map(recipe=>{const key=TEST_KEYS[recipe.id];return <article className={`gst-recipe ${recipe.complete?'complete':recipe.blocked?'blocked':'ready'}`} key={recipe.id}><div className="gst-recipe-number">{recipe.complete?'✓':recipe.number}</div><div className="gst-recipe-copy"><div className="gst-recipe-title"><div><span>{recipe.number}</span><h3>{recipe.title}</h3></div><b>{statusOf(recipe)}</b></div><p>{recipe.description}</p><div className="gst-evidence"><strong>Live evidence</strong><span>{recipe.evidence}</span></div><div className="gst-recipe-actions"><a className="rr-btn secondary" href={recipe.route}>{recipe.action} →</a>{key&&!recipe.complete&&!recipe.blocked&&<button className="rr-btn primary" disabled={saving===recipe.id} onClick={()=>verify(recipe.id)}>{saving===recipe.id?'Saving…':'Mark rehearsal or review verified'}</button>}</div></div></article>})}</div><section className="gst-safety"><Icon name="info" size={18}/><div><strong>Operational integrity</strong><p>Access and check-in remain server-enforced. Gift List and Giving Hub reuse the contribution ledger, and only finance confirmation contributes to confirmed totals and projector progress.</p></div></section></div>
}
