// A recorded check describes its scope, not permission to launch a service.
export const CHECKLISTS = {
 live_materials:['Open the named presenter resource with the intended access.','Check its assigned session and published version.','Rehearse projection or playback on the intended display and record its identifier.'],
 rsvp:['Submit one controlled RSVP using the intended public or personal flow.','Confirm attendee roles and question answers in Guests.','Open the resulting pass and record what happened to confirmation delivery.'],
 tickets:['Complete one controlled checkout for the product and price being tested.','Confirm its order, attendee and pass records.','For a paid test, inspect the provider result; a free order verifies free checkout only.'],
 pass:['Open a named test attendee’s pass.','Check displayed identity, event and QR readability.','Record whether the chosen delivery channel actually reached the test recipient.'],
 channels:['Use only your authorized test recipient on each channel in scope.','Check final delivery or receipt, rather than provider acceptance alone.','Record the channel and message record IDs, excluding private pass tokens.'],
 automation:['Review routing, recipient consent and the schedule timezone.','Run one controlled message test and inspect its recipient record.','Confirm final delivery and record exactly which automation was tested.'],
 design:['Preview the selected design on desktop.','Preview the same draft on phone width.','Check event branding, dates, contrast and the primary guest action.'],
 invitation:['Open the intended RSVP page as a guest.','Check event details and the registration steps.','Complete a controlled registration and inspect its confirmation and pass.'],
 materials:['Generate the specific output being reviewed.','Check its event information, links and QR where applicable.','Inspect the downloaded output at its intended size.'],
 guesthub:['Open GuestHub using an authorized test guest.','Check the enabled services and that guest’s pass.','Check phone navigation and the intended party permissions.'],
 community:['Open the community with an eligible test adult.','Verify the configured junior restrictions.','Review the specific guest and moderator actions listed in your reference.'],
 team:['Confirm the assigned test staff member can open the event.','Check their intended role permissions.','Verify the handoff instructions and record the role tested.'],
 planner:['Review the event milestones and timezone.','Check assigned owners and the selected budget/vendor records.','Review the event-day runsheet and note any outstanding items.'],
 seating:['Inspect the chosen floor plan and capacity.','Check the named test guest’s seat assignment.','Review conflicts before making final seating assignments.'],
 orders:['Select a menu for a confirmed test guest at the configured selection stage.','Check that the kitchen shows the correct combination and guest.','Verify admission, selection and served-choice locks with test records.'],
 logistics:['Inspect the specific shipment and its recipients.','Check the vendor/packing/dispatch view in scope.','Record the delivery status observed; do not imply actual fulfillment from configuration alone.'],
 access:['Use a test credential allowed in the configured zone.','Test a credential that must be denied and inspect the reason.','Check capacity and in/out behavior for the named zone and gate.'],
 checkin:['Test the intended admission and exit modes with named test passes.','Check the result popup and manual lookup on the intended devices.','Rehearse loss of connectivity and sync; record devices and offline limitations.'],
 journey:['Open the published workflow for an authorized test guest.','Exercise its required steps and relevant consent/guardian rules.','Inspect the recorded progress and staff handoff.'],
 gifts:['Open the public gift list.','Make a controlled claim and inspect privacy and quantity rules.','Test release of that claim and confirm its saved state.'],
 giving:['Inspect the campaign and only its enabled payment methods.','Record one controlled contribution or pledge.','Check the public view; a pledge does not verify money received.'],
 finance:['Compare the selected contribution with its payment evidence.','Check the finance decision and audit history.','Reconcile the specific total tested without treating pledges as received money.'],
 conference:['Create or inspect the conference track.','Check programme ownership and intended audience.','Review the publication plan and record unresolved setup.'],
 calls:['Submit one controlled application through the public call.','Open the complete submission in the review workspace.','Record the specific review action and resulting state.'],
 programme:['Review session dates, room, speaker and audience.','Check conflicts and the intended published version.','Open the guest programme and verify the scoped sessions.'],
 speakers:['Review the selected speaker profile and assignments.','Check the relevant release or materials records.','Inspect public/private visibility for this speaker.'],
 partners:['Review the selected partner and its deliverables.','Check its event assignment and listing settings.','Inspect the intended public listing and record omissions.'],
 activities:['Open the specified activity as a test guest.','Submit a controlled response and inspect moderation where applicable.','Confirm the response appears correctly in the operator results.'],
 control:['Connect the intended display and publish the show workflow.','Rehearse presenter/moderator controls and guest response updates.','Inspect the live display and record devices and workflow tested.'],
 certificates:['Issue one test certificate to an eligible test attendee.','Open that certificate’s public verification page.','Check recipient, design and eligibility; this does not verify bulk issuance.'],
 analytics:['Inspect results for the named test activity.','Compare recorded responses and moderation state.','Review one export and record the filters used.'],
 results:['Review the event result categories in scope.','Compare the selected metrics to their source records.','Inspect an export and document any unresolved discrepancy.'],
 closeout:['Confirm intake and live operations are closed as intended.','Review finance, delivery and follow-up exceptions.','Check retention and exports; record outstanding work explicitly.'],
 reuse:['Create a controlled copy with new event dates.','Inspect which settings and private records were copied.','Verify the new draft requires its own readiness checks.'],
 help:['Follow help from the task being tested.','Check the action, error and next-step guidance.','Return to the same event and task.'],
 integrations:['Review the named connection’s scope and ownership.','Run a controlled sync and inspect the result.','Test its retry or disable behavior and record what was exercised.'],
}
