import {useEffect,useMemo,useState} from 'react'
import {api} from '../api'
import {ErrorRetryState,LoadingSkeleton} from './redesign/RedesignPrimitives'
import {Icon} from './redesign/RedesignShell'
import {selectedOutcomeIds} from './guidedSetupPhaseOneModel.mjs'
import {PHASE_FIVE_PROGRESS_PREFIX,phaseFiveReadiness} from './guidedSetupPhaseFiveModel.mjs'
import './GuidedSetupPhaseTwo.css'
const TEST_KEYS={conference:'conference_review',calls:'call_test',programme:'programme_review',speakers:'speaker_review',partners:'partner_review',activities:'activity_test',control:'control_rehearsal',materials:'materials_rehearsal',certificates:'certificate_test',analytics:'analytics_review'}
const statusOf=r=>r.complete?'Complete':r.blocked?'Blocked':'Ready'
export default function GuidedSetupPhaseFive({eventId,onBack,notify}){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState('')
 async function load(){if(!eventId){setLoading(false);return}setLoading(true);setError('');const calls=await Promise.allSettled([api.listEvents(),api.getSetupProgress(eventId),api.getConferenceCenter(eventId),api.liveProgramSessions(eventId),api.listSpeakers(eventId),api.listPartners(eventId),api.liveActivities(eventId),api.liveDisplays(eventId),api.liveWorkflows(eventId),api.listPresenterMaterials(eventId),api.listCertificateTemplates(eventId),api.listEventCertificates(eventId)]);try{if(calls[0].status==='rejected')throw calls[0].reason;if(calls[1].status==='rejected')throw calls[1].reason;const event=calls[0].value.find(x=>x.id===eventId);if(!event)throw new Error("That event isn't available on this account.");const v=(i,f)=>calls[i].status==='fulfilled'?calls[i].value:f;setData({event,progress:v(1,{}).steps||{},conference:v(2,null),sessions:v(3,[]),speakers:v(4,[]),partners:v(5,[]),activities:v(6,[]),displays:v(7,[]),workflows:v(8,[]),materials:v(9,[]),certificateTemplates:v(10,[]),certificates:v(11,[]),dataFailures:calls.slice(2).map((r,i)=>r.status==='rejected'?i:null).filter(i=>i!==null)})}catch(e){setError(e.message||'Phase 5 readiness could not be loaded')}finally{setLoading(false)}}
 useEffect(()=>{load()},[eventId]) // eslint-disable-line react-hooks/exhaustive-deps
 const readiness=useMemo(()=>data?phaseFiveReadiness({...data,selectedOutcomes:selectedOutcomeIds(data.progress)}):null,[data])
 async function verify(id){const key=TEST_KEYS[id];setSaving(id);try{await api.setSetupProgress(eventId,`${PHASE_FIVE_PROGRESS_PREFIX}${key}`,'completed');notify(`${id.replaceAll('_',' ')} review recorded`);await load()}catch(e){notify(e.message||'Review evidence could not be saved',true)}finally{setSaving('')}}
 if(!eventId)return <div className="gsp-empty"><h2>Select an event</h2></div>
 if(loading)return <div className="rr-panel"><div className="rd-panel-body"><LoadingSkeleton rows={9}/></div></div>
 if(error)return <div className="rr-panel"><div className="rd-panel-body"><ErrorRetryState message={error} onRetry={load}/></div></div>
 if(!readiness.recipes.length)return <div className="gsp-empty"><h2>No conference or live outcome selected</h2><p>Choose Conference Center, Festio Live, or certificates to add Phase 5 procedures.</p><button className="rr-btn primary" onClick={onBack}>Review operations</button></div>
 const percent=readiness.total?Math.round(readiness.complete/readiness.total*100):0
 return <div className="gst-guide"><header className="gsp-guide-head"><div><span className="gsp-eyebrow">Phase 5 · conference and live programme</span><h2>{data.event.name}</h2><p>{readiness.complete} of {readiness.total} selected procedures complete · {readiness.blocked} blocked</p></div><div className="gst-head-actions"><button className="rr-btn secondary" onClick={onBack}>Operations</button><button className="rr-btn secondary" onClick={load}>Refresh status</button></div></header><div className="gsp-progress" aria-label={`${percent} percent complete`}><span style={{width:`${percent}%`}}/></div>{readiness.dataFailures.length>0&&<div className="gst-warning"><Icon name="info" size={17}/><span>Some optional conference or live services are unavailable. Their procedures remain visible and are not reported as complete.</span></div>}{readiness.next&&<section className={`gsp-next${readiness.next.blocked?' blocked':''}`}><div><span className="gsp-eyebrow">Next recommended action</span><h3>{readiness.next.title}</h3><p>{readiness.next.description}</p></div><a className="rr-btn primary" href={readiness.next.route}>{readiness.next.action} →</a></section>}<div className="gst-recipe-list">{readiness.recipes.map(recipe=><article className={`gst-recipe ${recipe.complete?'complete':recipe.blocked?'blocked':'ready'}`} key={recipe.id}><div className="gst-recipe-number">{recipe.complete?'✓':recipe.number}</div><div className="gst-recipe-copy"><div className="gst-recipe-title"><div><span>{recipe.number}</span><h3>{recipe.title}</h3></div><b>{statusOf(recipe)}</b></div><p>{recipe.description}</p><div className="gst-evidence"><strong>Live evidence</strong><span>{recipe.evidence}</span></div><div className="gst-recipe-actions"><a className="rr-btn secondary" href={recipe.route}>{recipe.action} →</a>{!recipe.complete&&!recipe.blocked&&<button className="rr-btn primary" disabled={saving===recipe.id} onClick={()=>verify(recipe.id)}>{saving===recipe.id?'Saving…':'Mark test, rehearsal or review verified'}</button>}</div></div></article>)}</div><section className="gst-safety"><Icon name="info" size={18}/><div><strong>One programme source</strong><p>Sessions, tracks, speakers, partners and materials retain their canonical records. Live response rules and anonymity stay server-enforced, while certificate eligibility and verification remain within the certificate service.</p></div></section></div>
}
