export const PHASE_FIVE_PROGRESS_PREFIX='phase5_'
export const PHASE_FIVE_RECIPES=[
 {id:'conference',number:'5.1',title:'Establish Conference Center',outcome:'conference',route:'/conference-center',action:'Open Conference Center',description:'Confirm inherited identity, programme team, tracks, audience and publication timeline.'},
 {id:'calls',number:'5.2',title:'Run calls and abstract review',outcome:'conference',route:'/conference-center',action:'Manage calls and reviews',description:'Open the public call, review submissions and promote accepted work to canonical records.'},
 {id:'programme',number:'5.3',title:'Build and publish the programme',outcome:'conference',route:'/experience-redesign?tab=workflow',action:'Open programme builder',description:'Connect tracks, sessions, rooms, speakers, audiences and materials, then check conflicts and publish.'},
 {id:'speakers',number:'5.4',title:'Operate speakers',outcome:'conference',route:'/conference-center',action:'Open speaker operations',description:'Manage profiles, releases, assignments, materials, meetings and missing information.'},
 {id:'partners',number:'5.5',title:'Operate exhibitors and sponsors',outcome:'conference',route:'/conference-center',action:'Open partner operations',description:'Manage organizations, packages, booths, deliverables, public listings and attendee links.'},
 {id:'activities',number:'5.6',title:'Create live engagement',outcome:'live',route:'/live-redesign?tab=activities',action:'Open Live activities',description:'Create polls, quizzes, Q&A, word clouds, surveys and feedback with server-enforced response rules.'},
 {id:'control',number:'5.7',title:'Rehearse and run live',outcome:'live',route:'/live-redesign?tab=control%20room',action:'Open control room',description:'Connect presenter, moderator and displays, verify realtime behavior and rehearse the run of show.'},
 {id:'materials',number:'5.8',title:'Prepare presenter resources',outcomes:['live','conference'],route:'/live-redesign?tab=materials',action:'Open presenter materials',description:'Assign slides, PDFs and supported links to sessions, verify access and publish presenter resources.'},
 {id:'certificates',number:'5.9',title:'Issue certificates',outcome:'certificates',route:'/live-redesign?tab=certificates',action:'Open certificates',description:'Configure design and eligibility, issue a test, verify the public code, then batch issue and report.'},
 {id:'analytics',number:'5.10',title:'Analyze engagement',outcome:'live',route:'/live-redesign?tab=insights',action:'Open engagement insights',description:'Review response completeness, moderation, activity comparison, filters, exports and follow-up.'},
]
const rows=v=>Array.isArray(v)?v:(Array.isArray(v?.items)?v.items:[])
const checked=(p,k)=>p?.[`${PHASE_FIVE_PROGRESS_PREFIX}${k}`]==='completed'
export function selectedPhaseFiveRecipes(selected=[]){return PHASE_FIVE_RECIPES.filter(r=>r.outcome?selected.includes(r.outcome):r.outcomes.some(x=>selected.includes(x)))}
export function phaseFiveReadiness({progress={},selectedOutcomes=[],conference=null,sessions=[],speakers=[],partners=[],activities=[],displays=[],workflows=[],materials=[],certificateTemplates=[],certificates=[],dataFailures=[]}){
 const recipes=selectedPhaseFiveRecipes(selectedOutcomes),tracks=rows(conference?.tracks),submissions=rows(conference?.submissions),operations=rows(conference?.operations),sessionRows=rows(sessions),speakerRows=rows(speakers),partnerRows=rows(partners),activityRows=rows(activities),displayRows=rows(displays),workflowRows=rows(workflows),materialRows=rows(materials),templateRows=rows(certificateTemplates),certificateRows=rows(certificates)
 const profile=conference?.profile||{},callsReady=!!profile.public_token&&profile.calls_open===true&&rows(profile.enabled_call_types).length>0,reviewed=submissions.filter(x=>x.status&&x.status!=='pending').length
 const publishedSessions=sessionRows.filter(x=>x.published===true||x.is_published===true||x.status==='published').length,publishedWorkflows=workflowRows.filter(x=>x.published===true||x.status==='published').length
 const liveActivities=activityRows.filter(x=>['live','open','completed','closed'].includes(String(x.status||'').toLowerCase())).length,connectedDisplays=displayRows.filter(x=>x.connected===true||x.status==='connected'||x.last_seen_at).length
 const issued=certificateRows.filter(x=>String(x.status||'').toLowerCase()!=='revoked').length
 const state={
  conference:{complete:tracks.length>0&&checked(progress,'conference_review'),blocked:tracks.length===0,evidence:`${tracks.length} track${tracks.length===1?'':'s'} · ${operations.length} operational item${operations.length===1?'':'s'} · ${checked(progress,'conference_review')?'foundation reviewed':'review pending'}`},
  calls:{complete:callsReady&&checked(progress,'call_test'),blocked:!callsReady,evidence:`${callsReady?'Public call open':'Public call not open'} · ${submissions.length} submission${submissions.length===1?'':'s'} · ${reviewed} reviewed · ${checked(progress,'call_test')?'test submission verified':'test pending'}`},
  programme:{complete:sessionRows.length>0&&publishedSessions>0&&checked(progress,'programme_review'),blocked:sessionRows.length===0,evidence:`${sessionRows.length} session${sessionRows.length===1?'':'s'} · ${publishedSessions} published · ${checked(progress,'programme_review')?'conflict review verified':'review pending'}`},
  speakers:{complete:speakerRows.length>0&&checked(progress,'speaker_review'),blocked:speakerRows.length===0,evidence:`${speakerRows.length} speaker${speakerRows.length===1?'':'s'} · ${checked(progress,'speaker_review')?'operations reviewed':'missing-information review pending'}`},
  partners:{complete:partnerRows.length>0&&checked(progress,'partner_review'),blocked:partnerRows.length===0,evidence:`${partnerRows.length} exhibitor or sponsor record${partnerRows.length===1?'':'s'} · ${checked(progress,'partner_review')?'deliverables reviewed':'review pending'}`},
  activities:{complete:activityRows.length>0&&checked(progress,'activity_test'),blocked:activityRows.length===0,evidence:`${activityRows.length} activit${activityRows.length===1?'y':'ies'} · ${liveActivities} opened or completed · ${checked(progress,'activity_test')?'guest response test verified':'response test pending'}`},
  control:{complete:displayRows.length>0&&workflowRows.length>0&&checked(progress,'control_rehearsal'),blocked:displayRows.length===0||workflowRows.length===0,evidence:`${displayRows.length} display${displayRows.length===1?'':'s'} (${connectedDisplays} connected) · ${workflowRows.length} workflow${workflowRows.length===1?'':'s'} (${publishedWorkflows} published) · ${checked(progress,'control_rehearsal')?'rehearsal verified':'rehearsal pending'}`},
  materials:{complete:materialRows.length>0&&checked(progress,'materials_rehearsal'),blocked:materialRows.length===0,evidence:`${materialRows.length} presenter material${materialRows.length===1?'':'s'} · ${checked(progress,'materials_rehearsal')?'access and projection verified':'rehearsal pending'}`},
  certificates:{complete:templateRows.length>0&&issued>0&&checked(progress,'certificate_test'),blocked:templateRows.length===0,evidence:`${templateRows.length} template${templateRows.length===1?'':'s'} · ${issued} active certificate${issued===1?'':'s'} · ${checked(progress,'certificate_test')?'public verification tested':'test issuance pending'}`},
  analytics:{complete:activityRows.length>0&&checked(progress,'analytics_review'),blocked:activityRows.length===0,evidence:`${activityRows.length} activit${activityRows.length===1?'y':'ies'} available for comparison · ${checked(progress,'analytics_review')?'results and export reviewed':'analytics review pending'}`},
 }
 const visible=recipes.map(r=>({...r,...state[r.id]})),complete=visible.filter(x=>x.complete).length,blocked=visible.filter(x=>x.blocked).length
 return {recipes:visible,complete,total:visible.length,blocked,next:visible.find(x=>!x.complete)||null,dataFailures}
}
