import { useEffect, useState } from 'react'
import { Navigate } from 'react-router-dom'
import { api } from '../api'
import { useAuth } from '../context/AuthContext'
import GUIDE_CONTENT_SOURCE from '../guideContent.mjs?raw'
import { KNOWLEDGE_BASE_MD, QA_RELEASE_RUNBOOK_MD } from '../generated/internalMediaDocs.mjs'
import { COMPETITOR_PRICING_REVIEW_MD } from '../generated/competitorPricingReview.mjs'
import KT_CALENDARS_AND_FIXES_MD from '../docs/KT-2026-07-calendars-and-fixes.md?raw'

const REVIEW_TASK_TITLE = 'Competitor Pricing Strategy Review (Media Library)'
const REVIEW_TASK_NOTES = 'Shared comment thread for reviewing COMPETITOR-PRICING-STRATEGY-REVIEW-2026-07.md from the Media Library.'

export const INTERNAL_DOCS = [
  {
    title: 'Customer Help Source',
    description: 'Canonical structured content powering the customer-facing Help guide. Update this source, then regenerate the support knowledge base.',
    filename: 'guideContent.mjs',
    type: 'MJS',
    content: GUIDE_CONTENT_SOURCE,
  },
  {
    title: 'Support Knowledge Base',
    description: 'Generated Markdown used by the support service. Its source of truth is guideContent.mjs.',
    filename: 'knowledge_base.md',
    type: 'MD',
    content: KNOWLEDGE_BASE_MD,
  },
  {
    title: 'QA Release Certification Runbook',
    description: 'Internal instructions for safely executing the full staging checklist, including identity, reliability, security, accessibility, and evidence requirements.',
    filename: 'QA_RELEASE_CERTIFICATION_RUNBOOK.md',
    type: 'MD',
    content: QA_RELEASE_RUNBOOK_MD,
  },
  {
    title: 'Competitor Pricing Strategy Review (2026-07)',
    description: 'Full strategy draft including competitor pricing snapshots, confidence notes, and recommended Festio pricing posture.',
    filename: 'COMPETITOR-PRICING-STRATEGY-REVIEW-2026-07.md',
    type: 'MD',
    content: COMPETITOR_PRICING_REVIEW_MD,
  },
  {
    title: 'KT: Event Calendars, Task Attachments & Two Production Bugs (2026-07)',
    description: 'Engineering knowledge transfer for backend-2.2.80–2.2.83: Event Calendars + Contact Lists, Task attachments, the SignalHouse messageId fix (and the regression that preceded it), and the multi-org DEFAULT_ORG_ID resolution bug/fix. Staging only — read before the prod review pass.',
    filename: 'KT-2026-07-calendars-and-fixes.md',
    type: 'MD',
    content: KT_CALENDARS_AND_FIXES_MD,
  },
]

export const PDFS = [
  {
    title: 'Festio Introductory Guide',
    description: 'Short product introduction covering setup, invites, RSVP, check-in, results, and paid operations.',
    href: '/media/eventqr-intro-target-audience.pdf',
    filename: 'eventqr-intro-target-audience.pdf',
    type: 'PDF',
  },
  {
    title: 'Festio One-Pager',
    description: 'Compact sales handout for quick sharing. ⚠ Stale: no source file in the repo to regenerate — needs an external redesign pass to reflect current branding and features.',
    href: '/media/eventqr-onepager.pdf',
    filename: 'eventqr-onepager.pdf',
    type: 'PDF',
  },
  {
    title: 'Festio Pitch Deck',
    description: 'Longer investor/product pitch deck. Rebranded and price-corrected 2026-07-15 (regenerated by printing the HTML source below to PDF). Business KPIs (margin, CAC payback) and market/competitor claims are untouched — verify those before external use.',
    href: '/media/eventqr-pitch.pdf',
    filename: 'eventqr-pitch.pdf',
    type: 'PDF',
  },
]

export const HTML_ASSETS = [
  {
    title: 'Competitor Pricing Strategy Review (2026-07)',
    description: 'Formatted HTML review page for the full competitor pricing strategy document. Preserves all content with readable headings, lists, and tables for team review.',
    href: '/media/competitor-pricing-strategy-review-2026-07.html',
    filename: 'competitor-pricing-strategy-review-2026-07.html',
    type: 'HTML',
  },
  {
    title: 'Getting Started Tour',
    description: 'Interactive browser-based tour for prospects and new organizers. Refreshed 2026-07-15: fixed leftover "EQ" logo marks, corrected the "email is always free" claim (email metering shipped), removed the dead-end Full Guide link (Help is paid-only now), and added 2 new steps for invitation categories/auto-seating and FestioHub.',
    href: '/media/getting-started.html',
    filename: 'getting-started.html',
    type: 'HTML',
  },
  {
    title: 'Pitch Deck HTML',
    description: 'Editable HTML source for the pitch deck — this is the PDF\'s source of truth (print this page to regenerate it). Rebranded and pricing corrected 2026-07-15 against the live pricing_plans data. Business KPIs and competitor claims are untouched (already disclaimed on the slide) — verify before external use.',
    href: '/media/eventqr-pitch-v3-target-audience.html',
    filename: 'eventqr-pitch-v3-target-audience.html',
    type: 'HTML',
  },
  {
    title: "Women's Convention Experience Proposal",
    description: "Organizer-facing proposal deck for using Festio Experience at Masjid Mumineen Women's Convention 2026.",
    href: '/media/womens-convention-experience-proposal.html',
    filename: 'womens-convention-experience-proposal.html',
    type: 'HTML',
  },
  {
    title: 'NCNMO Platform 2026 Partnership Proposal',
    description: "Partnership proposal for the National Council of Nigerian Muslim Organizations' Platform 2026 (multi-day, multi-track, ~2,000 guests): $0 software/support with a $3,000 hard cost cap, real dashboard screenshots (reference event name blurred), and program/multi-session tracking.",
    href: '/media/ncnmo-platform-partnership-proposal.html',
    filename: 'ncnmo-platform-partnership-proposal.html',
    type: 'HTML',
  },
  {
    title: 'PAMAN Partnership Pitch Deck',
    description: "Slide deck for the Party Managers Association of Nigeria — an ongoing association partnership (not tied to a single conference), with real product screenshots from the demo event and a working referral link (?ref=paman). Arrow keys or the on-screen controls navigate; three fields (member benefit, contact name/email/phone) need filling in before sending.",
    href: '/media/paman-partnership-pitch.html',
    filename: 'paman-partnership-pitch.html',
    type: 'HTML',
  },
  {
    title: 'PAMAN Live Presentation Deck',
    description: "For presenting in person during the 15-minute meeting itself (not for sending ahead) — same screenshots and branding as the proposal deck, but opens with an agenda slide and closes with a \"what happens next\" timeline instead of asking to schedule the meeting you're already in.",
    href: '/media/paman-live-presentation.html',
    filename: 'paman-live-presentation.html',
    type: 'HTML',
  },
  {
    title: 'Staging QA Checklist',
    description: 'Full feature-by-feature test pass for staff to run on staging — ~55 test cases across setup, RSVP, check-in, FestioHub, FestioMe, messaging, and more. Testers enter their name, work through the checklist, and download a results file to send back.',
    href: '/media/festio-qa-checklist.html',
    filename: 'festio-qa-checklist.html',
    type: 'HTML',
  },
  {
    title: 'Staging QA Checklist — Modules',
    description: 'Same test cases as the full checklist, split into one page per feature area (25 modules) so you can hand a single module link to one tester. Each module has its own sign-in, progress bar, and Save button; results land in the same place (Console → QA checklist).',
    href: '/media/festio-qa-modules.html',
    filename: 'festio-qa-modules.html',
    type: 'HTML',
  },
]

// Refreshed 2026-07-15 against the live 2.0.69 app — includes features that
// shipped after the July-14 set (per-field RSVP requirements, invitation
// categories & auto-seating, multi-day display-only menus, FestioHub).
// SAME filenames as guideContent.mjs (Help guide) reuse this exact set, so
// keeping this list current keeps the in-app guide current too.
export const SCREENSHOTS = [
  ['Event setup', '/media/help2-event-setup.png'],
  ['Guests', '/media/help2-guests.png'],
  ['Invites and RSVP', '/media/help2-invites-rsvp.png'],
  ['RSVP form fields (per-field required/optional)', '/media/help2-rsvp-fields.png'],
  ['Invitation categories & auto-seating', '/media/help2-categories.png'],
  ['Seating', '/media/help2-seating.png'],
  ['Orders: multi-day menu (day + display-only)', '/media/help2-menu-fields.png'],
  ['Orders', '/media/help2-orders.png'],
  ['Entry areas', '/media/help2-entry-areas.png'],
  ['Team', '/media/help2-team.png'],
  ['Check-in', '/media/help2-checkin.png'],
  ['Results', '/media/help2-results.png'],
  ['Event Pass', '/media/help2-event-pass.png'],
  ['Guest invite (RSVP page)', '/media/help2-guest-invite.png'],
  ['Festio Pass — ticket with day-tabbed menu', '/media/help2-festio-pass.png'],
  ['FestioHub — Live Program, activity, food menu', '/media/help2-festiohub.png'],
  ['Deliveries', '/media/help2-deliveries.png'],
  ['Gift list', '/media/help2-gift-list.png'],
].map(([title, href]) => ({
  title,
  href,
  filename: href.split('/').pop(),
  type: 'PNG',
}))

function DownloadIcon({ className = '' }) {
  return (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.8} d="M12 3v12m0 0l-4-4m4 4l4-4M5 21h14" />
    </svg>
  )
}

function ExternalIcon({ className = '' }) {
  return (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.8} d="M7 17L17 7m0 0H9m8 0v8" />
    </svg>
  )
}

function AssetCard({ asset }) {
  return (
    <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl p-4 shadow-sm">
      <div className="flex items-start justify-between gap-3">
        <div>
          <div className="text-xs font-bold uppercase tracking-wide text-teal-700 dark:text-teal-300">{asset.type}</div>
          <h3 className="mt-1 font-semibold text-slate-950 dark:text-white">{asset.title}</h3>
          <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{asset.description}</p>
        </div>
      </div>
      <div className="mt-4 flex flex-wrap gap-2">
        <a href={asset.href} target="_blank" rel="noreferrer"
          className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 dark:border-slate-600 px-3 py-2 text-sm font-semibold text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700">
          <ExternalIcon className="h-4 w-4" />
          Open
        </a>
        <a href={asset.href} download={asset.filename}
          className="inline-flex items-center gap-1.5 rounded-lg bg-teal-600 px-3 py-2 text-sm font-semibold text-white hover:bg-teal-700">
          <DownloadIcon className="h-4 w-4" />
          Download
        </a>
      </div>
    </div>
  )
}

function ScreenshotCard({ asset }) {
  return (
    <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl overflow-hidden shadow-sm">
      <a href={asset.href} target="_blank" rel="noreferrer" className="block bg-slate-100 dark:bg-slate-900">
        <img src={asset.href} alt={asset.title} loading="lazy" className="h-40 w-full object-cover object-top" />
      </a>
      <div className="p-3">
        <div className="font-semibold text-sm text-slate-950 dark:text-white">{asset.title}</div>
        <div className="mt-3 flex gap-2">
          <a href={asset.href} target="_blank" rel="noreferrer"
            className="inline-flex items-center gap-1 rounded-md border border-slate-300 dark:border-slate-600 px-2.5 py-1.5 text-xs font-semibold text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700">
            <ExternalIcon className="h-3.5 w-3.5" />
            Open
          </a>
          <a href={asset.href} download={asset.filename}
            className="inline-flex items-center gap-1 rounded-md bg-teal-600 px-2.5 py-1.5 text-xs font-semibold text-white hover:bg-teal-700">
            <DownloadIcon className="h-3.5 w-3.5" />
            Download
          </a>
        </div>
      </div>
    </div>
  )
}

function InternalDocCard({ asset }) {
  function openDocument(download = false) {
    const blob = new Blob([asset.content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    if (download) link.download = asset.filename
    else link.target = '_blank'
    link.rel = 'noreferrer'
    document.body.appendChild(link)
    link.click()
    link.remove()
    window.setTimeout(() => URL.revokeObjectURL(url), 1000)
  }

  return (
    <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl p-4 shadow-sm">
      <div className="text-xs font-bold uppercase tracking-wide text-teal-700 dark:text-teal-300">{asset.type}</div>
      <h3 className="mt-1 font-semibold text-slate-950 dark:text-white">{asset.title}</h3>
      <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{asset.description}</p>
      <div className="mt-4 flex flex-wrap gap-2">
        <button type="button" onClick={() => openDocument(false)}
          className="inline-flex items-center gap-1.5 rounded-lg border border-slate-300 dark:border-slate-600 px-3 py-2 text-sm font-semibold text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700">
          <ExternalIcon className="h-4 w-4" /> Open
        </button>
        <button type="button" onClick={() => openDocument(true)}
          className="inline-flex items-center gap-1.5 rounded-lg bg-teal-600 px-3 py-2 text-sm font-semibold text-white hover:bg-teal-700">
          <DownloadIcon className="h-4 w-4" /> Download
        </button>
      </div>
    </div>
  )
}

function MediaReviewComments() {
  const [reviewEvents, setReviewEvents] = useState([])
  const [reviewEventId, setReviewEventId] = useState('')
  const [reviewTask, setReviewTask] = useState(null)
  const [reviewActivity, setReviewActivity] = useState([])
  const [reviewComment, setReviewComment] = useState('')
  const [bootLoading, setBootLoading] = useState(true)
  const [threadLoading, setThreadLoading] = useState(false)
  const [posting, setPosting] = useState(false)
  const [reviewErr, setReviewErr] = useState('')

  useEffect(() => {
    let cancelled = false
    async function loadEvents() {
      setBootLoading(true)
      setReviewErr('')
      try {
        const events = await api.listEvents()
        if (cancelled) return
        const sorted = [...events].sort((a, b) => String(a.name || '').localeCompare(String(b.name || '')))
        setReviewEvents(sorted)
        if (!sorted.length) {
          setReviewEventId('')
          return
        }
        const eventFromQuery = new URLSearchParams(window.location.search).get('event')
        const seeded = sorted.find((event) => event.id === eventFromQuery)
          || sorted.find((event) => event.status === 'active')
          || sorted[0]
        setReviewEventId((prev) => prev || seeded.id)
      } catch (e) {
        if (!cancelled) setReviewErr(e.message || 'Failed to load events')
      } finally {
        if (!cancelled) setBootLoading(false)
      }
    }
    loadEvents()
    return () => { cancelled = true }
  }, [])

  async function loadReviewThread(eventId) {
    if (!eventId) {
      setReviewTask(null)
      setReviewActivity([])
      return
    }
    setThreadLoading(true)
    setReviewErr('')
    try {
      const tasks = await api.listTasks(eventId)
      let task = tasks.find((item) => item.title === REVIEW_TASK_TITLE)
      if (!task) {
        task = await api.createTask(eventId, {
          title: REVIEW_TASK_TITLE,
          notes: REVIEW_TASK_NOTES,
        })
      }
      const activity = await api.listTaskActivity(eventId, task.id)
      setReviewTask(task)
      setReviewActivity(activity)
    } catch (e) {
      setReviewErr(e.message || 'Failed to load review thread')
      setReviewTask(null)
      setReviewActivity([])
    } finally {
      setThreadLoading(false)
    }
  }

  useEffect(() => {
    loadReviewThread(reviewEventId)
  }, [reviewEventId])

  async function postReviewComment(event) {
    event.preventDefault()
    const body = reviewComment.trim()
    if (!body || !reviewTask || !reviewEventId) return
    setPosting(true)
    setReviewErr('')
    try {
      await api.addTaskComment(reviewEventId, reviewTask.id, body)
      setReviewComment('')
      const activity = await api.listTaskActivity(reviewEventId, reviewTask.id)
      setReviewActivity(activity)
    } catch (e) {
      setReviewErr(e.message || 'Failed to post comment')
    } finally {
      setPosting(false)
    }
  }

  return (
    <section>
      <h2 className="text-sm font-bold uppercase tracking-wide text-slate-500 dark:text-slate-400 mb-3">Competitor pricing review comments</h2>
      <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl p-4 shadow-sm">
        <p className="text-sm text-slate-600 dark:text-slate-300">
          Team discussion thread for the internal doc <span className="font-semibold">COMPETITOR-PRICING-STRATEGY-REVIEW-2026-07.md</span>.
        </p>

        <div className="mt-3">
          <label htmlFor="review-event" className="block text-xs font-semibold text-slate-500 dark:text-slate-400 mb-1">
            Event context (shared task thread)
          </label>
          <select
            id="review-event"
            value={reviewEventId}
            onChange={(event) => setReviewEventId(event.target.value)}
            className="w-full md:w-[28rem] rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-700 px-3 py-2 text-sm text-slate-900 dark:text-white"
            disabled={bootLoading || !reviewEvents.length}
          >
            {!reviewEvents.length ? (
              <option value="">No events available</option>
            ) : reviewEvents.map((event) => (
              <option key={event.id} value={event.id}>{event.name}</option>
            ))}
          </select>
        </div>

        {reviewErr && <p className="mt-3 text-sm text-red-500">{reviewErr}</p>}

        <div className="mt-4 rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-900/40 p-3">
          {threadLoading ? (
            <p className="text-sm text-slate-500 dark:text-slate-400">Loading comments...</p>
          ) : reviewActivity.length === 0 ? (
            <p className="text-sm text-slate-500 dark:text-slate-400">No comments yet. Add the first review note.</p>
          ) : (
            <div className="space-y-3 max-h-72 overflow-y-auto pr-1">
              {reviewActivity.map((item) => (
                <div key={item.id}>
                  {item.kind === 'comment' ? (
                    <div className="text-sm">
                      <div className="text-slate-900 dark:text-white font-semibold">
                        {item.user_name || 'Team member'}
                        <span className="ml-2 text-xs font-normal text-slate-500 dark:text-slate-400">
                          {new Date(item.created_at).toLocaleString()}
                        </span>
                      </div>
                      <p className="mt-1 whitespace-pre-wrap text-slate-700 dark:text-slate-200">{item.body}</p>
                    </div>
                  ) : (
                    <p className="text-xs italic text-slate-500 dark:text-slate-400">
                      {item.user_name ? `${item.user_name} - ` : ''}{item.body}
                    </p>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>

        <form onSubmit={postReviewComment} className="mt-3 space-y-2">
          <label htmlFor="review-comment" className="block text-xs font-semibold text-slate-500 dark:text-slate-400">
            Add review comment
          </label>
          <textarea
            id="review-comment"
            value={reviewComment}
            onChange={(event) => setReviewComment(event.target.value)}
            rows={3}
            placeholder="Share pricing assumptions, risks, edits, or approval notes..."
            className="w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-700 px-3 py-2 text-sm text-slate-900 dark:text-white"
          />
          <button
            type="submit"
            disabled={posting || !reviewComment.trim() || !reviewTask || !reviewEventId}
            className="inline-flex items-center gap-1.5 rounded-lg bg-teal-600 px-3 py-2 text-sm font-semibold text-white hover:bg-teal-700 disabled:opacity-50"
          >
            {posting ? 'Posting...' : 'Post comment'}
          </button>
        </form>
      </div>
    </section>
  )
}

export default function MediaPage() {
  const { user } = useAuth()
  if (user === undefined) return null
  if (!user?.is_platform_superadmin) return <Navigate to="/" replace />

  return (
    <div className="max-w-6xl mx-auto px-4 py-8 space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-slate-950 dark:text-white">Media Library</h1>
        <p className="mt-2 text-sm text-slate-500 dark:text-slate-400">
          Operator-only links for viewing and downloading Festio PDFs, HTML tours, and product screenshots.
        </p>
        <p className="mt-1 text-xs text-slate-400 dark:text-slate-500">
          Screenshots, the Introductory Guide, the Getting Started tour, and the pitch deck last refreshed
          2026-07-15 against live 2.0.69. Only the one-pager still needs a redesign pass — see its card.
        </p>
        <p className="mt-1 text-xs text-amber-600 dark:text-amber-400">
          ⚠ Not yet reflected in the screenshots/tour/pitch deck below: Event Calendars, Contact Lists, or
          Task attachments (shipped 2026-07-25, staging only) — see the new KT doc for what's not yet in
          the sales/marketing assets.
        </p>
      </div>

      <section>
        <h2 className="text-sm font-bold uppercase tracking-wide text-slate-500 dark:text-slate-400 mb-3">Internal documentation</h2>
        <div className="grid md:grid-cols-3 gap-4">
          {INTERNAL_DOCS.map((asset) => <InternalDocCard key={asset.filename} asset={asset} />)}
        </div>
      </section>

      <MediaReviewComments />

      <section>
        <h2 className="text-sm font-bold uppercase tracking-wide text-slate-500 dark:text-slate-400 mb-3">PDF downloads</h2>
        <div className="grid md:grid-cols-3 gap-4">
          {PDFS.map((asset) => <AssetCard key={asset.href} asset={asset} />)}
        </div>
      </section>

      <section>
        <h2 className="text-sm font-bold uppercase tracking-wide text-slate-500 dark:text-slate-400 mb-3">HTML media</h2>
        <div className="grid md:grid-cols-2 gap-4">
          {HTML_ASSETS.map((asset) => <AssetCard key={asset.href} asset={asset} />)}
        </div>
      </section>

      <section>
        <h2 className="text-sm font-bold uppercase tracking-wide text-slate-500 dark:text-slate-400 mb-3">Product screenshots</h2>
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {SCREENSHOTS.map((asset) => <ScreenshotCard key={asset.href} asset={asset} />)}
        </div>
      </section>
    </div>
  )
}
