import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../api'
import './PublicPagesRedesignPage.css'

const SURFACES = [
  { id: 'invite', label: '✉️ Invitation & RSVP', tokenKey: 'inviteToken' },
  { id: 'calendar', label: '📅 Calendar', tokenKey: 'calendarToken' },
  { id: 'registry', label: '🎁 Registry', tokenKey: 'registryToken' },
  { id: 'vendor', label: '📦 Vendor', tokenKey: 'vendorToken' },
  { id: 'floor', label: '🗺️ Floor plan', tokenKey: 'floorToken' },
]

function StatePanel({ loading, error, onRetry, children }) {
  if (loading) return <div className="pp-tab-content"><p>Loading secure public page…</p></div>
  if (error) return (
    <div className="pp-tab-content">
      <div className="pp-tab-header"><h2>This link could not be opened</h2><p role="alert">{error}</p></div>
      <button className="pp-btn-primary" onClick={onRetry}>Try again</button>
    </div>
  )
  return children
}

function MissingToken({ surface }) {
  return (
    <div className="pp-tab-content">
      <div className="pp-tab-header">
        <h2>{surface}</h2>
        <p>Open this preview with the unguessable token generated by the event admin. No sample customer data is displayed.</p>
      </div>
    </div>
  )
}

function VendorSurface({ token }) {
  const [state, setState] = useState({ loading: true, error: '', data: null })
  const load = () => {
    setState((value) => ({ ...value, loading: true, error: '' }))
    api.getVendorPage(token)
      .then((data) => setState({ loading: false, error: '', data }))
      .catch((error) => setState({ loading: false, error: error.message || 'Vendor link not found', data: null }))
  }
  useEffect(load, [token])
  const lines = state.data?.lines || []
  return <StatePanel {...state} onRetry={load}>
    <div className="pp-tab-content">
      <div className="pp-tab-header"><h2>{state.data?.shipment_name}</h2><p>{state.data?.event_name} · secure read-only vendor list</p></div>
      {state.data?.notes && <p>{state.data.notes}</p>}
      <div className="pp-table-wrap"><table className="pp-table">
        <thead><tr><th>Recipient</th><th>Phone</th><th>Item</th><th>Qty</th><th>Status</th></tr></thead>
        <tbody>{lines.map((line) => <tr key={line.guest_id}>
          <td><strong>{[line.first_name, line.last_name].filter(Boolean).join(' ')}</strong></td>
          <td>{line.phone || '—'}</td><td>{line.item || state.data.shipment_name}</td><td>{line.quantity}</td>
          <td>{line.ship_status || 'pending'}</td>
        </tr>)}</tbody>
      </table></div>
      {!lines.length && <p>No recipients are currently included.</p>}
      <button className="pp-btn-download" onClick={() => api.downloadVendorXlsx(token, `${state.data.shipment_name}.xlsx`)}>⬇ Download spreadsheet (.xlsx)</button>
    </div>
  </StatePanel>
}

function RegistryClaim({ token, item, onClose, onSaved }) {
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [amount, setAmount] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const isFund = item.kind === 'fund'
  async function submit(event) {
    event.preventDefault()
    setBusy(true); setError('')
    try {
      const body = { claimer_name: name.trim(), claimer_email: email.trim() || undefined }
      if (isFund) {
        const minor = Math.round(Number(amount) * 100)
        if (!Number.isFinite(minor) || minor <= 0) throw new Error('Enter a valid contribution amount.')
        body.amount_minor = minor
      } else body.quantity = 1
      await api.claimRegistryItem(token, item.id, body)
      await onSaved()
    } catch (err) { setError(err.message || 'Gift could not be recorded') } finally { setBusy(false) }
  }
  return <div className="pp-modal-backdrop" onClick={onClose}><form className="pp-modal" onSubmit={submit} onClick={(event) => event.stopPropagation()}>
    <div className="pp-modal-head"><strong>{isFund ? 'Contribute' : 'Reserve'}: {item.title}</strong><button type="button" onClick={onClose}>×</button></div>
    <label className="pp-modal-label">Your name</label><input required className="pp-modal-input" value={name} onChange={(event) => setName(event.target.value)} />
    <label className="pp-modal-label">Email (optional)</label><input type="email" className="pp-modal-input" value={email} onChange={(event) => setEmail(event.target.value)} />
    {isFund && <><label className="pp-modal-label">Amount</label><input required type="number" className="pp-modal-input" value={amount} onChange={(event) => setAmount(event.target.value)} /></>}
    {error && <p role="alert">{error}</p>}
    <button disabled={busy} className="pp-btn-primary">{busy ? 'Saving…' : 'Confirm'}</button>
  </form></div>
}

function RegistrySurface({ token }) {
  const [state, setState] = useState({ loading: true, error: '', data: null })
  const [claiming, setClaiming] = useState(null)
  const [notice, setNotice] = useState('')
  const load = () => api.getRegistryPage(token)
    .then((data) => setState({ loading: false, error: '', data }))
    .catch((error) => setState({ loading: false, error: error.message || 'Registry not found', data: null }))
  useEffect(() => { setState({ loading: true, error: '', data: null }); load() }, [token])
  return <StatePanel {...state} onRetry={load}><div className="pp-tab-content">
    <div className="pp-tab-header"><h2>{state.data?.event_name}</h2><p>{state.data?.registry_message || 'Gift registry'}</p></div>
    {notice && <p role="status">{notice}</p>}
    <div className="pp-registry-grid">{(state.data?.items || []).map((item) => {
      const remaining = item.remaining ?? 1
      return <div className={`pp-registry-card${remaining <= 0 ? ' claimed' : ''}`} key={item.id}>
        <div className="pp-registry-type">{item.kind === 'fund' ? '💰 Fund' : item.kind === 'link' ? '🔗 Wish list' : '🎁 Item'}</div>
        <strong className="pp-registry-name">{item.title}</strong>
        {item.description && <p>{item.description}</p>}
        {(item.buy_url || item.external_url) && <a className="pp-registry-link" href={item.buy_url || item.external_url} target="_blank" rel="noreferrer">View list →</a>}
        {item.kind !== 'link' && <button disabled={remaining <= 0} className="pp-btn-primary" onClick={() => setClaiming(item)}>{item.kind === 'fund' ? 'Contribute' : remaining <= 0 ? 'Reserved' : 'Reserve'}</button>}
      </div>
    })}</div>
    {claiming && <RegistryClaim token={token} item={claiming} onClose={() => setClaiming(null)} onSaved={async () => { setClaiming(null); await load(); setNotice('Thank you! Your gift was recorded.') }} />}
  </div></StatePanel>
}

function CalendarSurface({ token }) {
  const [state, setState] = useState({ loading: true, error: '', data: null })
  const load = () => api.resolveCalendar(token).then((data) => setState({ loading: false, error: '', data })).catch((error) => setState({ loading: false, error: error.message || 'Calendar not found', data: null }))
  useEffect(() => { setState({ loading: true, error: '', data: null }); load() }, [token])
  return <StatePanel {...state} onRetry={load}><div className="pp-tab-content">
    <div className="pp-tab-header"><h2>{state.data?.title}</h2><p>{state.data?.description}</p></div>
    <div className="pp-cal-list">{(state.data?.events || []).map((event) => <a className="pp-cal-card" href={event.register_url} key={event.id}>
      <div className="pp-cal-card-left"><strong className="pp-cal-name">{event.name}</strong><div className="pp-cal-meta"><span>📅 {new Date(event.event_date).toLocaleString()}</span></div></div>
      <div className="pp-cal-card-right">{event.rsvp_status && <span className="pp-rsvp-badge">{event.rsvp_status}</span>}<span className="pp-btn-outline">{event.rsvp_status ? 'View / edit RSVP' : 'Register'}</span></div>
    </a>)}</div>
  </div></StatePanel>
}

function CanonicalSurface({ kind, token }) {
  const href = kind === 'invite' ? `/rsvp/${encodeURIComponent(token)}` : `/floor/${encodeURIComponent(token)}`
  const label = kind === 'invite' ? 'Open invitation & RSVP' : 'Open shared floor plan'
  return <div className="pp-tab-content"><div className="pp-tab-header">
    <h2>{kind === 'invite' ? 'Invitation & RSVP' : 'Shared floor plan'}</h2>
    <p>This surface uses the existing token-aware guest flow so re-entry, permissions, and saved state remain identical to the live application.</p>
  </div><a className="pp-btn-primary" href={href}>{label} →</a></div>
}

export default function PublicPagesRedesignPage() {
  const [searchParams, setSearchParams] = useSearchParams()
  const requestedTab = searchParams.get('tab')
  const tab = SURFACES.some((surface) => surface.id === requestedTab) ? requestedTab : 'invite'
  const tokens = useMemo(() => Object.fromEntries(SURFACES.map((surface) => [surface.id, searchParams.get(surface.tokenKey) || ''])), [searchParams])
  const current = SURFACES.find((surface) => surface.id === tab)
  const token = tokens[tab]
  return <div className="pp-public-shell">
    <div className="pp-topbar"><div className="pp-brand">F Festio</div><nav className="pp-tabs">{SURFACES.map((surface) => <button key={surface.id} className={`pp-tab${tab === surface.id ? ' active' : ''}`} onClick={() => {
      const next = new URLSearchParams(searchParams); next.set('tab', surface.id); setSearchParams(next)
    }}>{surface.label}</button>)}</nav></div>
    <main className="pp-main">
      {!token ? <MissingToken surface={current.label} />
        : tab === 'vendor' ? <VendorSurface token={token} />
          : tab === 'registry' ? <RegistrySurface token={token} />
            : tab === 'calendar' ? <CalendarSurface token={token} />
              : <CanonicalSurface kind={tab} token={token} />}
    </main>
  </div>
}
