import {useEffect,useState} from 'react'
import {useParams} from 'react-router-dom'

export default function TicketTransferPage(){
  const {token}=useParams(),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null)
  useEffect(()=>{fetch(`/api/ticketing/public/transfers/${encodeURIComponent(token)}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.detail);setData(d)}).catch(e=>setError(e.message))},[token])
  async function accept(){setBusy(true);try{const r=await fetch(`/api/ticketing/public/transfers/${encodeURIComponent(token)}/accept`,{method:'POST'}),d=await r.json();if(!r.ok)throw new Error(d.detail);setResult(d)}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',background:'#f1f5f4',padding:20,fontFamily:'Inter,system-ui'}}><section style={{maxWidth:520,padding:35,borderRadius:22,background:'#fff',boxShadow:'0 20px 60px #173c3718'}}><a href="/" style={{color:'#0f766e',fontWeight:900,textDecoration:'none'}}>F Festio</a>{error?<><h1>Transfer unavailable</h1><p>{error}</p></>:result?<><h1>Your ticket is ready</h1><p>The previous QR has been disabled and your new unique pass was emailed to you.</p><a href={result.pass_url} style={{display:'inline-block',padding:13,borderRadius:10,background:'#0f766e',color:'#fff',fontWeight:900,textDecoration:'none'}}>Open my pass</a></>:!data?<p>Loading secure transfer…</p>:<><small style={{color:'#64748b',fontWeight:800}}>SECURE TICKET TRANSFER</small><h1>A Festio ticket is waiting for you.</h1><p>This ticket will be registered to <b>{data.recipient_name}</b> at <b>{data.recipient_email}</b>. Accepting creates a new QR and permanently disables the sender’s QR.</p><button onClick={accept} disabled={busy||data.status!=='pending'} style={{padding:14,border:0,borderRadius:10,background:'#0f766e',color:'#fff',fontWeight:900}}>{data.status!=='pending'?'Already accepted':busy?'Creating your pass…':'Accept ticket transfer'}</button></>}</section></main>
}
