export const CONTENT = {
  // ─────────────────────────────────────────────────────────────────────────
  // ORGANIZER
  // ─────────────────────────────────────────────────────────────────────────
  organizer: {
    label: 'Organizer',
    icon: '🗂️',
    blurb: 'Create an event, invite guests, and run check-in on the day.',
    topics: [
      {
        id: 'org-start', icon: '🚀', title: 'Get started',
        intro: 'Everything begins with a free account — no credit card required.',
        steps: [
          'Go to festio.events and click Get Started.',
          'Sign in with Google (fastest) or create an account with any email address.',
          'You land straight in Event Setup with your own organisation already created.',
          'Click New Event to create your first event — you can run a free event with up to 25 guests right away.',
          'Want to try all paid features before buying? Use the trial request banner in Event Setup and send a request — we\'ll set you up.',
        ],
        tip: 'The free tier includes email invites, RSVP tracking, and up to 25 guests. Upgrade to an Event Pass to unlock SMS/WhatsApp, QR check-in, seating, entry areas, and more.',
      },
      {
        id: 'org-rsvp-only', icon: '✉️', title: 'Just need RSVPs? Start here',
        intro: 'Not every event needs seating, orders, or entry rules — sometimes you just want a clean guest list and RSVP count.',
        steps: [
          'When creating your event, choose attendance mode "Invitation / RSVP" and leave the RSVP form checkbox on — skip the other add-on checkboxes (Seating, Orders, Planner, etc.) entirely.',
          'Using the guided setup wizard instead? The RSVP step offers two cards: "Skip RSVP" or "With RSVP" — pick "With RSVP".',
          'That\'s it — you get a free-tier event with an invite page, RSVP tracking, and up to 25 guests, with no paid features enabled.',
          'You can always turn on more add-ons later from Guest Communication → Features & messaging once you actually need them.',
        ],
        tip: 'This path is the fastest way to get a shareable RSVP link out the door — add seating, check-in, or messaging channels only when the event actually needs them.',
      },
      {
        id: 'org-create', icon: '📅', title: 'Create your event',
        img: '/media/help2-event-setup.png',
        intro: 'Each event is a self-contained workspace with its own guests, invites, settings, and day-of tools.',
        steps: [
          'In Event Setup, click New Event.',
          'Enter the event name, an optional host/organiser display name, date & time, and a base URL slug (used in invite links).',
          'Save. Open the event — navigation is grouped into Setup (Start here, Guests, Invites & RSVP), Entry areas/rules, Add-ons (Seating, Orders, Deliveries, Gift list), and Team & settings. On a phone the sidebar becomes a dropdown.',
          'Under Guest Communication → Features &amp; messaging, toggle on the add-ons you need: Venue Access, Seating, Orders, Logistics, Registry (gift list), Speakers, Partners, Reminders, Experience, Planner, Festio Live, and FestioMe. Most require an Event Pass — once enabled it appears in the sidebar.',
          'The event you pick is remembered across Results, Check-in, and Orders — you only choose it once. The current event shows as a chip in the top bar.',
          'Set the event to Draft while preparing, Active on the day to enable check-in, and Ended afterwards.',
          'You can create multiple events — each is independent with its own guest list and settings.',
        ],
        tip: 'The base URL slug is used in all invite and RSVP links (e.g. festio.events/invite/your-slug). Keep it short and memorable.',
      },
      {
        id: 'org-guests', icon: '👥', title: 'Add your guest list',
        img: '/media/help2-guests.png',
        intro: 'Import from a spreadsheet, sync from Google Sheets, or add guests one at a time.',
        steps: [
          'Go to Start here → Download template. It contains exactly the columns your event uses — with an Excel dropdown for ticket types — so nothing is missed.',
          'Fill in the template and click Upload guest file. Your own spreadsheet works too: column names match in any case or spacing (First Name = first_name = FIRST NAME).',
          'Email is optional — guests without an email can still receive SMS/WhatsApp invites and be checked in by QR.',
          'For live sync: paste a Google Sheets or OneDrive share link. Import once, or set a sync interval while the event is Active.',
          'Watch the sync status badge: green = ok, amber = imported with warnings (unknown ticket types, rows over plan limit, invalid phone numbers), red = sync failed (check the share link is still public).',
          'Re-importing never creates duplicates — it fills in missing phone numbers, ticket types, addresses, and tags for existing guests.',
          'For Entry rules events: add a "tags" column (e.g. "VIP; Press") — unknown tags are created automatically and control which areas each guest may enter.',
          'The free tier allows up to 25 guests total. An Event Pass raises this limit based on the tier you choose.',
          'To add a single guest: Guests tab → Add guest, fill in the form.',
        ],
        tip: 'Column matching is flexible — "First Name", "first_name", "firstname" all map to the same field. The only required column is a name (first + last, or full name).',
        warn: 'Phone numbers must include the country code (e.g. +2348012345678 for Nigeria, +14155551234 for US) for SMS/WhatsApp delivery to work.',
      },
      {
        id: 'org-rsvp', icon: '✉️', title: 'Set up your RSVP & invite page',
        img: '/media/help2-invites-rsvp.png',
        intro: 'The invite page is what guests see when they open their link. Make it yours.',
        steps: [
          'Go to Invites & RSVP → Invitation page & RSVP.',
          'Choose Anyone with event link (one shared link, anyone can RSVP) or Only guests with personal invite link (unique private link per guest — only that guest can use it).',
          'Optionally: set an RSVP deadline, enable approval required (you manually approve each RSVP — only applies with "Anyone with event link"; personal invite links skip approval since you already control who\'s invited), add custom questions (dietary, t-shirt size, table preference, etc.), upload a cover image, and write a welcome message.',
          'Click "Preview invite page" to see exactly what guests will see before you send anything.',
          'For Orders events: add choices for meals, drinks, gifts, or any other item guests should select on the invite page.',
          'For Deliveries events: turn on address collection — guests enter their shipping address when they RSVP.',
          'Set a maximum RSVP count to close registrations once the venue is full.',
        ],
        tip: 'Personal invite links prevent forwarding and double-booking. Use them for formal events or when you need a precise headcount.',
      },
      {
        id: 'org-design-studio', icon: '🎨', title: 'Design Studio: brand your invite, pass & Guest Hub',
        badge: 'Paid',
        img: '/media/help2-design-studio.png',
        intro: 'Match your invite page, ticket, and Guest Hub to your event\'s look — colors, fonts, and layout, no design tool required.',
        steps: [
          'Open Design Studio from the sidebar (requires an Event Pass to publish; you can still browse and edit for free).',
          'Templates tab: browse ready-made template families (each covering your Event Page, Flyer, Pass, and Email together) and pick one as your starting point.',
          'Flyer tab: edit wording (title, date, venue) plus colors and font pairing for a shareable flyer image.',
          'Event Page tab: toggle hero sections, cover image fit and focus, and which event details show — with a live preview of your real invite page.',
          'Festio Pass tab: edit the admission wording, footer note, and FestioHub intro shown on every guest\'s ticket.',
          'Guest Hub tab: pick one of the ready-made visual themes — applies colors, font, and layout together across the RSVP page and Guest Hub in one click.',
          'Email Preview tab: check how your saved wording and colors look across every email type (invitation, RSVP confirmation, pass, reminder, broadcast, check-in confirmation).',
          'Publish tab: review the checklist, then Publish design to make your changes live for guests.',
        ],
        warn: 'Publishing requires an Event Pass — you can design for free, but guests won\'t see your changes until you upgrade and publish. There\'s also no rollback: if a published version has a mistake, publish a corrected version rather than trying to revert.',
      },
      {
        id: 'org-categories', icon: '🗂️', title: 'Invitation categories & auto-seating',
        intro: 'Let one person register a whole party — spouse, kids, guests — with everyone auto-seated in the right section.',
        steps: [
          'Guests tab → Invites & RSVP → turn on "Multi-invitee" so one submitter can register additional people alongside themselves.',
          'In Category invitee limits & table-category mapping, click + Add category for each group you want (e.g. Family, VIP, Staff).',
          'For each category, set a maximum number of invitees and choose which seating-table category the submitter and their invitees should land in (matched against the table categories you\'ve already created in Seating).',
          'On RSVP, the submitter is automatically seated in their bucket and each invitee in theirs — no manual seat assignment needed for that party.',
          'The auto-generated "Invitation category" question this creates is managed only from this panel, not the general RSVP questions list.',
        ],
        tip: 'Set up your seating table categories first — the category mapping dropdowns here are populated from table categories that already exist.',
      },
      {
        id: 'org-send', icon: '📤', title: 'Send invitations',
        img: '/media/help2-invites-rsvp.png',
        intro: 'Reach guests on the channel they actually check — WhatsApp, SMS, or email.',
        steps: [
          'Shared link: copy the event link and share it yourself (WhatsApp group, email, social). Or use Manual invite — search a specific guest and send them a personal link.',
          'Personal links: use Invites & RSVP to send to guests who have not been invited yet, remind no-replies, or resend links.',
          'Pick your channels: Email (always free), SMS (uses message credits), WhatsApp (uses message credits).',
          'Each guest receives their personal ticket QR automatically by email when they RSVP as Attending.',
          'For guests without email: if you have their phone number, their QR ticket is delivered via SMS or WhatsApp instead.',
          'Message credits are pre-purchased from the Event Pass area — top up as needed. Check your balance before a bulk send.',
          'For reminders, use Broadcast Message to nudge guests before the event or during arrival.',
        ],
        tip: 'Run a small test send to yourself first (add your own phone/email as a test guest) to confirm message formatting and delivery before sending to all guests.',
        warn: 'WhatsApp and SMS sends consume message credits — SMS costs more per message than WhatsApp (roughly 2 credits per SMS vs 1.5 per WhatsApp message by default). A bulk send to 300 guests can use several hundred credits, not just 300. Check the estimated cost shown before sending, and check your balance first — the send will stop mid-way if you run out.',
      },
      {
        id: 'org-track', icon: '✅', title: 'Track RSVPs & approvals',
        img: '/media/help2-guests.png',
        steps: [
          'The Guests tab shows every guest with their current status: Attending, Declined, Pending (submitted, awaiting your approval), or No reply.',
          'Each row also shows whether the guest has been checked in on the day.',
          'If "Approval required" is on: click a guest to approve or reject their RSVP. Use "Approve all" to confirm everyone at once.',
          'Use search, selection, and the status columns to find specific groups quickly.',
          'Use the guest tools to review or download event data when you need an offline list.',
          'Click any guest to see their details: RSVP answers, contact info, ticket type, tags, seat assignment, order choices, and check-in history.',
          'Update a guest\'s status, ticket type, or seat assignment manually if needed.',
        ],
        tip: 'Use the filter + bulk-select to approve, email, or change ticket types for a whole group at once.',
      },
      {
        id: 'org-broadcast', icon: '📣', title: 'Broadcast an update',
        img: '/media/help2-invites-rsvp.png',
        intro: 'Push a message to any subset of guests at any time — before, during, or after the event.',
        steps: [
          'Invites & RSVP → Broadcast Message.',
          'Write your message (plain text — keep it short for SMS/WhatsApp).',
          'Choose your target: All guests, RSVP Attending, RSVP Declined, No reply, Checked-in, or Not checked-in.',
          'Pick your channel(s): email, SMS, WhatsApp — or all three.',
          'Preview the estimated credit cost before sending.',
          'Hit Send. Delivery happens in the background — you can leave the page.',
          'Useful examples: venue change, schedule update, parking instructions, "doors open in 30 minutes", post-event thank-you.',
        ],
        warn: 'Broadcast sends are immediate and cannot be recalled once sent. Double-check your message and target group before confirming.',
      },
      {
        id: 'org-templates', icon: '✏️', title: 'Customize your message templates',
        img: '/media/help2-templates.png',
        intro: 'Every automatic message — invitations, RSVP confirmations, reminders, and more — has editable wording per channel.',
        steps: [
          'Communications → Messages tab → Templates.',
          'Each channel falls back to the default wording unless you save your own override — cards show a Custom or Default badge.',
          'Click Edit on a template to change its Email subject/body and SMS/WhatsApp/MMS body text. Use the listed placeholders (e.g. guest name, event name, Guest Hub link, ticket link) to personalize each send.',
          'Use Preview to see how it renders, or Test send to email/text it to yourself before it goes live.',
          'Reset returns a customized template to the default wording — only available once you\'ve actually customized it.',
          'Recent template changes shows an audit log of who edited what and when.',
        ],
        warn: 'The WhatsApp body field you edit here is not what guests actually receive. Every real WhatsApp send goes through a fixed, Meta-approved template managed in Bird\'s dashboard — the platform shows an inline reminder of this wherever you edit WhatsApp wording. To change what WhatsApp messages actually say, submit a new template for Meta review (see the WhatsApp Templates section below the editor — a one-time $5 review fee applies) rather than editing the text field.',
      },
      {
        id: 'org-seating', icon: '🍽️', title: 'Seating & orders',
        badge: 'Paid',
        imgs: ['/media/help2-menu-fields.png', '/media/help2-orders.png'],
        intro: 'Assign tables, let guests pick meals, drinks, gifts, or other items, and give staff a live Orders view.',
        steps: [
          'Guest Communication → Features &amp; messaging → turn on Seating and/or Orders (requires an Event Pass).',
          'Seating tab → Create tables: set a name (Table 1, Head Table, VIP Round…), capacity, and optionally a section label.',
          'Use Auto-assign to fill tables automatically by RSVP order, or drag guests to specific seats manually.',
          'Reserve seats: mark seats as unavailable (blocked for a VIP arrival, accessibility needs, etc.).',
          'Partner pairing: guests can link their plus-one on their ticket page — auto-assign keeps them together.',
          'Orders tab → Add categories (Meals, Drinks, Gifts, Merchandise) and items with optional descriptions.',
          'Guests see the available items on their ticket page and pick before your deadline.',
          'Orders view: a read-only view your staff or caterer can open on a tablet — shows each table\'s order totals and individual choices, updating live.',
          'Use the seating plan and order totals as the working list for your caterer or fulfilment team.',
        ],
        tip: 'Use the RSVP deadline as your cutoff when you do not want guests changing item choices at the last minute.',
      },
      {
        id: 'org-access', icon: '🎫', title: 'Entry areas & ticket rules',
        badge: 'Paid',
        img: '/media/help2-entry-areas.png',
        intro: 'Control which guests can enter which areas of your venue — enforced automatically at every scan.',
        steps: [
          'Guest Communication → Features &amp; messaging → turn on Venue Access (requires an Event Pass).',
          'Entry areas tab → Areas: create the areas in your venue — Main Hall, VIP Lounge, Backstage, Green Room, etc. Set an optional capacity limit and direction mode (Entry only / Exit only / Both).',
          'Ticket types: create tiers — GA (General Admission), VIP, Press, Staff, Speaker. For each type, choose which zones they may enter. Leave empty to allow all zones.',
          'Assign ticket types: set a guest\'s type one by one from their profile, or include a ticket_type column in your imported spreadsheet.',
          'Tags: create classifiers (VIP, 21+, Speaker, Media…) for finer control — a guest can have multiple tags. Set zone rules to require specific tags.',
          'Gates: create a named gate for each scanner position (e.g. "Main Entrance", "VIP Gate", "Backstage Door"). Pin it to a zone + direction. Staff select their gate once — access rules are enforced automatically.',
          'Analytics: live occupancy per zone, peak arrival times, room-to-room flow, and each guest\'s full journey through the venue.',
        ],
        tip: 'Gates are the easiest setup for multi-zone events: staff just select "I\'m at Main Entrance" and scan — the zone and direction are automatic for every scan after that.',
      },
      {
        id: 'org-sections', icon: '🔲', title: 'Section scanning (multi-entrance seating)',
        badge: 'Paid',
        intro: 'For events seated by table group with two or more entrances — each scanner routes walk-ins and manual check-ins into the section it\'s assigned to.',
        steps: [
          'Guest Communication → Features & messaging → turn on Section scanning (only shown once you have table groups set up in Seating).',
          'On the Team page, assign each staff member (or each device) the table-group section they\'re stationed at.',
          'Walk-ins and manual check-ins scanned at that station seat into that section automatically, instead of a single shared default group.',
          'A guest\'s own assigned group always wins if it doesn\'t match the scanning station — there\'s no override flow by design.',
        ],
        warn: 'Section scanning and Venue Access (zone/gate-based entry rules) can\'t both be on for the same event — turn one off before enabling the other.',
      },
      {
        id: 'org-experience', icon: '🧭', title: 'Experience workflows: consent, souvenirs, rooms & sessions',
        badge: 'Paid',
        img: '/media/help2-org-experience.png',
        intro: 'Build a step-by-step operational journey for each guest — check-in, consent, seating, souvenirs, sessions — tracked from Setup to departure.',
        steps: [
          'Guest Communication → Features & messaging → turn on Experience, then open Experience settings.',
          'Workflow tab: start from a template (VIP Dinner Guest Journey, Conference Registration, Wedding Reception, Simple Check-in) or build your own from steps like check-in, consent, seating assignment, meal selection, souvenir, badge, room assignment, session attendance, or feedback.',
          'Only one workflow can be live per event at a time. Publish makes it active; to change a published workflow you Clone it first, then publish the clone.',
          'Consent tab: guests sign consent from their Festio Pass page — this only becomes available after they\'ve checked in, so don\'t make an earlier step depend on consent being signed first.',
          'Guests tab, Feedback tab, and Analytics tab track each guest\'s progress through the workflow and completion rates per step.',
          'Inbound Automations and Messages let you react to step completion (e.g. a message once a guest is seated).',
        ],
        warn: 'Step ordering matters: the default "welcome pack" preset requires consent before souvenir pickup, but consent can\'t be signed until after check-in — putting a consent-dependent step earlier than check-in will silently block guests from completing it.',
      },
      {
        id: 'org-logistics', icon: '📦', title: 'Deliveries: ship merch, aso-ebi & gifts',
        badge: 'Paid',
        img: '/media/help2-deliveries.png',
        steps: [
          'Guest Communication → Features &amp; messaging → turn on Logistics.',
          'Deliveries tab → New Shipment. Name it (e.g. "Aso-ebi fabric", "Welcome bag", "Gift delivery").',
          'Add items to the shipment — each with a name, optional size/variant, and quantity.',
          'Guest addresses: collected automatically if you turned on address collection in RSVP settings, or import them via the ship_address columns in your guest list.',
          'Packing list: a shareable read-only page your fulfilment vendor opens — they see guest names, addresses, and items without needing a login.',
          'Mark items as packed/shipped per guest — or bulk-mark a whole shipment.',
          'Use multiple shipments for different waves (pre-event aso-ebi vs post-event gift delivery).',
        ],
        tip: 'Add the shipping address fields to your RSVP custom questions so guests fill them in when they confirm — no separate data collection needed.',
      },
      {
        id: 'org-registry', icon: '🎁', title: 'Gift list',
        badge: 'Paid',
        img: '/media/help2-gift-list.png',
        steps: [
          'Guest Communication → Features &amp; messaging → turn on Registry.',
          'Gift list tab → Add items: paste a store link and the platform auto-fills the title, image, and price. Or add cash funds (e.g. "Honeymoon fund", "New home contribution").',
          'Write a welcome message shown at the top of the gift list page.',
          'Share the public gift list link directly — paste it in WhatsApp, add it to your invite page, or print it on physical invites.',
          'Guests mark what they\'ll bring (or how much they\'re contributing) so nobody doubles up.',
          'No money moves through Festio — guests purchase or give directly to you. The gift list is purely a wish-list coordination tool.',
          'You can see who has claimed each item from the Gift list tab.',
        ],
      },
      {
        id: 'org-ticketing', icon: '🎫', title: 'Ticket sales',
        img: '/media/help2-ticketing.png',
        intro: 'Sell paid tickets — general admission, VIP, donations, or external registrations — instead of (or alongside) free RSVP.',
        steps: [
          'Open Ticket sales from the sidebar. 01 Availability: turn on "Sell tickets for this event".',
          '02 Payouts: connect Paystack or Stripe, choose whether the processor fee is added to the buyer\'s total or deducted from your proceeds, and optionally add event tax.',
          '03 Ticket types: + Add this ticket type — choose a real ticket (grants admission), a donation/sponsorship (payment only, no pass), or an external registration (price shown here, buyer registers/pays elsewhere). Set name, price, quantity, and which access level it grants.',
          '04 Catalog: review and Hide any ticket type you want to pull from sale.',
          'Need to comp someone in? Issue complimentary pass(es) admits guests without payment.',
          '05 Publish & share: View events opens the public ticket marketplace; Copy link gives your event\'s own storefront page; Copy embed gives an iframe snippet for your own website.',
          '06 Live sales report: gross revenue, tickets sold, refunds, your proceeds, and a full order ledger with approve/refund actions and a downloadable CSV.',
          'A purchased ticket issues the same QR pass as a free RSVP guest — check-in works identically either way. A full refund voids that pass and releases the inventory.',
        ],
        warn: 'Ticket sales currently runs in test mode only — payments use Stripe/Paystack test keys, so no real money changes hands yet. Treat it as a preview of the checkout flow, not a live revenue channel, until this is confirmed generally available.',
      },
      {
        id: 'org-community', icon: '💬', title: 'FestioMe: guest community & groups',
        badge: 'Paid',
        img: '/media/help2-org-community.png',
        intro: 'A community space for your guests — sub-groups, channels, and announcements, reachable from their Guest Hub.',
        steps: [
          'Guest Communication → Features & messaging → turn on FestioMe, then Open FestioMe.',
          'Community tab → Create group: set a join policy — Open, Requires approval, or Invite only. Tick "Event-team support group" for a staff-only, unlisted group.',
          'Inside a group, + Create channel: choose Discussion, Announcement, or Staff, and optionally make it private to chosen members.',
          'Group Settings: write community rules (shown to members) and change the join policy any time.',
          'Moderation tab: approve or deny join requests, and review reported messages.',
          'Guests reach FestioMe from their Guest Hub — their Festio Pass signs them straight in, no separate account needed.',
        ],
        warn: 'FestioMe\'s own Moderation tab does not cover 1:1 guest-to-host direct messages — those are moderated from Communications → Guest Communication instead.',
      },
      {
        id: 'org-guest-communication', icon: '💌', title: 'Guest Communication: replies & direct messages',
        steps: [
          'Communications → Guest Communication tab shows every guest reply and direct message in one inbox, across email, SMS, and WhatsApp.',
          'Reply to a guest directly from the thread — it goes out on whichever channel they messaged you on.',
          'This is also where you moderate 1:1 guest↔host direct messages and FestioMe guest chat — FestioMe\'s own Moderation tab links back here for that.',
          'Use this alongside Messages (template wording) and Scheduler (timed sends) — Guest Communication is specifically for two-way conversations, not outbound campaigns.',
        ],
      },
      {
        id: 'org-tasks', icon: '✅', title: 'Tasks: run your to-do list as a team',
        img: '/media/help2-org-tasks.png',
        intro: 'Assign and track the work behind your event — who\'s doing what, by when.',
        steps: [
          'Team & Tasks page → Tasks tab → + Task: set a title, assignee, due date, and notes.',
          'Switch between List and Board view depending on how your team likes to work.',
          'Open a task to add subtasks, attach files, or post a comment in its activity thread.',
          'Move a task through Open → In progress → Done as work happens.',
          'My Tasks (from your own account) shows everything assigned to you across every event you have access to, separate from any one event\'s task list.',
        ],
        tip: 'Planner\'s Timeline milestones can link to tasks automatically — a milestone\'s linked tasks show up in both places.',
      },
      {
        id: 'org-planner', icon: '📘', title: 'Planner: budget, vendors & run sheet',
        badge: 'Paid',
        img: '/media/help2-planner.png',
        intro: 'Keep the planning work — budget, vendors, contracts, timeline — next to your guest list instead of scattered across spreadsheets.',
        steps: [
          'Guest Communication → Features & messaging → turn on Planner, then Open your planner.',
          'Budget tab: track allocated vs. actual spend by category.',
          'Vendors and Procurement tabs: a workspace per vendor for quotes and orders.',
          'Contracts tab: draft a contract with title and terms, Save draft, then Send — the vendor signs from their own portal link. Status moves through draft → sent → signed, showing who signed and when.',
          'Timeline tab: add milestones and link tasks to each one (shares the same task list as Team & Tasks) — this is a milestone list, not a Gantt chart.',
          'Runsheet and Documents tabs: your day-of schedule and shared files in one place.',
        ],
        tip: 'Vendor e-signature happens entirely in the vendor\'s own portal view — you don\'t need to chase a separate signing tool.',
      },
      {
        id: 'org-live', icon: '🎤', title: 'Festio Live: quizzes, polls & surveys',
        badge: 'Paid',
        intro: 'Live quizzes, polls, ratings, surveys, Q&A, and word clouds — guests join and respond from their own phone, with results on a presenter screen or venue TV.',
        steps: [
          'Guest Communication → Features &amp; messaging → turn on Festio Live (requires an Event Pass).',
          'Open Festio Live from the sidebar. Click + New activity and choose a type: Quiz, Poll, Survey, Rating, Feedback, Q&A, Word Cloud, or Live Voting.',
          'Add questions: single/multiple choice, true/false, rating, open text, number, ranking, quadrant (2×2 grid), or image click. Quizzes can award points and run a leaderboard.',
          'Set the activity to Live when you\'re ready to start. Guests can then join and respond in real time.',
          'Guests join automatically from their Guest Hub — a "Join Festio Live" button appears on their ticket page whenever an activity is live for their event or current session. No app or extra sign-in needed.',
          'No personal invite links yet, or a broadcast-style audience (e.g. a keynote)? Share a join code or QR instead — guests go to festio.events/live/join and enter the 6-character code, or scan a QR you display on screen.',
          'Displays tab → create a Display for each TV/projector/presenter screen. Assign it an activity and a scene (live results, leaderboard, word cloud, etc.) and open its link on that screen — it updates in real time.',
          'For a guided, presenter-paced show (like a live quiz night), use Start guided show — it walks the room through each question with an intro, answering window, reveal, and results automatically.',
          'For Survey and Feedback activities: once you have responses, use Download report on the Displays tab to get a full PDF — every question, including open-text answers, not just what fits on the TV screen.',
        ],
        tip: 'Turn on "Moderate text" when creating an open-text, word-cloud, or Q&A activity so you can approve responses before they appear on the public display.',
        warn: 'Quiz and Poll results are visible to everyone watching the display as soon as you reveal them — don\'t reveal until every guest you\'re expecting has answered.',
      },
      {
        id: 'org-team', icon: '🧑‍🤝‍🧑', title: 'Add your team',
        img: '/media/help2-team.png',
        steps: [
          'Team tab → "Add a teammate" → enter their email address and choose a role.',
          'Admin role: can manage the event (edit settings, guests, seating, etc.). Full access except billing.',
          'Staff role: can only check in guests and view Check-in/Results for their assigned events. Cannot edit anything.',
          'Orders access: read-only access to the Orders view for their assigned events. No check-in access.',
          'The teammate signs in with that exact email — their account links to your organisation automatically.',
          'Assign the teammate to specific events from the Team tab — they only see events they\'ve been assigned to.',
          'Remove a teammate from the Team tab at any time. Their account continues to exist but loses access to your events.',
        ],
        tip: 'Add all check-in staff before the event day. Have them test-login and open the Check-in page the day before so there are no surprises on the day.',
      },
      {
        id: 'org-checkin', icon: '🎟️', title: 'Check-in day',
        img: '/media/help2-checkin.png',
        steps: [
          'The day before: set the event to Active in Start here. This enables Check-in to process guests.',
          'Ensure all scanning staff are added to the Team tab and assigned to this event.',
          'Share the Check-in page with staff. No app install — it runs in any mobile browser.',
          'Staff open Check-in → choose their gate (or set area + direction manually) → tap Start camera.',
          'Each guest shows their QR code (from email, SMS, WhatsApp, or their ticket page). Staff point the camera — admission is instant.',
          'Green = admitted. Yellow = already admitted (duplicate scan). Red = denied (wrong zone, at capacity, or needs an Event Pass).',
          'For walk-in guests not on the list: Guests tab → Add guest → assign them a ticket type → their QR appears immediately for scanning.',
          'Results updates in real time — open it on a separate screen to monitor check-ins live.',
          'After the event: set to Ended to disable further check-ins. Review the full check-in record from the Guests tab.',
        ],
        tip: 'Test scanning works on at least one device before guests arrive. Scan your own guest entry to confirm the green admitted screen appears.',
        warn: 'Check-in requires the event to be set to Active. If guests are getting "Event not active" errors, check the event status in Start here.',
      },
      {
        id: 'org-dashboard', icon: '📊', title: 'Results',
        img: '/media/help2-results.png',
        steps: [
          'Open Results from the nav during or after your event.',
          'Stat tiles: Expected, Checked in, Declined, Walk-ins, Checked out, and how many confirmed guests haven\'t arrived yet.',
          'The ring chart shows the percentage of expected guests checked in so far — a single completion number, not an RSVP breakdown.',
          'Attendance tab: a cumulative arrival chart comparing actual check-ins against an even expected pace throughout the day, plus an hour-by-hour breakdown — shows when your peak entry times were.',
          'Venue Access events: a live occupancy bar per zone (from the Attendance/Operations tabs). Turns amber near capacity, red once full.',
          'Invitations, Meals, Program, and Experience tabs cover RSVP status, order choices, session attendance, and guest-journey progress respectively.',
          'Per-table order totals and packing/fulfilment lists live under Orders and Deliveries, not Results — Results is about attendance, not table-by-table fulfilment.',
          'Results auto-refreshes automatically — no need to reload manually.',
          'Staff and Orders access roles can view Results for their assigned events when permitted (read-only).',
        ],
        tip: 'Put Results on a tablet at the organiser desk so you can monitor arrivals in real time without leaving your post.',
      },
      {
        id: 'org-upgrade', icon: '💳', title: 'Event Pass & message credits',
        img: '/media/help2-event-pass.png',
        steps: [
          'Free tier: email invites, up to 25 guests, Festio branding on invite pages, no paid features.',
          'Event Pass: buy per event in Invites & RSVP → Event Pass. Unlocks SMS/WhatsApp invites, more guests, QR check-in, seating & orders, entry areas, deliveries, gift list, and removes Festio branding.',
          'Event Passes are tiered by guest cap — choose the tier that fits your event size. You can upgrade to a higher tier if your guest list grows.',
          'Message credits: buy in the Event Pass area. Credits are shared across all your events. By default, one SMS costs about 2 credits, one WhatsApp message about 1.5 credits — email doesn\'t use credits. Exact rates are shown when you preview a send.',
          'Low on credits mid-event? Buy a top-up instantly from Event Setup — credits are available immediately.',
          'Trial: new accounts can request a free trial from the Event Setup banner — send the request and we\'ll comp your first event.',
        ],
        tip: 'Check your credit balance before any bulk send. The Event Pass area shows your current balance and usage history.',
      },
      {
        id: 'org-api', icon: '🔌', title: 'Public API & developer access',
        img: '/media/help2-org-api.png',
        intro: 'Read or write your event\'s guest data from your own tools using the Public API.',
        steps: [
          'Org Settings → API Keys panel → Create new key.',
          'Name the key and choose a scope: Read-only, or Read-write (requires an active API subscription — the option is disabled without one).',
          'Your new key is shown once in a banner — copy it immediately, it can\'t be viewed again. Revoke a key any time from the list.',
          'API docs has the full reference; API Explorer is an in-app console for trying real calls against your own data before writing code.',
          'The API covers guests, tables, table groups, and Experience — the same data you manage in the app.',
        ],
        warn: 'Read-write access is gated behind an active API subscription — a read-only key works immediately, but write calls fail until you subscribe.',
      },
      {
        id: 'org-calendars', icon: '📆', title: 'Event Calendars: curated listing pages',
        img: '/media/help2-org-calendars.png',
        intro: 'A public page listing several of your events together — for a season, a venue, or a recurring series.',
        steps: [
          'Org Settings → Calendars panel → New calendar: set a title, description, and visibility (Public or Private).',
          'Manage on a calendar → Add event to curate which events appear, reorder them with the Up/Down buttons, and upload a logo.',
          'Copy public link to share the page directly, or Copy embed code to add it as an iframe on your own website.',
          'Each calendar tracks total views, and each listed event tracks its own click-through count.',
          'For a Private calendar, build a Contact List (paste contacts or upload a CSV/Excel file) and tick it under Private-link audiences, then Send private links to email everyone on that list their own calendar link.',
        ],
        warn: '"Send private links" only works on a Private calendar — a Public calendar with an audience selected will show an error when you try to send, rather than disabling the button ahead of time.',
      },
      {
        id: 'org-export', icon: '⬇️', title: 'Export & post-event',
        steps: [
          'Guests tab: review RSVP status, check-in time, seat, order choices, and any custom question answers.',
          'Seating tab: use the seating chart and table assignment list for on-site reference.',
          'Orders tab: review per-table item totals for your caterer or fulfilment team.',
          'Deliveries tab: review guest names, addresses, and items for fulfilment.',
          'Results: check-in timeline and area analytics are visible on-screen — take screenshots or use your browser print function.',
          'After the event, set it to Ended so check-in and RSVP submissions close. The event stays in your event list with its full data for reporting — nothing is deleted or hidden.',
        ],
      },
      {
        id: 'org-troubleshoot', icon: '🔧', title: 'Troubleshooting',
        intro: 'Common issues and how to fix them.',
        steps: [
          'Guests not receiving invites: check their email/phone in the Guests tab — look for the ⚠️ flag on rows with invalid phone numbers. For email, ask guests to check spam/junk. Resend from the guest row or Invites & RSVP.',
          'Import shows warnings (amber badge): click the badge to see which rows failed — most common causes are missing country codes on phone numbers, unknown ticket type names, or rows exceeding your plan guest limit.',
          'Google Sheets sync is red: the share link has expired or the sheet\'s sharing setting changed. Re-share the sheet as "Anyone with the link can view" and paste the new link.',
          'QR not scanning: ensure the event is set to Active. Check the scanner device has camera permission in browser settings. Try good lighting — the QR needs to be fully visible in frame.',
          'Guest getting "Already admitted": the QR was used at a previous gate. Check their check-in log (Guest profile) to see where they were scanned. This is normal — just admit them manually if it was an error.',
          'Area showing Denied: the guest\'s ticket type or tags don\'t permit entry to that area. Check the guest\'s ticket type in their profile and compare with the rules in Entry areas.',
          'Credits ran out during a bulk send: buy a top-up from Event Setup and resume the send from Invites & RSVP using a no-reply reminder.',
          'Can\'t see Seating / Venue Access tabs: these features must be turned on in Guest Communication → Features &amp; messaging, and require an Event Pass.',
          'Staff can\'t see the event in Check-in: they must be added in Team tab AND assigned to this specific event.',
          'RSVP deadline passed but guests are still submitting: the deadline blocks new RSVPs from the public invite page. You can still add or approve guests manually from Event Setup.',
          'Guests don\'t see "Join Festio Live" on their ticket page: confirm Festio Live is turned on (Guest Communication → Features &amp; messaging) and that an activity is actually set to Live, not Draft. Share the festio.events/live/join code as a fallback.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STAFF / SCANNER
  // ─────────────────────────────────────────────────────────────────────────
  staff: {
    label: 'Staff / Check-in',
    icon: '📷',
    blurb: 'Check guests in at the door. No app needed — runs in your phone browser.',
    topics: [
      {
        id: 'staff-join', icon: '🔑', title: 'Get set up before the event',
        steps: [
          'Your organiser adds you by email in the event\'s Team tab. Make sure they use your exact sign-in email.',
          'Sign in at festio.events with that email. Your account links to their organisation automatically.',
          'You\'ll see the events you\'ve been assigned to in the Check-in screen.',
          'Open Check-in on the device you\'ll use on the day and confirm you can see the event. Do this at least the day before.',
          'Grant camera permission: the browser will ask the first time you start the camera. Allow it — if you accidentally denied, go to your browser Settings → Site permissions → Camera and re-enable it.',
          'Check your internet connection. Opening Check-in once while online automatically caches the guest list on your device — if the connection drops later, scanning keeps working and syncs automatically once you\'re back online (you\'ll see a blue result instead of green while offline).',
        ],
        tip: 'Do a test scan the day before. Your organiser can add themselves as a guest — scan their QR to confirm the green admitted screen appears.',
      },
      {
        id: 'staff-scan', icon: '📷', title: 'Check guests in',
        img: '/media/help2-checkin.png',
        steps: [
          'Open Check-in on your phone or tablet. No app download needed.',
          'Select your event from the list.',
          'If the event uses Gates, select your gate (e.g. "Main Entrance"). This sets your zone and direction automatically.',
          'If using manual area entry: pick the area you\'re standing at and direction (Entry / Exit).',
          'Tap Start camera. Point the camera at the guest\'s QR code — it reads instantly without pressing any button.',
          'Hold the phone steady and ensure good lighting. The QR code must be fully within the camera frame.',
          'After each scan the screen resets automatically, ready for the next guest within a second.',
          'If a guest\'s phone screen is dim: ask them to increase brightness. A printed QR works just as well.',
        ],
        tip: 'If a QR is not working, ask the organiser to look up the guest in Guests and confirm their invitation or ticket code.',
      },
      {
        id: 'staff-results', icon: 'ℹ️', title: 'Understanding scan results',
        steps: [
          '✅ Green — "Welcome, [Name]!" — admitted successfully. Guest may proceed.',
          '⚠️ Yellow — "Already admitted" — this QR was scanned before. Ask when and where — it\'s usually fine if they\'re moving between zones.',
          '🔴 Red — "Access denied" — the guest\'s ticket type or tags don\'t permit this area, or the area is at capacity. Politely direct them to the correct entrance.',
          '🔴 Red — "Event not active" — the organiser hasn\'t set the event to Active yet. Ask them to do so in Event Setup → Start here.',
          '🔴 Red — "Needs Event Pass" — the organiser\'s account is on the free tier. This shouldn\'t happen at a real event — contact your organiser.',
          '❓ "Guest not found" — the QR is from a different event or is corrupted. Direct the guest to the organiser desk.',
          '🔵 Blue — "Checked in on this device" — the internet dropped, so the scan was accepted from the guest list already cached on your phone and queued to sync. Keep scanning normally; it uploads automatically once you\'re back online.',
          'For any denied result, do not override — direct the guest to the organiser\'s desk for resolution.',
        ],
      },
      {
        id: 'staff-zones', icon: '🚪', title: 'Zone scanning & gates',
        img: '/media/help2-checkin.png',
        steps: [
          'If the event has Entry areas enabled, Check-in shows an Area/Gate picker before you start.',
          'Gate mode (recommended): select your named gate once (e.g. "VIP Lounge Door"). The zone and direction are pre-configured — every scan automatically enforces the rules for that gate.',
          'Manual mode: pick a zone (e.g. Main Hall) and direction (Entry or Exit) yourself. Change it if you move to a different gate.',
          'The scan result shows "Allowed" (green) or "Denied" (red) plus the live occupancy count for that zone.',
          'Denied reasons shown on screen: "Wrong zone for ticket type", "Tag not permitted here", "Zone at capacity".',
          'A guest\'s first allowed Entry scan anywhere in the venue also counts as their event check-in — no separate check-in scan needed.',
          'Exit scans are optional — they help track who is still inside the venue.',
          'Live occupancy is shown below the scan result — you can see if a zone is filling up.',
        ],
        tip: 'If you\'re covering multiple gates, stay on Gate mode and switch your gate selection each time you move — don\'t try to use Manual mode for a fast-moving door.',
      },
      {
        id: 'staff-experience', icon: '🧭', title: 'Running an Experience workflow',
        intro: 'If the organizer has set up an Experience workflow, check-in is just the first step — you may also mark consent, seating, souvenirs, or session attendance.',
        steps: [
          'Each guest\'s Festio Pass page shows their current step in the workflow — what\'s done and what\'s next.',
          'Consent (if required) can only be signed after the guest is checked in — if a guest asks to sign before arrival, let them know it opens right after their first scan.',
          'Mark a step complete from the guest\'s pass page as they go through it — souvenir pickup, badge issued, seated, etc.',
          'If a step won\'t complete, check whether it depends on an earlier step (like consent) that hasn\'t happened yet — direct the guest through steps in order.',
        ],
      },
      {
        id: 'staff-tips', icon: '💡', title: 'Tips for a smooth check-in',
        steps: [
          'Keep your phone charged — bring a power bank for all-day events.',
          'Use a phone holder or lanyard so your hands are free to manage the queue.',
          'Brief other staff before opening: agree on what to do if a QR is denied or a guest can\'t find their ticket.',
          'For large events with queues: open multiple check-in stations and assign a separate area/gate to each — parallel scanning dramatically reduces wait times.',
          'If the camera freezes: close and reopen the Check-in tab. You don\'t lose any data.',
          'Guests who can\'t find their QR: ask them to check their confirmation email/SMS/WhatsApp. If still missing, direct them to the organiser desk for lookup in Guests.',
          'Manual lookup: ask the organiser to use Guests or the ticket code lookup to confirm the guest before entry.',
          'Noisy lighting (direct sunlight, flashing lights): tilt the guest\'s screen slightly towards you or ask them to cup their hand over it to reduce glare.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // GUEST
  // ─────────────────────────────────────────────────────────────────────────
  guest: {
    label: 'Guest',
    icon: '🎉',
    blurb: 'You received an invite — here\'s everything you need from RSVP to arrival.',
    topics: [
      {
        id: 'guest-open', icon: '🔗', title: 'Open your invite',
        img: '/media/help2-guest-invite.png',
        steps: [
          'Tap the link in your email, SMS, or WhatsApp message. It opens in your phone browser — no app download needed.',
          'If the link asks you to "Open with…" — choose your browser (Chrome, Safari, etc.).',
          'If the link has expired: RSVP deadlines are set by the host. Contact them directly to be added manually.',
          'If you can\'t find your invite: check your spam/junk folder (email) or your WhatsApp message requests.',
        ],
      },
      {
        id: 'guest-rsvp', icon: '📝', title: 'RSVP',
        steps: [
          'Fill in your name and any questions the host has set (dietary preference, item choice, t-shirt size, etc.).',
          'Click Confirm to say yes, or "Can\'t make it" to decline.',
          'On a personal (closed) invite link, you can return and change your answer until the RSVP deadline.',
          'If the host requires approval, you\'ll see "RSVP submitted — awaiting confirmation" until they approve. You\'ll get a notification when you\'re confirmed.',
          'If you\'re bringing a plus-one: look for the partner/plus-one option on your ticket page after confirming — link your partner\'s name so you\'re seated together.',
        ],
        tip: 'RSVP as soon as possible — some events have capacity limits and close registrations once full.',
      },
      {
        id: 'guest-ticket', icon: '🎟️', title: 'Your ticket & QR code',
        steps: [
          'Once your RSVP is confirmed, you\'ll receive a confirmation email (and/or SMS/WhatsApp) with your personal QR code.',
          'On the day: show this QR at the entrance — staff will scan it with their phone camera. It\'s instant.',
          'You can also find your ticket by reopening the invite link — your QR is always there.',
          'The QR is personal and unique to you. Don\'t share it with anyone else.',
          'If the event uses zones (e.g. VIP areas): your ticket type controls which areas you can enter. If you\'re denied at a gate, speak to the organiser.',
          'Printed QR works just as well as showing it on your phone screen.',
        ],
        tip: 'Screenshot your QR code and save it to your phone\'s camera roll before the event, in case you lose internet access on the day.',
      },
      {
        id: 'guest-tickets', icon: '💳', title: 'Buying a paid ticket',
        steps: [
          'Some events are ticketed rather than free RSVP — you\'ll see prices and ticket types (General Admission, VIP, etc.) on the event page.',
          'Pick a ticket type and quantity, then pay by card through the event\'s checkout.',
          'After payment, you receive the same personal QR pass a free RSVP guest gets — show it at the door the same way.',
          'A refund (if the organizer issues one) cancels your pass along with the payment.',
        ],
      },
      {
        id: 'guest-experience', icon: '🧭', title: 'Your guest journey (consent, souvenirs, sessions)',
        steps: [
          'Some events track a step-by-step journey on your Festio Pass page — check-in, consent, seating, souvenirs, or session attendance, depending on what the host set up.',
          'Consent forms (if required) become available on your pass page after you\'ve checked in, not before.',
          'Your current step and what\'s next are shown right on your pass — staff can also see and update it as you go through each step.',
        ],
      },
      {
        id: 'guest-meal', icon: '🍽️', title: 'Order choices & seating',
        steps: [
          'If the host set up orders, you\'ll see a "Pick your items" section on your ticket/RSVP page.',
          'Pick your choice before the deadline shown — after the deadline, changes may not be accepted.',
          'Your item choices are sent to the event team and linked to your table automatically — you don\'t need to tell anyone on the day.',
          'Seating: the host assigns tables. Your table and seat number (if assigned) appear on your ticket page before the event.',
          'If you\'re attending as a couple/group: link your plus-one on your ticket page so the host can seat you together.',
        ],
      },
      {
        id: 'guest-address', icon: '📦', title: 'Providing your address (aso-ebi / gifts)',
        steps: [
          'Some events collect shipping addresses for aso-ebi fabric, welcome bags, or post-event gift delivery.',
          'If address collection is on, you\'ll see an address form on the RSVP or ticket page.',
          'Enter your full delivery address including postcode/zip code and country.',
          'You can update your address by returning to your invite link before the shipping cutoff date set by the host.',
          'If you missed the address deadline: contact the host directly.',
        ],
      },
      {
        id: 'guest-registry', icon: '🎁', title: 'Gift registry',
        steps: [
          'If the host shares a registry link, open it to browse their gift wishlist and cash contribution funds.',
          'Click "I\'ll bring this" on any item to claim it — others will see it\'s taken so nobody buys duplicates.',
          'For cash funds: the host\'s payment details or instructions are shown — you transfer directly, not through Festio.',
          'You can unclaim an item if your plans change — just return to the registry link and untick.',
          'No account or login required to view or claim items.',
        ],
      },
      {
        id: 'guest-live', icon: '🎤', title: 'Join a live quiz, poll or survey',
        steps: [
          'If the host is running Festio Live, a "Join Festio Live" button appears on your invite/ticket page whenever an activity is live — tap it to join instantly, no extra sign-in.',
          'No personal invite link (e.g. you\'re at a talk or keynote)? Go to festio.events/live/join on your phone and enter the 6-character join code shown on screen, or scan the QR code if one is displayed.',
          'Answer from your own phone — quizzes may have a timer and award points; polls, ratings, and surveys just record your response.',
          'For quizzes: your score and rank appear on the leaderboard once the host reveals results.',
          'For word clouds and open-text questions: your answer may need host approval before it appears on the shared screen — this is normal if nothing shows up immediately.',
          'You can only submit once per question unless the host has turned on "Allow changes" for that activity.',
        ],
        tip: 'If "Join Festio Live" isn\'t showing on your ticket page, the host hasn\'t started an activity yet — check back once the session begins, or ask the host for the join code.',
      },
      {
        id: 'guest-faq', icon: '❓', title: 'Guest FAQ',
        intro: 'Quick answers to common questions.',
        steps: [
          'I didn\'t get a confirmation email — check your spam folder first. If it\'s not there, return to your invite link and confirm your email address is correct. Contact the host to resend.',
          'I can\'t find the invite link — check your email, SMS, and WhatsApp message requests. Ask the host to resend it.',
          'The link says "RSVP closed" — the deadline or capacity limit has passed. Contact the host directly.',
          'My QR won\'t scan — ask the staff member to direct you to the organiser desk. The organiser can confirm your invite or ticket code.',
          'I want to bring an extra guest — contact the host. They control plus-one allowances.',
          'I need to cancel — return to your invite link and change your RSVP to "Can\'t make it". Contact the host if you\'re past the deadline.',
          'I have a dietary requirement — if there\'s no option on the RSVP form, add a note in the "special requests" field or contact the host directly.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OPERATOR
  // ─────────────────────────────────────────────────────────────────────────
  operator: {
    label: 'Operator',
    icon: '🛠️',
    blurb: 'Platform management — organisations, billing, pricing, and support tooling.',
    topics: [
      {
        id: 'op-open', icon: '🛠️', title: 'Open the Console',
        steps: [
          'Operators see a Console link in the main navigation when signed in.',
          'Direct URL: /console.',
          'The Console is only visible to accounts with the platform superadmin role.',
          'If you need operator access added, contact another existing operator.',
        ],
      },
      {
        id: 'op-grant', icon: '🎁', title: 'Comp events & add credits',
        steps: [
          'Console → Overview: lists every organisation with its events.',
          'Click an event → Comp Event: select a tier to grant it free (Starter, Standard, Pro, Scale, etc.). The organiser immediately gets all features of that tier.',
          'Click an organisation → Add Credits: enter a credit amount to top up their message credit balance at no charge.',
          'Comps and credit grants are logged with the operator name and timestamp.',
          'To remove a comp: click the event and select Remove Comp — the event reverts to its paid status.',
        ],
      },
      {
        id: 'op-trials', icon: '🎟️', title: 'Trial requests',
        steps: [
          'Console → Trial requests: lists customers who submitted a free trial request from Event Setup.',
          'Each request shows: contact name, email, phone, event name, use case description, and submission date.',
          'Approve: select a tier to comp their event onto (and optionally add message credits). Click Approve — the customer is emailed the decision automatically.',
          'Decline: click Decline — the customer is emailed that their request wasn\'t approved.',
          'If the requester has no event yet: approve with no event selected — the comp is held and applied to their next event automatically.',
          'Approved trials do not auto-expire — remove the comp manually from the event if needed after the trial period.',
        ],
      },
      {
        id: 'op-accounts', icon: '🧑‍💼', title: 'Manage accounts',
        steps: [
          'Console → Accounts: every organisation with its members, roles, and event count.',
          'Suspend an org: all members lose access to its events immediately. Reversible — reactivate any time. No data is lost.',
          'Delete an org: permanently removes the org and all its events and data. Requires typing the org name to confirm. Irreversible.',
          'Per member actions: change role (Owner / Admin / Staff), remove from org, suspend user (blocks all sign-in), or delete user (removes account + disables sign-in).',
          'Guard rails: you cannot suspend or delete yourself, the last operator account, or the default org.',
          'View a member\'s full sign-in history and last active date from their profile.',
        ],
        warn: 'Org deletion is permanent and cannot be undone. Always confirm with the customer before deleting.',
      },
      {
        id: 'op-pricing', icon: '💲', title: 'Edit pricing & plans',
        steps: [
          'Console → Pricing: view and edit all event pass tiers and message credit packs.',
          'Edit a tier: change the display name, price (USD and/or NGN), guest cap, active/inactive status.',
          'Add a new tier: useful for custom enterprise plans.',
          'Message credit packs: edit the credits-per-pack, price, and active status.',
          'Changes apply immediately to the public pricing page and checkout.',
          'Deactivating a tier hides it from checkout but doesn\'t affect events already on that tier.',
          'Global add-on promotion (in the same Pricing tab): opens every add-on free on all current and future paid events for a set period — "Open paid-event add-ons for 6 months" or "End promotion now". Free events still can\'t use add-ons, and any explicit per-org or per-event override still takes precedence.',
        ],
      },
      {
        id: 'op-addons', icon: '🧩', title: 'Grant or deny add-ons per organization',
        steps: [
          'Console → Add-on Access: search for the organization or event you need.',
          'Manage add-ons on an organization opens an override editor per add-on — Grant, Deny, or return it to normal billing rules.',
          'Organization-level grants apply to all of that org\'s current and future events, not just one.',
          'Use this for one-off exceptions (a customer needs Planner early, or should never get a specific add-on) rather than the blanket Console → Pricing promotion, which affects everyone.',
        ],
      },
      {
        id: 'op-platform', icon: '⚙️', title: 'Platform-wide settings',
        steps: [
          'Console → Support chat: toggle whether the in-app support chat widget is visible to organizers platform-wide.',
          'Console → Usage: aggregated usage stats across all organizations.',
          'Console → QA checklist: view results submitted from the staging QA checklist tools.',
          'Console → Referrals and Affiliate stores: manage referral tracking and affiliate storefronts.',
          'Console → Org Plans: view and adjust organization-level subscription plans (distinct from per-event Event Pass tiers).',
        ],
      },
      {
        id: 'op-operators', icon: '👤', title: 'Manage operators',
        steps: [
          'Console → Operators: lists all accounts with platform superadmin access.',
          'Add an operator: enter their email address. They must already have a Festio account.',
          'Revoke an operator: removes their superadmin access. You cannot revoke your own access.',
          'Keep the operator list minimal — operator accounts have unrestricted access to all organisations and data.',
        ],
        warn: 'Only grant operator access to trusted team members. Operators can view, modify, and delete any organisation\'s data.',
      },
    ],
  },
}
