export const CONTENT = {
  // ─────────────────────────────────────────────────────────────────────────
  // ORGANIZER
  // ─────────────────────────────────────────────────────────────────────────
  organizer: {
    label: 'Organizer',
    icon: '🗂️',
    blurb: 'Create an event, invite guests, and run check-in on the day.',
    topics: [
      {
        id: 'org-start', icon: '🚀', title: 'Get started',
        intro: 'Everything begins with a free account — no credit card required.',
        steps: [
          'Go to events.vsgs.io and click Get Started.',
          'Sign in with Google (fastest) or create an account with any email address.',
          'You land straight in the Admin panel with your own organisation already created.',
          'Click New Event to create your first event — you can run a free event with up to 25 guests right away.',
          'Want to try all paid features before buying? Look for the "Request free trial" banner in the Admin panel and send a request — we\'ll set you up.',
        ],
        tip: 'The free tier includes email invites, RSVP tracking, and up to 25 guests. Upgrade to an Event Pass to unlock SMS/WhatsApp, QR check-in, seating, venue zones, and more.',
      },
      {
        id: 'org-create', icon: '📅', title: 'Create your event',
        img: '/media/admin-overview.png',
        intro: 'Each event is a self-contained workspace with its own guests, invites, settings, and day-of tools.',
        steps: [
          'In Admin, click New Event.',
          'Enter the event name, an optional host/organiser display name, date & time, and a base URL slug (used in invite links).',
          'Save. Open the event — navigation is a left sidebar grouped into Setup (Overview, Guests, Invites), Venue & access, Add-ons (Seating, Menu, Logistics, Registry), and Team & settings. On a phone the sidebar becomes a dropdown.',
          'Under Team &amp; settings → Features, toggle on the features you need: Seating, Menu, Venue Access, Logistics, Gift Registry. Each requires an Event Pass — once enabled it appears in the sidebar.',
          'The event you pick is remembered across Dashboard, Scanner and Kitchen — you only choose it once. The current event shows as a chip in the top bar.',
          'Set the event to Draft while preparing, Active on the day to enable scanning, and Closed afterwards.',
          'You can create multiple events — each is independent with its own guest list and settings.',
        ],
        tip: 'The base URL slug is used in all invite and RSVP links (e.g. events.vsgs.io/invite/your-slug). Keep it short and memorable.',
      },
      {
        id: 'org-guests', icon: '👥', title: 'Add your guest list',
        img: '/media/admin-guests.png',
        intro: 'Import from a spreadsheet, sync from Google Sheets, or add guests one at a time.',
        steps: [
          'Go to Overview → Download template. It contains exactly the columns your event uses — with an Excel dropdown for ticket types — so nothing is missed.',
          'Fill in the template and click Upload CSV/Excel. Your own spreadsheet works too: column names match in any case or spacing (First Name = first_name = FIRST NAME).',
          'Email is optional — guests without an email can still receive SMS/WhatsApp invites and be checked in by QR.',
          'For live sync: paste a Google Sheets or OneDrive share link. Import once, or tick "auto-sync" to refresh every minute while the event is Active.',
          'Watch the sync status badge: green = ok, amber = imported with warnings (unknown ticket types, rows over plan limit, invalid phone numbers), red = sync failed (check the share link is still public).',
          'Re-importing never creates duplicates — it fills in missing phone numbers, ticket types, addresses, and tags for existing guests.',
          'For Venue Access events: add a "tags" column (e.g. "VIP; Press") — unknown tags are created automatically and control which zones each guest may enter.',
          'The free tier allows up to 25 guests total. An Event Pass raises this limit based on the tier you choose.',
          'To add a single guest: Guests tab → Add guest, fill in the form.',
        ],
        tip: 'Column matching is flexible — "First Name", "first_name", "firstname" all map to the same field. The only required column is a name (first + last, or full name).',
        warn: 'Phone numbers must include the country code (e.g. +2348012345678 for Nigeria, +14155551234 for US) for SMS/WhatsApp delivery to work.',
      },
      {
        id: 'org-rsvp', icon: '✉️', title: 'Set up your RSVP & invite page',
        img: '/media/admin-invite.png',
        intro: 'The invite page is what guests see when they open their link. Make it yours.',
        steps: [
          'Go to the Invite tab → "Invite Page & RSVP".',
          'Choose Open mode (one shared link, anyone can RSVP) or Closed mode (unique private link per guest — only that guest can use it).',
          'Optionally: set an RSVP deadline, enable approval required (you manually approve each RSVP), add custom questions (dietary, t-shirt size, table preference, etc.), upload a cover image, and write a welcome message.',
          'Click "Preview invite page" to see exactly what guests will see before you send anything.',
          'For Seating events: add a custom question like "Meal choice" and link it to the menu — guests pick their meal on the invite page.',
          'For Logistics events: turn on address collection — guests enter their shipping address when they RSVP.',
          'Set a maximum RSVP count to close registrations once the venue is full.',
        ],
        tip: 'Closed mode (unique per-guest links) prevents forwarding and double-booking. Use it for formal events or when you need a precise headcount.',
      },
      {
        id: 'org-send', icon: '📤', title: 'Send invitations',
        img: '/media/send-invites.png',
        intro: 'Reach guests on the channel they actually check — WhatsApp, SMS, or email.',
        steps: [
          'Open mode: copy the shared event link and share it yourself (WhatsApp group, email, social). Or use Manual invite — search a specific guest and send them a personal link.',
          'Closed mode: Invite tab → Bulk RSVP invites. Choose "Send to not-yet-invited" (first send), "Remind no-reply" (follow-up), or "Resend to all".',
          'Pick your channels: Email (always free), SMS (uses message credits), WhatsApp (uses message credits).',
          'Each guest receives their personal ticket QR automatically by email when they RSVP as Attending.',
          'For guests without email: if you have their phone number, their QR ticket is delivered via SMS or WhatsApp instead.',
          'Message credits are pre-purchased in the Admin panel — top up as needed. Check your balance before a bulk send.',
          'Schedule reminders: set an automated reminder 24 hours and/or 1 hour before the event — guests who haven\'t checked in yet receive a nudge.',
        ],
        tip: 'Run a small test send to yourself first (add your own phone/email as a test guest) to confirm message formatting and delivery before sending to all guests.',
        warn: 'WhatsApp and SMS sends consume message credits. A bulk send to 300 guests uses 300 credits. Check your balance first — the send will stop mid-way if you run out.',
      },
      {
        id: 'org-track', icon: '✅', title: 'Track RSVPs & approvals',
        img: '/media/admin-guests.png',
        steps: [
          'The Guests tab shows every guest with their current status: Attending, Declined, Pending (submitted, awaiting your approval), or No reply.',
          'Each row also shows whether the guest has been checked in on the day.',
          'If "Approval required" is on: click a guest to approve or reject their RSVP. Use "Approve all" to confirm everyone at once.',
          'Filter the list by status, ticket type, or tag to find specific groups quickly.',
          'Export the full guest list to CSV at any time from the Guests tab menu.',
          'Click any guest to see their full details: RSVP answers, contact info, ticket type, tags, seat assignment, meal choice, and check-in history.',
          'Update a guest\'s status, ticket type, or seat assignment manually if needed.',
        ],
        tip: 'Use the filter + bulk-select to approve, email, or change ticket types for a whole group at once.',
      },
      {
        id: 'org-broadcast', icon: '📣', title: 'Broadcast an update',
        img: '/media/broadcast.png',
        intro: 'Push a message to any subset of guests at any time — before, during, or after the event.',
        steps: [
          'Invite tab → Broadcast Message.',
          'Write your message (plain text — keep it short for SMS/WhatsApp).',
          'Choose your target: All guests, RSVP Attending, RSVP Declined, No reply, Checked-in, or Not checked-in.',
          'Pick your channel(s): email, SMS, WhatsApp — or all three.',
          'Preview the estimated credit cost before sending.',
          'Hit Send. Delivery happens in the background — you can leave the page.',
          'Useful examples: venue change, schedule update, parking instructions, "doors open in 30 minutes", post-event thank-you.',
        ],
        warn: 'Broadcast sends are immediate and cannot be recalled once sent. Double-check your message and target group before confirming.',
      },
      {
        id: 'org-seating', icon: '🍽️', title: 'Seating & menu',
        badge: 'Paid',
        intro: 'Assign tables, let guests pick meals, and give your kitchen a live order view.',
        steps: [
          'Team &amp; settings → Features → turn on Seating and/or Menu (requires an Event Pass).',
          'Seating tab → Create tables: set a name (Table 1, Head Table, VIP Round…), capacity, and optionally a section label.',
          'Use Auto-assign to fill tables automatically by RSVP order, or drag guests to specific seats manually.',
          'Reserve seats: mark seats as unavailable (blocked for a VIP arrival, accessibility needs, etc.).',
          'Partner pairing: guests can link their plus-one on their ticket page — auto-assign keeps them together.',
          'Menu tab → Add categories (Starters, Mains, Desserts) and items with optional descriptions.',
          'Guests see the menu on their ticket page and pick their meal before your deadline.',
          'Kitchen view: a read-only view your catering team can open on a tablet — shows each table\'s order totals and individual choices, updating live.',
          'Export the full seating plan and meal orders to PDF or CSV for your caterer.',
        ],
        tip: 'Set a meal selection deadline in the Menu settings so guests can\'t change their order at the last minute.',
      },
      {
        id: 'org-access', icon: '🎫', title: 'Venue Access: zones & ticket types',
        badge: 'Paid',
        imgs: ['/media/admin-access.png', '/media/admin-access-analytics.png'],
        intro: 'Control which guests can enter which areas of your venue — enforced automatically at every scan.',
        steps: [
          'Team &amp; settings → Features → turn on Access (requires an Event Pass).',
          'Access tab → Zones: create the areas in your venue — Main Hall, VIP Lounge, Backstage, Kitchen, etc. Set an optional capacity limit and direction mode (Entry only / Exit only / Both).',
          'Ticket types: create tiers — GA (General Admission), VIP, Press, Staff, Speaker. For each type, choose which zones they may enter. Leave empty to allow all zones.',
          'Assign ticket types: set a guest\'s type one by one from their profile, or include a ticket_type column in your imported spreadsheet.',
          'Tags: create classifiers (VIP, 21+, Speaker, Media…) for finer control — a guest can have multiple tags. Set zone rules to require specific tags.',
          'Gates: create a named gate for each scanner position (e.g. "Main Entrance", "VIP Gate", "Backstage Door"). Pin it to a zone + direction. Staff select their gate once — access rules are enforced automatically.',
          'Analytics: live occupancy per zone, peak arrival times, room-to-room flow, and each guest\'s full journey through the venue.',
        ],
        tip: 'Gates are the easiest setup for multi-zone events: staff just select "I\'m at Main Entrance" and scan — the zone and direction are automatic for every scan after that.',
      },
      {
        id: 'org-logistics', icon: '📦', title: 'Logistics: ship merch, aso-ebi & gifts',
        badge: 'Paid',
        img: '/media/admin-logistics.png',
        steps: [
          'Team &amp; settings → Features → turn on Logistics.',
          'Logistics tab → New Shipment. Name it (e.g. "Aso-ebi fabric", "Welcome bag", "Gift delivery").',
          'Add items to the shipment — each with a name, optional size/variant, and quantity.',
          'Guest addresses: collected automatically if you turned on address collection in RSVP settings, or import them via the ship_address columns in your guest list.',
          'Packing list: a shareable read-only page your fulfilment vendor opens — they see guest names, addresses, and items without needing a login.',
          'Mark items as packed/shipped per guest — or bulk-mark a whole shipment.',
          'Use multiple shipments for different waves (pre-event aso-ebi vs post-event gift delivery).',
        ],
        tip: 'Add the shipping address fields to your RSVP custom questions so guests fill them in when they confirm — no separate data collection needed.',
      },
      {
        id: 'org-registry', icon: '🎁', title: 'Gift registry',
        badge: 'Paid',
        img: '/media/admin-registry.png',
        steps: [
          'Team &amp; settings → Features → turn on Registry.',
          'Registry tab → Add items: paste a store link and the platform auto-fills the title, image, and price. Or add cash funds (e.g. "Honeymoon fund", "New home contribution").',
          'Write a welcome message shown at the top of the registry page.',
          'Share the public registry link directly — paste it in WhatsApp, add it to your invite page, or print it on physical invites.',
          'Guests mark what they\'ll bring (or how much they\'re contributing) so nobody doubles up.',
          'No money moves through EventQR — guests purchase or give directly to you. The registry is purely a wish-list coordination tool.',
          'You can see who has claimed each item from the Registry tab.',
        ],
      },
      {
        id: 'org-team', icon: '🧑‍🤝‍🧑', title: 'Add your team',
        img: '/media/admin-team.png',
        steps: [
          'Team tab → "Add a teammate" → enter their email address and choose a role.',
          'Admin role: can manage the event (edit settings, guests, seating, etc.). Full access except billing.',
          'Staff role: can only scan guests and view the scanner/dashboard for their assigned events. Cannot edit anything.',
          'Kitchen role: read-only access to the kitchen/catering view for their assigned events. No scanning.',
          'The teammate signs in with that exact email — their account links to your organisation automatically.',
          'Assign the teammate to specific events from the Team tab — they only see events they\'ve been assigned to.',
          'Remove a teammate from the Team tab at any time. Their account continues to exist but loses access to your events.',
        ],
        tip: 'Add all scanning staff before the event day. Have them test-login and open the Scanner page the day before so there are no surprises on the day.',
      },
      {
        id: 'org-checkin', icon: '🎟️', title: 'Check-in day',
        steps: [
          'The day before: set the event to Active in Overview. This enables the scanner to process guests.',
          'Ensure all scanning staff are added to the Team tab and assigned to this event.',
          'Share the scanner URL with staff: events.vsgs.io/scanner. No app install — it runs in any mobile browser.',
          'Staff open Scanner → choose their gate (or set zone + direction manually) → tap Start Camera.',
          'Each guest shows their QR code (from email, SMS, WhatsApp, or their ticket page). Staff point the camera — admission is instant.',
          'Green = admitted. Yellow = already admitted (duplicate scan). Red = denied (wrong zone, at capacity, or needs an Event Pass).',
          'For walk-in guests not on the list: Guests tab → Add guest → assign them a ticket type → their QR appears immediately for scanning.',
          'The Dashboard updates in real time — open it on a separate screen to monitor check-ins live.',
          'After the event: set to Closed to disable further scanning. Download the full check-in report from the Guests tab.',
        ],
        tip: 'Test scanning works on at least one device before guests arrive. Scan your own guest entry to confirm the green admitted screen appears.',
        warn: 'Scanning requires the event to be set to Active. If guests are getting "Event not active" errors, check the event status in Overview.',
      },
      {
        id: 'org-dashboard', icon: '📊', title: 'Live dashboard',
        steps: [
          'Open Dashboard from the nav during or after your event.',
          'Top row: total RSVP\'d, total checked in, currently in venue (if using Venue Access).',
          'RSVP breakdown doughnut: Attending vs Declined vs No reply.',
          'Check-in timeline: arrivals per hour throughout the event — shows when your peak entry times were.',
          'Zone occupancy (Venue Access): live count and capacity bar per zone. Turns red when near capacity.',
          'Catering summary: totals by meal choice across all tables.',
          'Per-table report: each table\'s check-in count, meal orders, and which guests are seated there.',
          'The dashboard auto-refreshes every few seconds — no need to reload manually.',
          'Staff and Kitchen roles can view the Dashboard for their assigned events (read-only).',
        ],
        tip: 'Put the Dashboard on a tablet at the organiser desk so you can monitor arrivals in real time without leaving your post.',
      },
      {
        id: 'org-upgrade', icon: '💳', title: 'Event Pass & message credits',
        img: '/media/pricing.png',
        steps: [
          'Free tier: email invites, up to 25 guests, EventQR branding on invite pages, no paid features.',
          'Event Pass: buy per event in the Invite tab → Event Pass. Unlocks SMS/WhatsApp invites, more guests, QR check-in, seating & menu, venue access zones, logistics, gift registry, and removes EventQR branding.',
          'Event Passes are tiered by guest cap — choose the tier that fits your event size. You can upgrade to a higher tier if your guest list grows.',
          'Message credits: buy in Admin → Message Credits. Credits are shared across all your events. 1 credit = 1 SMS or 1 WhatsApp message to 1 guest.',
          'Low on credits mid-event? Buy a top-up instantly from Admin — credits are available immediately.',
          'Trial: new accounts can request a free trial from the Admin panel banner — send the request and we\'ll comp your first event.',
        ],
        tip: 'Check your credit balance before any bulk send. Admin → Message Credits shows your current balance and usage history.',
      },
      {
        id: 'org-export', icon: '⬇️', title: 'Export & post-event',
        steps: [
          'Guests tab → Export CSV: full guest list with RSVP status, check-in time, seat, meal choice, and any custom question answers.',
          'Seating tab → Export PDF: printable seating chart and table assignment list for on-site reference.',
          'Menu/Catering tab → Export CSV: per-table meal order summary for your caterer.',
          'Logistics tab → Export packing list: CSV of guest names, addresses, and items for fulfilment.',
          'Dashboard: check-in timeline and zone analytics are visible on-screen — take screenshots or use your browser print function.',
          'After the event, set it to Closed and archive it. Archived events remain accessible for reporting but don\'t appear in your active list.',
        ],
      },
      {
        id: 'org-troubleshoot', icon: '🔧', title: 'Troubleshooting',
        intro: 'Common issues and how to fix them.',
        steps: [
          'Guests not receiving invites: check their email/phone in the Guests tab — look for the ⚠️ flag on rows with invalid phone numbers. For email, ask guests to check spam/junk. Resend from the Guests tab (individual) or Bulk RSVP (all).',
          'Import shows warnings (amber badge): click the badge to see which rows failed — most common causes are missing country codes on phone numbers, unknown ticket type names, or rows exceeding your plan guest limit.',
          'Google Sheets sync is red: the share link has expired or the sheet\'s sharing setting changed. Re-share the sheet as "Anyone with the link can view" and paste the new link.',
          'QR not scanning: ensure the event is set to Active. Check the scanner device has camera permission in browser settings. Try good lighting — the QR needs to be fully visible in frame.',
          'Guest getting "Already admitted": the QR was used at a previous gate. Check their check-in log (Guest profile) to see where they were scanned. This is normal — just admit them manually if it was an error.',
          'Zone showing Denied: the guest\'s ticket type or tags don\'t permit entry to that zone. Check the guest\'s ticket type in their profile and compare with the zone rules in the Access tab.',
          'Credits ran out during a bulk send: buy a top-up in Admin → Message Credits and resume the send from Bulk RSVP invites using "Remind no-reply" (this targets only guests who haven\'t received the invite yet).',
          'Can\'t see Seating / Access tabs: these features must be turned on in Team &amp; settings → Features, and require an Event Pass.',
          'Staff can\'t see the event in Scanner: they must be added in Team tab AND assigned to this specific event.',
          'RSVP deadline passed but guests are still submitting: the deadline blocks new RSVPs from the public invite page. You can still add or approve guests manually from the Admin.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STAFF / SCANNER
  // ─────────────────────────────────────────────────────────────────────────
  staff: {
    label: 'Staff / Scanner',
    icon: '📷',
    blurb: 'Check guests in at the door. No app needed — runs in your phone browser.',
    topics: [
      {
        id: 'staff-join', icon: '🔑', title: 'Get set up before the event',
        steps: [
          'Your organiser adds you by email in the event\'s Team tab. Make sure they use your exact sign-in email.',
          'Sign in at events.vsgs.io with that email. Your account links to their organisation automatically.',
          'You\'ll see the events you\'ve been assigned to in the Scanner screen.',
          'Open Scanner on the device you\'ll use on the day and confirm you can see the event. Do this at least the day before.',
          'Grant camera permission: the browser will ask the first time you open the scanner. Allow it — if you accidentally denied, go to your browser Settings → Site permissions → Camera and re-enable it.',
          'Check your internet connection. The scanner works best with a reliable connection; for low-signal venues ask your organiser about offline mode.',
        ],
        tip: 'Do a test scan the day before. Your organiser can add themselves as a guest — scan their QR to confirm the green admitted screen appears.',
      },
      {
        id: 'staff-scan', icon: '📷', title: 'Check guests in',
        img: '/media/scanner.png',
        steps: [
          'Open events.vsgs.io/scanner on your phone or tablet. No app download needed.',
          'Select your event from the list.',
          'If the event uses Gates, select your gate (e.g. "Main Entrance"). This sets your zone and direction automatically.',
          'If using manual zone entry: pick the zone you\'re standing at and direction (Entry / Exit).',
          'Tap Start Camera. Point the camera at the guest\'s QR code — it reads instantly without pressing any button.',
          'Hold the phone steady and ensure good lighting. The QR code must be fully within the camera frame.',
          'After each scan the screen resets automatically, ready for the next guest within a second.',
          'If a guest\'s phone screen is dim: ask them to increase brightness. A printed QR works just as well.',
        ],
        tip: 'You can also search for a guest by name if their QR isn\'t working — tap the Search tab and type their name to manually check them in.',
      },
      {
        id: 'staff-results', icon: 'ℹ️', title: 'Understanding scan results',
        steps: [
          '✅ Green — "Welcome, [Name]!" — admitted successfully. Guest may proceed.',
          '⚠️ Yellow — "Already admitted" — this QR was scanned before. Ask when and where — it\'s usually fine if they\'re moving between zones.',
          '🔴 Red — "Access denied" — the guest\'s ticket type or tags don\'t permit this zone, or the zone is at capacity. Politely direct them to the correct entrance.',
          '🔴 Red — "Event not active" — the organiser hasn\'t set the event to Active yet. Ask them to do so in Admin → Overview.',
          '🔴 Red — "Needs Event Pass" — the organiser\'s account is on the free tier. This shouldn\'t happen at a real event — contact your organiser.',
          '❓ "Guest not found" — the QR is from a different event or is corrupted. Search by name instead.',
          'For any denied result, do not override — direct the guest to the organiser\'s desk for resolution.',
        ],
      },
      {
        id: 'staff-zones', icon: '🚪', title: 'Zone scanning & gates',
        img: '/media/scanner-zone.png',
        steps: [
          'If the event has Venue Access enabled, the Scanner shows a Zone/Gate picker before you start.',
          'Gate mode (recommended): select your named gate once (e.g. "VIP Lounge Door"). The zone and direction are pre-configured — every scan automatically enforces the rules for that gate.',
          'Manual mode: pick a zone (e.g. Main Hall) and direction (Entry or Exit) yourself. Change it if you move to a different gate.',
          'The scan result shows "Allowed" (green) or "Denied" (red) plus the live occupancy count for that zone.',
          'Denied reasons shown on screen: "Wrong zone for ticket type", "Tag not permitted here", "Zone at capacity".',
          'A guest\'s first allowed Entry scan anywhere in the venue also counts as their event check-in — no separate check-in scan needed.',
          'Exit scans are optional — they help track who is still inside the venue.',
          'Live occupancy is shown below the scan result — you can see if a zone is filling up.',
        ],
        tip: 'If you\'re covering multiple gates, stay on Gate mode and switch your gate selection each time you move — don\'t try to use Manual mode for a fast-moving door.',
      },
      {
        id: 'staff-tips', icon: '💡', title: 'Tips for a smooth check-in',
        steps: [
          'Keep your phone charged — bring a power bank for all-day events.',
          'Use a phone holder or lanyard so your hands are free to manage the queue.',
          'Brief other staff before opening: agree on what to do if a QR is denied or a guest can\'t find their ticket.',
          'For large events with queues: open multiple scanner stations and assign a separate zone/gate to each — parallel scanning dramatically reduces wait times.',
          'If the camera freezes: close and reopen the Scanner tab. You don\'t lose any data.',
          'Guests who can\'t find their QR: ask them to check their confirmation email/SMS/WhatsApp. If still missing, search by name in the Search tab and check in manually.',
          'Manual check-in: tap Search, type the guest\'s name, tap their row, and hit Check In.',
          'Noisy lighting (direct sunlight, flashing lights): tilt the guest\'s screen slightly towards you or ask them to cup their hand over it to reduce glare.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // GUEST
  // ─────────────────────────────────────────────────────────────────────────
  guest: {
    label: 'Guest',
    icon: '🎉',
    blurb: 'You received an invite — here\'s everything you need from RSVP to arrival.',
    topics: [
      {
        id: 'guest-open', icon: '🔗', title: 'Open your invite',
        img: '/media/invite-page.png',
        steps: [
          'Tap the link in your email, SMS, or WhatsApp message. It opens in your phone browser — no app download needed.',
          'If the link asks you to "Open with…" — choose your browser (Chrome, Safari, etc.).',
          'If the link has expired: RSVP deadlines are set by the host. Contact them directly to be added manually.',
          'If you can\'t find your invite: check your spam/junk folder (email) or your WhatsApp message requests.',
        ],
      },
      {
        id: 'guest-rsvp', icon: '📝', title: 'RSVP',
        steps: [
          'Fill in your name and any questions the host has set (dietary preference, meal choice, t-shirt size, etc.).',
          'Click Confirm to say yes, or "Can\'t make it" to decline.',
          'On a personal (closed) invite link, you can return and change your answer until the RSVP deadline.',
          'If the host requires approval, you\'ll see "RSVP submitted — awaiting confirmation" until they approve. You\'ll get a notification when you\'re confirmed.',
          'If you\'re bringing a plus-one: look for the partner/plus-one option on your ticket page after confirming — link your partner\'s name so you\'re seated together.',
        ],
        tip: 'RSVP as soon as possible — some events have capacity limits and close registrations once full.',
      },
      {
        id: 'guest-ticket', icon: '🎟️', title: 'Your ticket & QR code',
        steps: [
          'Once your RSVP is confirmed, you\'ll receive a confirmation email (and/or SMS/WhatsApp) with your personal QR code.',
          'On the day: show this QR at the entrance — staff will scan it with their phone camera. It\'s instant.',
          'You can also find your ticket by reopening the invite link — your QR is always there.',
          'The QR is personal and unique to you. Don\'t share it with anyone else.',
          'If the event uses zones (e.g. VIP areas): your ticket type controls which areas you can enter. If you\'re denied at a gate, speak to the organiser.',
          'Printed QR works just as well as showing it on your phone screen.',
        ],
        tip: 'Screenshot your QR code and save it to your phone\'s camera roll before the event, in case you lose internet access on the day.',
      },
      {
        id: 'guest-meal', icon: '🍽️', title: 'Meal choice & seating',
        steps: [
          'If the host set a menu, you\'ll see a "Select your meal" section on your ticket/RSVP page.',
          'Pick your choice before the deadline shown — after the deadline, changes may not be accepted.',
          'Your meal choice is sent to the kitchen and linked to your table automatically — you don\'t need to tell anyone on the day.',
          'Seating: the host assigns tables. Your table and seat number (if assigned) appear on your ticket page before the event.',
          'If you\'re attending as a couple/group: link your plus-one on your ticket page so the host can seat you together.',
        ],
      },
      {
        id: 'guest-address', icon: '📦', title: 'Providing your address (aso-ebi / gifts)',
        steps: [
          'Some events collect shipping addresses for aso-ebi fabric, welcome bags, or post-event gift delivery.',
          'If address collection is on, you\'ll see an address form on the RSVP or ticket page.',
          'Enter your full delivery address including postcode/zip code and country.',
          'You can update your address by returning to your invite link before the shipping cutoff date set by the host.',
          'If you missed the address deadline: contact the host directly.',
        ],
      },
      {
        id: 'guest-registry', icon: '🎁', title: 'Gift registry',
        steps: [
          'If the host shares a registry link, open it to browse their gift wishlist and cash contribution funds.',
          'Click "I\'ll bring this" on any item to claim it — others will see it\'s taken so nobody buys duplicates.',
          'For cash funds: the host\'s payment details or instructions are shown — you transfer directly, not through EventQR.',
          'You can unclaim an item if your plans change — just return to the registry link and untick.',
          'No account or login required to view or claim items.',
        ],
      },
      {
        id: 'guest-faq', icon: '❓', title: 'Guest FAQ',
        intro: 'Quick answers to common questions.',
        steps: [
          'I didn\'t get a confirmation email — check your spam folder first. If it\'s not there, return to your invite link and confirm your email address is correct. Contact the host to resend.',
          'I can\'t find the invite link — check your email, SMS, and WhatsApp message requests. Ask the host to resend it.',
          'The link says "RSVP closed" — the deadline or capacity limit has passed. Contact the host directly.',
          'My QR won\'t scan — ask the staff member to search your name manually in their scanner. They can check you in without the QR.',
          'I want to bring an extra guest — contact the host. They control plus-one allowances.',
          'I need to cancel — return to your invite link and change your RSVP to "Can\'t make it". Contact the host if you\'re past the deadline.',
          'I have a dietary requirement — if there\'s no option on the RSVP form, add a note in the "special requests" field or contact the host directly.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OPERATOR
  // ─────────────────────────────────────────────────────────────────────────
  operator: {
    label: 'Operator',
    icon: '🛠️',
    blurb: 'Platform management — organisations, billing, pricing, and support tooling.',
    topics: [
      {
        id: 'op-open', icon: '🛠️', title: 'Open the Console',
        steps: [
          'Operators see a Console link in the main navigation when signed in.',
          'Direct URL: /console.',
          'The Console is only visible to accounts with the platform superadmin role.',
          'If you need operator access added, contact another existing operator.',
        ],
      },
      {
        id: 'op-grant', icon: '🎁', title: 'Comp events & add credits',
        steps: [
          'Console → Overview: lists every organisation with its events.',
          'Click an event → Comp Event: select a tier to grant it free (Starter, Pro, Grand, etc.). The organiser immediately gets all features of that tier.',
          'Click an organisation → Add Credits: enter a credit amount to top up their message credit balance at no charge.',
          'Comps and credit grants are logged with the operator name and timestamp.',
          'To remove a comp: click the event and select Remove Comp — the event reverts to its paid status.',
        ],
      },
      {
        id: 'op-trials', icon: '🎟️', title: 'Trial requests',
        steps: [
          'Console → Trial requests: lists customers who submitted a free trial request from the Admin panel.',
          'Each request shows: contact name, email, phone, event name, use case description, and submission date.',
          'Approve: select a tier to comp their event onto (and optionally add message credits). Click Approve — the customer is emailed the decision automatically.',
          'Decline: click Decline — the customer is emailed that their request wasn\'t approved.',
          'If the requester has no event yet: approve with no event selected — the comp is held and applied to their next event automatically.',
          'Approved trials do not auto-expire — remove the comp manually from the event if needed after the trial period.',
        ],
      },
      {
        id: 'op-accounts', icon: '🧑‍💼', title: 'Manage accounts',
        steps: [
          'Console → Accounts: every organisation with its members, roles, and event count.',
          'Suspend an org: all members lose access to its events immediately. Reversible — reactivate any time. No data is lost.',
          'Delete an org: permanently removes the org and all its events and data. Requires typing the org name to confirm. Irreversible.',
          'Per member actions: change role (Owner / Admin / Staff), remove from org, suspend user (blocks all sign-in), or delete user (removes account + disables sign-in).',
          'Guard rails: you cannot suspend or delete yourself, the last operator account, or the default org.',
          'View a member\'s full sign-in history and last active date from their profile.',
        ],
        warn: 'Org deletion is permanent and cannot be undone. Always confirm with the customer before deleting.',
      },
      {
        id: 'op-pricing', icon: '💲', title: 'Edit pricing & plans',
        steps: [
          'Console → Pricing: view and edit all event pass tiers and message credit packs.',
          'Edit a tier: change the display name, price (USD and/or NGN), guest cap, active/inactive status.',
          'Add a new tier: useful for custom enterprise plans.',
          'Message credit packs: edit the credits-per-pack, price, and active status.',
          'Changes apply immediately to the public pricing page and checkout.',
          'Deactivating a tier hides it from checkout but doesn\'t affect events already on that tier.',
        ],
      },
      {
        id: 'op-operators', icon: '👤', title: 'Manage operators',
        steps: [
          'Console → Operators: lists all accounts with platform superadmin access.',
          'Add an operator: enter their email address. They must already have a EventQR account.',
          'Revoke an operator: removes their superadmin access. You cannot revoke your own access.',
          'Keep the operator list minimal — operator accounts have unrestricted access to all organisations and data.',
        ],
        warn: 'Only grant operator access to trusted team members. Operators can view, modify, and delete any organisation\'s data.',
      },
    ],
  },
}
