export const CONTENT = {
  // ─────────────────────────────────────────────────────────────────────────
  // ORGANIZER
  // ─────────────────────────────────────────────────────────────────────────
  organizer: {
    label: 'Organizer',
    icon: '🗂️',
    blurb: 'Create an event, invite guests, and run check-in on the day.',
    topics: [
      {
        id: 'org-start', icon: '🚀', title: 'Get started',
        intro: 'Everything begins with a free account — no credit card required.',
        steps: [
          'Go to events.vsgs.io and click Get Started.',
          'Sign in with Google (fastest) or create an account with any email address.',
          'You land straight in Event Setup with your own organisation already created.',
          'Click New Event to create your first event — you can run a free event with up to 25 guests right away.',
          'Want to try all paid features before buying? Use the trial request banner in Event Setup and send a request — we\'ll set you up.',
        ],
        tip: 'The free tier includes email invites, RSVP tracking, and up to 25 guests. Upgrade to an Event Pass to unlock SMS/WhatsApp, QR check-in, seating, entry areas, and more.',
      },
      {
        id: 'org-create', icon: '📅', title: 'Create your event',
        img: '/media/help-event-setup.png',
        intro: 'Each event is a self-contained workspace with its own guests, invites, settings, and day-of tools.',
        steps: [
          'In Event Setup, click New Event.',
          'Enter the event name, an optional host/organiser display name, date & time, and a base URL slug (used in invite links).',
          'Save. Open the event — navigation is grouped into Setup (Start here, Guests, Invites & RSVP), Entry areas/rules, Add-ons (Seating, Orders, Deliveries, Gift list), and Team & settings. On a phone the sidebar becomes a dropdown.',
          'Under Team &amp; settings → Features, toggle on the features you need: Seating, Orders, Entry rules, Deliveries, and Gift list. Each requires an Event Pass — once enabled it appears in the sidebar.',
          'The event you pick is remembered across Results, Check-in, and Orders — you only choose it once. The current event shows as a chip in the top bar.',
          'Set the event to Draft while preparing, Active on the day to enable check-in, and Ended afterwards.',
          'You can create multiple events — each is independent with its own guest list and settings.',
        ],
        tip: 'The base URL slug is used in all invite and RSVP links (e.g. events.vsgs.io/invite/your-slug). Keep it short and memorable.',
      },
      {
        id: 'org-guests', icon: '👥', title: 'Add your guest list',
        img: '/media/help-guests.png',
        intro: 'Import from a spreadsheet, sync from Google Sheets, or add guests one at a time.',
        steps: [
          'Go to Start here → Download template. It contains exactly the columns your event uses — with an Excel dropdown for ticket types — so nothing is missed.',
          'Fill in the template and click Upload guest file. Your own spreadsheet works too: column names match in any case or spacing (First Name = first_name = FIRST NAME).',
          'Email is optional — guests without an email can still receive SMS/WhatsApp invites and be checked in by QR.',
          'For live sync: paste a Google Sheets or OneDrive share link. Import once, or set a sync interval while the event is Active.',
          'Watch the sync status badge: green = ok, amber = imported with warnings (unknown ticket types, rows over plan limit, invalid phone numbers), red = sync failed (check the share link is still public).',
          'Re-importing never creates duplicates — it fills in missing phone numbers, ticket types, addresses, and tags for existing guests.',
          'For Entry rules events: add a "tags" column (e.g. "VIP; Press") — unknown tags are created automatically and control which areas each guest may enter.',
          'The free tier allows up to 25 guests total. An Event Pass raises this limit based on the tier you choose.',
          'To add a single guest: Guests tab → Add guest, fill in the form.',
        ],
        tip: 'Column matching is flexible — "First Name", "first_name", "firstname" all map to the same field. The only required column is a name (first + last, or full name).',
        warn: 'Phone numbers must include the country code (e.g. +2348012345678 for Nigeria, +14155551234 for US) for SMS/WhatsApp delivery to work.',
      },
      {
        id: 'org-rsvp', icon: '✉️', title: 'Set up your RSVP & invite page',
        img: '/media/help-invites-rsvp.png',
        intro: 'The invite page is what guests see when they open their link. Make it yours.',
        steps: [
          'Go to Invites & RSVP → Invitation page & RSVP.',
          'Choose Anyone with event link (one shared link, anyone can RSVP) or Only guests with personal invite link (unique private link per guest — only that guest can use it).',
          'Optionally: set an RSVP deadline, enable approval required (you manually approve each RSVP), add custom questions (dietary, t-shirt size, table preference, etc.), upload a cover image, and write a welcome message.',
          'Click "Preview invite page" to see exactly what guests will see before you send anything.',
          'For Orders events: add choices for meals, drinks, gifts, or any other item guests should select on the invite page.',
          'For Deliveries events: turn on address collection — guests enter their shipping address when they RSVP.',
          'Set a maximum RSVP count to close registrations once the venue is full.',
        ],
        tip: 'Personal invite links prevent forwarding and double-booking. Use them for formal events or when you need a precise headcount.',
      },
      {
        id: 'org-send', icon: '📤', title: 'Send invitations',
        img: '/media/help-invites-rsvp.png',
        intro: 'Reach guests on the channel they actually check — WhatsApp, SMS, or email.',
        steps: [
          'Shared link: copy the event link and share it yourself (WhatsApp group, email, social). Or use Manual invite — search a specific guest and send them a personal link.',
          'Personal links: use Invites & RSVP to send to guests who have not been invited yet, remind no-replies, or resend links.',
          'Pick your channels: Email (always free), SMS (uses message credits), WhatsApp (uses message credits).',
          'Each guest receives their personal ticket QR automatically by email when they RSVP as Attending.',
          'For guests without email: if you have their phone number, their QR ticket is delivered via SMS or WhatsApp instead.',
          'Message credits are pre-purchased from the Event Pass area — top up as needed. Check your balance before a bulk send.',
          'For reminders, use Broadcast Message to nudge guests before the event or during arrival.',
        ],
        tip: 'Run a small test send to yourself first (add your own phone/email as a test guest) to confirm message formatting and delivery before sending to all guests.',
        warn: 'WhatsApp and SMS sends consume message credits. A bulk send to 300 guests uses 300 credits. Check your balance first — the send will stop mid-way if you run out.',
      },
      {
        id: 'org-track', icon: '✅', title: 'Track RSVPs & approvals',
        img: '/media/help-guests.png',
        steps: [
          'The Guests tab shows every guest with their current status: Attending, Declined, Pending (submitted, awaiting your approval), or No reply.',
          'Each row also shows whether the guest has been checked in on the day.',
          'If "Approval required" is on: click a guest to approve or reject their RSVP. Use "Approve all" to confirm everyone at once.',
          'Use search, selection, and the status columns to find specific groups quickly.',
          'Use the guest tools to review or download event data when you need an offline list.',
          'Click any guest to see their details: RSVP answers, contact info, ticket type, tags, seat assignment, order choices, and check-in history.',
          'Update a guest\'s status, ticket type, or seat assignment manually if needed.',
        ],
        tip: 'Use the filter + bulk-select to approve, email, or change ticket types for a whole group at once.',
      },
      {
        id: 'org-broadcast', icon: '📣', title: 'Broadcast an update',
        img: '/media/help-invites-rsvp.png',
        intro: 'Push a message to any subset of guests at any time — before, during, or after the event.',
        steps: [
          'Invites & RSVP → Broadcast Message.',
          'Write your message (plain text — keep it short for SMS/WhatsApp).',
          'Choose your target: All guests, RSVP Attending, RSVP Declined, No reply, Checked-in, or Not checked-in.',
          'Pick your channel(s): email, SMS, WhatsApp — or all three.',
          'Preview the estimated credit cost before sending.',
          'Hit Send. Delivery happens in the background — you can leave the page.',
          'Useful examples: venue change, schedule update, parking instructions, "doors open in 30 minutes", post-event thank-you.',
        ],
        warn: 'Broadcast sends are immediate and cannot be recalled once sent. Double-check your message and target group before confirming.',
      },
      {
        id: 'org-seating', icon: '🍽️', title: 'Seating & orders',
        badge: 'Paid',
        imgs: ['/media/help-orders.png', '/media/help-orders-view.png'],
        intro: 'Assign tables, let guests pick meals, drinks, gifts, or other items, and give staff a live Orders view.',
        steps: [
          'Team &amp; settings → Features → turn on Seating and/or Orders (requires an Event Pass).',
          'Seating tab → Create tables: set a name (Table 1, Head Table, VIP Round…), capacity, and optionally a section label.',
          'Use Auto-assign to fill tables automatically by RSVP order, or drag guests to specific seats manually.',
          'Reserve a seat for a guest: click an empty seat on the chart and pick the guest — they\'re placed in exactly that seat (handy for a head table or a specific arrangement).',
          'Partner pairing: guests can link their plus-one on their ticket page — auto-assign keeps them together.',
          'Table groups: group tables into a section (e.g. "Family side", "Friends side", "Men", "Women"). A guest assigned to a group can only be seated at that group\'s tables — auto-assign, manual seating, and check-in all honour it.',
          'No double-booking: each seat holds exactly one guest and a table can\'t be filled past its capacity — the seating chart and a guest\'s profile both block it. If a guest\'s table or group is already full at check-in, they show as Denied so you can re-seat them rather than being seated twice.',
          'Orders tab → Add categories (Meals, Drinks, Gifts, Merchandise) and items with optional descriptions.',
          'Guests see the available items on their ticket page and pick before your deadline.',
          'Orders view: a read-only view your staff or caterer can open on a tablet — shows each table\'s order totals and individual choices, updating live.',
          'Use the seating plan and order totals as the working list for your caterer or fulfilment team.',
        ],
        tip: 'Use the RSVP deadline as your cutoff when you do not want guests changing item choices at the last minute.',
      },
      {
        id: 'org-access', icon: '🎫', title: 'Entry areas & ticket rules',
        badge: 'Paid',
        img: '/media/help-entry-areas.png',
        intro: 'Control which guests can enter which areas of your venue — enforced automatically at every scan.',
        steps: [
          'Team &amp; settings → Features → turn on Entry rules (requires an Event Pass).',
          'Entry areas tab → Areas: create the areas in your venue — Main Hall, VIP Lounge, Backstage, Green Room, etc. Set an optional capacity limit and direction mode (Entry only / Exit only / Both).',
          'Ticket types: create tiers — GA (General Admission), VIP, Press, Staff, Speaker. For each type, choose which zones they may enter. Leave empty to allow all zones.',
          'Ticket capacity (optional): give a ticket type a limit (e.g. 50 VIP) and you won\'t be able to assign more than that many guests to it — handy for capped tiers.',
          'Assign ticket types: set a guest\'s type one by one from their profile, or include a ticket_type column in your imported spreadsheet.',
          'Tags: create classifiers (VIP, 21+, Speaker, Media…) for finer control — a guest can have multiple tags. Set zone rules to require specific tags.',
          'Gates: create a named gate for each scanner position (e.g. "Main Entrance", "VIP Gate", "Backstage Door"). Pin it to a zone + direction. Staff select their gate once — access rules are enforced automatically.',
          'Analytics: live occupancy per zone, peak arrival times, room-to-room flow, and each guest\'s full journey through the venue.',
        ],
        tip: 'Gates are the easiest setup for multi-zone events: staff just select "I\'m at Main Entrance" and scan — the zone and direction are automatic for every scan after that. Note: Entry rules can\'t be combined with Section scanning on the same event — use Entry rules for access control + occupancy, Section scanning to seat walk-ins by entrance.',
      },
      {
        id: 'org-sections', icon: '🚪', title: 'Section scanning (multi-entrance seating)',
        badge: 'Paid',
        intro: 'For events where each entrance serves a part of the room — e.g. men\'s / women\'s sides, or marquee A / marquee B — route walk-ins and ungrouped check-ins to the right section automatically, per staff member.',
        steps: [
          'Set up your sections as table groups first (Seating tab) — a section is simply a table group.',
          'Guests tab → Walk-in guests → turn on Section scanning. It needs at least one table group, and can\'t be used together with Entry rules.',
          'Team &amp; settings → Event team: assign each staff member their section. A staffer pinned to one section is routed there automatically; give them two or more and they pick their section on the scanner.',
          'At the door: walk-ins and ungrouped manual check-ins handled by that staffer are seated in their section. Admins/owners aren\'t pinned — they pick a section on the scanner.',
          'A guest who already belongs to a different group keeps their own group — a section never overrides a guest\'s explicit assignment.',
        ],
        tip: 'While Section scanning is on, each staffer\'s assigned section replaces the single "auto-assign walk-ins to table group" setting.',
      },
      {
        id: 'org-logistics', icon: '📦', title: 'Deliveries: ship merch, aso-ebi & gifts',
        badge: 'Paid',
        img: '/media/help-deliveries.png',
        steps: [
          'Team &amp; settings → Features → turn on Deliveries.',
          'Deliveries tab → New Shipment. Name it (e.g. "Aso-ebi fabric", "Welcome bag", "Gift delivery").',
          'Add items to the shipment — each with a name, optional size/variant, and quantity.',
          'Guest addresses: collected automatically if you turned on address collection in RSVP settings, or import them via the ship_address columns in your guest list.',
          'Packing list: a shareable read-only page your fulfilment vendor opens — they see guest names, addresses, and items without needing a login.',
          'Mark items as packed/shipped per guest — or bulk-mark a whole shipment.',
          'Use multiple shipments for different waves (pre-event aso-ebi vs post-event gift delivery).',
        ],
        tip: 'Add the shipping address fields to your RSVP custom questions so guests fill them in when they confirm — no separate data collection needed.',
      },
      {
        id: 'org-registry', icon: '🎁', title: 'Gift list',
        badge: 'Paid',
        img: '/media/help-gift-list.png',
        steps: [
          'Team &amp; settings → Features → turn on Gift list.',
          'Gift list tab → Add items: paste a store link and the platform auto-fills the title, image, and price. Or add cash funds (e.g. "Honeymoon fund", "New home contribution").',
          'Write a welcome message shown at the top of the gift list page.',
          'Share the public gift list link directly — paste it in WhatsApp, add it to your invite page, or print it on physical invites.',
          'Guests mark what they\'ll bring (or how much they\'re contributing) so nobody doubles up.',
          'No money moves through EventQR — guests purchase or give directly to you. The gift list is purely a wish-list coordination tool.',
          'You can see who has claimed each item from the Gift list tab.',
        ],
      },
      {
        id: 'org-team', icon: '🧑‍🤝‍🧑', title: 'Add your team',
        img: '/media/help-team.png',
        steps: [
          'Team tab → "Add a teammate" → enter their email address and choose a role.',
          'Roles: Owner and Admin can manage the event (settings, guests, seating, etc.); Staff can only check guests in on events they\'re assigned to.',
          'Per-staffer permissions (for assigned Staff): toggle Seats (let them reassign seats), Orders (open the live Orders view), and Dashboard (view Results) for each person — all off by default.',
          'For Section scanning events: assign each staffer their section (table group) from the same Team panel, so walk-ins they handle route to the right part of the room.',
          'The teammate signs in with that exact email — their account links to your organisation automatically.',
          'Assign the teammate to specific events from the Team tab — they only see events they\'ve been assigned to.',
          'Remove a teammate from the Team tab at any time. Their account continues to exist but loses access to your events.',
        ],
        tip: 'Add all check-in staff before the event day. Have them test-login and open the Check-in page the day before so there are no surprises on the day.',
      },
      {
        id: 'org-checkin', icon: '🎟️', title: 'Check-in day',
        img: '/media/help-check-in.png',
        steps: [
          'The day before: set the event to Active in Start here. This enables Check-in to process guests.',
          'Ensure all scanning staff are added to the Team tab and assigned to this event.',
          'Share the Check-in page with staff. No app install — it runs in any mobile browser.',
          'Staff open Check-in → choose their gate (or set area + direction manually) → tap Start camera.',
          'Each guest shows their QR code (from email, SMS, WhatsApp, or their ticket page). Staff point the camera — admission is instant.',
          'Green = admitted. Yellow = already admitted (duplicate scan — same guest, same seat, never seated twice). Red = denied (wrong zone, at capacity, table/section full, or needs an Event Pass).',
          'For walk-in guests not on the list: Guests tab → Add guest → assign them a ticket type → their QR appears immediately for scanning.',
          'Results updates in real time — open it on a separate screen to monitor check-ins live.',
          'After the event: set to Ended to disable further check-ins. Review the full check-in record from the Guests tab.',
        ],
        tip: 'Test scanning works on at least one device before guests arrive. Scan your own guest entry to confirm the green admitted screen appears.',
        warn: 'Check-in requires the event to be set to Active. If guests are getting "Event not active" errors, check the event status in Start here.',
      },
      {
        id: 'org-dashboard', icon: '📊', title: 'Results',
        img: '/media/help-results.png',
        steps: [
          'Open Results from the nav during or after your event.',
          'Top row: total RSVP\'d, total checked in, currently in venue (if using Entry areas).',
          'RSVP breakdown doughnut: Attending vs Declined vs No reply.',
          'Check-in timeline: arrivals per hour throughout the event — shows when your peak entry times were.',
          'Area occupancy (Entry areas): live count and capacity bar per area. Turns red when near capacity.',
          'Orders summary: totals by selected item across all tables.',
          'Per-table report: each table\'s check-in count, order choices, and which guests are seated there.',
          'Results auto-refreshes every few seconds — no need to reload manually.',
          'Staff and Orders access roles can view Results for their assigned events when permitted (read-only).',
        ],
        tip: 'Put Results on a tablet at the organiser desk so you can monitor arrivals in real time without leaving your post.',
      },
      {
        id: 'org-upgrade', icon: '💳', title: 'Event Pass & message credits',
        img: '/media/help-event-pass.png',
        steps: [
          'Free tier: email invites, up to 25 guests, EventQR branding on invite pages, no paid features.',
          'Event Pass: buy per event in Invites & RSVP → Event Pass. Unlocks SMS/WhatsApp invites, more guests, QR check-in, seating & orders, entry areas, deliveries, gift list, and removes EventQR branding.',
          'Event Passes are tiered by guest cap — choose the tier that fits your event size. You can upgrade to a higher tier if your guest list grows.',
          'Message credits: buy in the Event Pass area. Credits are shared across all your events. 1 credit = 1 SMS or 1 WhatsApp message to 1 guest.',
          'Low on credits mid-event? Buy a top-up instantly from Event Setup — credits are available immediately.',
          'Trial: new accounts can request a free trial from the Event Setup banner — send the request and we\'ll comp your first event.',
        ],
        tip: 'Check your credit balance before any bulk send. The Event Pass area shows your current balance and usage history.',
      },
      {
        id: 'org-export', icon: '⬇️', title: 'Export & post-event',
        steps: [
          'Guests tab: review RSVP status, check-in time, seat, order choices, and any custom question answers.',
          'Seating tab: use the seating chart and table assignment list for on-site reference.',
          'Orders tab: review per-table item totals for your caterer or fulfilment team.',
          'Deliveries tab: review guest names, addresses, and items for fulfilment.',
          'Results: check-in timeline and area analytics are visible on-screen — take screenshots or use your browser print function.',
          'After the event, set it to Ended and archive it. Archived events remain accessible for reporting but don\'t appear in your active list.',
        ],
      },
      {
        id: 'org-troubleshoot', icon: '🔧', title: 'Troubleshooting',
        intro: 'Common issues and how to fix them.',
        steps: [
          'Guests not receiving invites: check their email/phone in the Guests tab — look for the ⚠️ flag on rows with invalid phone numbers. For email, ask guests to check spam/junk. Resend from the guest row or Invites & RSVP.',
          'Import shows warnings (amber badge): click the badge to see which rows failed — most common causes are missing country codes on phone numbers, unknown ticket type names, or rows exceeding your plan guest limit.',
          'Google Sheets sync is red: the share link has expired or the sheet\'s sharing setting changed. Re-share the sheet as "Anyone with the link can view" and paste the new link.',
          'QR not scanning: ensure the event is set to Active. Check the scanner device has camera permission in browser settings. Try good lighting — the QR needs to be fully visible in frame.',
          'Guest getting "Already admitted": the QR was used at a previous gate. Check their check-in log (Guest profile) to see where they were scanned. This is normal — just admit them manually if it was an error.',
          'Area showing Denied: the guest\'s ticket type or tags don\'t permit entry to that area. Check the guest\'s ticket type in their profile and compare with the rules in Entry areas.',
          'Check-in shows "No seat available" or "table group full": the guest\'s table or table group is at capacity. Free a seat, raise the table capacity, or move them to another group in Seating — then scan again.',
          'Can\'t enable Section scanning (or Entry rules): the two can\'t run on the same event. Turn the other one off first. Section scanning also needs at least one table group to exist.',
          '"Sold out" when assigning a ticket type: that ticket type has hit its capacity limit. Raise the limit on the ticket type, or pick a different one.',
          'Credits ran out during a bulk send: buy a top-up from Event Setup and resume the send from Invites & RSVP using a no-reply reminder.',
          'Can\'t see Seating / Entry areas tabs: these features must be turned on in Team &amp; settings → Features, and require an Event Pass.',
          'Staff can\'t see the event in Check-in: they must be added in Team tab AND assigned to this specific event.',
          'RSVP deadline passed but guests are still submitting: the deadline blocks new RSVPs from the public invite page. You can still add or approve guests manually from Event Setup.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // STAFF / SCANNER
  // ─────────────────────────────────────────────────────────────────────────
  staff: {
    label: 'Staff / Check-in',
    icon: '📷',
    blurb: 'Check guests in at the door. No app needed — runs in your phone browser.',
    topics: [
      {
        id: 'staff-join', icon: '🔑', title: 'Get set up before the event',
        steps: [
          'Your organiser adds you by email in the event\'s Team tab. Make sure they use your exact sign-in email.',
          'Sign in at events.vsgs.io with that email. Your account links to their organisation automatically.',
          'You\'ll see the events you\'ve been assigned to in the Check-in screen.',
          'Open Check-in on the device you\'ll use on the day and confirm you can see the event. Do this at least the day before.',
          'Grant camera permission: the browser will ask the first time you start the camera. Allow it — if you accidentally denied, go to your browser Settings → Site permissions → Camera and re-enable it.',
          'Check your internet connection. Check-in works best with a reliable connection; for low-signal venues ask your organiser about offline mode.',
        ],
        tip: 'Do a test scan the day before. Your organiser can add themselves as a guest — scan their QR to confirm the green admitted screen appears.',
      },
      {
        id: 'staff-scan', icon: '📷', title: 'Check guests in',
        img: '/media/help-check-in.png',
        steps: [
          'Open Check-in on your phone or tablet. No app download needed.',
          'Select your event from the list.',
          'If the event uses Gates, select your gate (e.g. "Main Entrance"). This sets your zone and direction automatically.',
          'If using manual area entry: pick the area you\'re standing at and direction (Entry / Exit).',
          'If the event uses Section scanning: your section is usually set for you. If you cover more than one, pick your section once — walk-ins and manual check-ins you handle are seated there.',
          'Tap Start camera. Point the camera at the guest\'s QR code — it reads instantly without pressing any button.',
          'Hold the phone steady and ensure good lighting. The QR code must be fully within the camera frame.',
          'After each scan the screen resets automatically, ready for the next guest within a second.',
          'If a guest\'s phone screen is dim: ask them to increase brightness. A printed QR works just as well.',
        ],
        tip: 'If a QR is not working, ask the organiser to look up the guest in Guests and confirm their invitation or ticket code.',
      },
      {
        id: 'staff-results', icon: 'ℹ️', title: 'Understanding scan results',
        steps: [
          '✅ Green — "Welcome, [Name]!" — admitted successfully. Guest may proceed.',
          '⚠️ Yellow — "Already admitted" — this QR was scanned before. Ask when and where — it\'s usually fine if they\'re moving between zones.',
          '🔴 Red — "Access denied" — the guest\'s ticket type or tags don\'t permit this area, or the area is at capacity. Politely direct them to the correct entrance.',
          '🔴 Red — "No seat available / table full" — the guest\'s assigned table or section is full. Don\'t re-scan; send them to the organiser\'s desk to be re-seated (the system won\'t double-book a seat).',
          '🔴 Red — "Event not active" — the organiser hasn\'t set the event to Active yet. Ask them to do so in Event Setup → Start here.',
          '🔴 Red — "Needs Event Pass" — the organiser\'s account is on the free tier. This shouldn\'t happen at a real event — contact your organiser.',
          '❓ "Guest not found" — the QR is from a different event or is corrupted. Direct the guest to the organiser desk.',
          'For any denied result, do not override — direct the guest to the organiser\'s desk for resolution.',
        ],
      },
      {
        id: 'staff-zones', icon: '🚪', title: 'Zone scanning & gates',
        img: '/media/help-check-in.png',
        steps: [
          'If the event has Entry areas enabled, Check-in shows an Area/Gate picker before you start.',
          'Gate mode (recommended): select your named gate once (e.g. "VIP Lounge Door"). The zone and direction are pre-configured — every scan automatically enforces the rules for that gate.',
          'Manual mode: pick a zone (e.g. Main Hall) and direction (Entry or Exit) yourself. Change it if you move to a different gate.',
          'The scan result shows "Allowed" (green) or "Denied" (red) plus the live occupancy count for that zone.',
          'Denied reasons shown on screen: "Wrong zone for ticket type", "Tag not permitted here", "Zone at capacity".',
          'A guest\'s first allowed Entry scan anywhere in the venue also counts as their event check-in — no separate check-in scan needed.',
          'Exit scans are optional — they help track who is still inside the venue.',
          'Live occupancy is shown below the scan result — you can see if a zone is filling up.',
        ],
        tip: 'If you\'re covering multiple gates, stay on Gate mode and switch your gate selection each time you move — don\'t try to use Manual mode for a fast-moving door.',
      },
      {
        id: 'staff-tips', icon: '💡', title: 'Tips for a smooth check-in',
        steps: [
          'Keep your phone charged — bring a power bank for all-day events.',
          'Use a phone holder or lanyard so your hands are free to manage the queue.',
          'Brief other staff before opening: agree on what to do if a QR is denied or a guest can\'t find their ticket.',
          'For large events with queues: open multiple check-in stations and assign a separate area/gate to each — parallel scanning dramatically reduces wait times.',
          'If the camera freezes: close and reopen the Check-in tab. You don\'t lose any data.',
          'Guests who can\'t find their QR: ask them to check their confirmation email/SMS/WhatsApp. If still missing, direct them to the organiser desk for lookup in Guests.',
          'Manual lookup: ask the organiser to use Guests or the ticket code lookup to confirm the guest before entry.',
          'Noisy lighting (direct sunlight, flashing lights): tilt the guest\'s screen slightly towards you or ask them to cup their hand over it to reduce glare.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // GUEST
  // ─────────────────────────────────────────────────────────────────────────
  guest: {
    label: 'Guest',
    icon: '🎉',
    blurb: 'You received an invite — here\'s everything you need from RSVP to arrival.',
    topics: [
      {
        id: 'guest-open', icon: '🔗', title: 'Open your invite',
        img: '/media/help-guest-invite.png',
        steps: [
          'Tap the link in your email, SMS, or WhatsApp message. It opens in your phone browser — no app download needed.',
          'If the link asks you to "Open with…" — choose your browser (Chrome, Safari, etc.).',
          'If the link has expired: RSVP deadlines are set by the host. Contact them directly to be added manually.',
          'If you can\'t find your invite: check your spam/junk folder (email) or your WhatsApp message requests.',
        ],
      },
      {
        id: 'guest-rsvp', icon: '📝', title: 'RSVP',
        steps: [
          'Fill in your name and any questions the host has set (dietary preference, item choice, t-shirt size, etc.).',
          'Click Confirm to say yes, or "Can\'t make it" to decline.',
          'On a personal (closed) invite link, you can return and change your answer until the RSVP deadline.',
          'If the host requires approval, you\'ll see "RSVP submitted — awaiting confirmation" until they approve. You\'ll get a notification when you\'re confirmed.',
          'If you\'re bringing a plus-one: look for the partner/plus-one option on your ticket page after confirming — link your partner\'s name so you\'re seated together.',
        ],
        tip: 'RSVP as soon as possible — some events have capacity limits and close registrations once full.',
      },
      {
        id: 'guest-ticket', icon: '🎟️', title: 'Your ticket & QR code',
        steps: [
          'Once your RSVP is confirmed, you\'ll receive a confirmation email (and/or SMS/WhatsApp) with your personal QR code.',
          'On the day: show this QR at the entrance — staff will scan it with their phone camera. It\'s instant.',
          'You can also find your ticket by reopening the invite link — your QR is always there.',
          'The QR is personal and unique to you. Don\'t share it with anyone else.',
          'If the event uses zones (e.g. VIP areas): your ticket type controls which areas you can enter. If you\'re denied at a gate, speak to the organiser.',
          'Printed QR works just as well as showing it on your phone screen.',
        ],
        tip: 'Screenshot your QR code and save it to your phone\'s camera roll before the event, in case you lose internet access on the day.',
      },
      {
        id: 'guest-meal', icon: '🍽️', title: 'Order choices & seating',
        steps: [
          'If the host set up orders, you\'ll see a "Pick your items" section on your ticket/RSVP page.',
          'Pick your choice before the deadline shown — after the deadline, changes may not be accepted.',
          'Your item choices are sent to the event team and linked to your table automatically — you don\'t need to tell anyone on the day.',
          'Seating: the host assigns tables. Your table and seat number (if assigned) appear on your ticket page before the event.',
          'If you\'re attending as a couple/group: link your plus-one on your ticket page so the host can seat you together.',
        ],
      },
      {
        id: 'guest-address', icon: '📦', title: 'Providing your address (aso-ebi / gifts)',
        steps: [
          'Some events collect shipping addresses for aso-ebi fabric, welcome bags, or post-event gift delivery.',
          'If address collection is on, you\'ll see an address form on the RSVP or ticket page.',
          'Enter your full delivery address including postcode/zip code and country.',
          'You can update your address by returning to your invite link before the shipping cutoff date set by the host.',
          'If you missed the address deadline: contact the host directly.',
        ],
      },
      {
        id: 'guest-registry', icon: '🎁', title: 'Gift registry',
        steps: [
          'If the host shares a registry link, open it to browse their gift wishlist and cash contribution funds.',
          'Click "I\'ll bring this" on any item to claim it — others will see it\'s taken so nobody buys duplicates.',
          'For cash funds: the host\'s payment details or instructions are shown — you transfer directly, not through EventQR.',
          'You can unclaim an item if your plans change — just return to the registry link and untick.',
          'No account or login required to view or claim items.',
        ],
      },
      {
        id: 'guest-faq', icon: '❓', title: 'Guest FAQ',
        intro: 'Quick answers to common questions.',
        steps: [
          'I didn\'t get a confirmation email — check your spam folder first. If it\'s not there, return to your invite link and confirm your email address is correct. Contact the host to resend.',
          'I can\'t find the invite link — check your email, SMS, and WhatsApp message requests. Ask the host to resend it.',
          'The link says "RSVP closed" — the deadline or capacity limit has passed. Contact the host directly.',
          'My QR won\'t scan — ask the staff member to direct you to the organiser desk. The organiser can confirm your invite or ticket code.',
          'I want to bring an extra guest — contact the host. They control plus-one allowances.',
          'I need to cancel — return to your invite link and change your RSVP to "Can\'t make it". Contact the host if you\'re past the deadline.',
          'I have a dietary requirement — if there\'s no option on the RSVP form, add a note in the "special requests" field or contact the host directly.',
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────────────
  // OPERATOR
  // ─────────────────────────────────────────────────────────────────────────
  operator: {
    label: 'Operator',
    icon: '🛠️',
    blurb: 'Platform management — organisations, billing, pricing, and support tooling.',
    topics: [
      {
        id: 'op-open', icon: '🛠️', title: 'Open the Console',
        steps: [
          'Operators see a Console link in the main navigation when signed in.',
          'Direct URL: /console.',
          'The Console is only visible to accounts with the platform superadmin role.',
          'If you need operator access added, contact another existing operator.',
        ],
      },
      {
        id: 'op-grant', icon: '🎁', title: 'Comp events & add credits',
        steps: [
          'Console → Overview: lists every organisation with its events.',
          'Click an event → Comp Event: select a tier to grant it free (the tiers configured in Pricing). The organiser immediately gets all features of that tier.',
          'Click an organisation → Add Credits: enter a credit amount to top up their message credit balance at no charge.',
          'Comps and credit grants are logged with the operator name and timestamp.',
          'To remove a comp: click the event and select Remove Comp — the event reverts to its paid status.',
        ],
      },
      {
        id: 'op-trials', icon: '🎟️', title: 'Trial requests',
        steps: [
          'Console → Trial requests: lists customers who submitted a free trial request from Event Setup.',
          'Each request shows: contact name, email, phone, event name, use case description, and submission date.',
          'Approve: select a tier to comp their event onto (and optionally add message credits). Click Approve — the customer is emailed the decision automatically.',
          'Decline: click Decline — the customer is emailed that their request wasn\'t approved.',
          'If the requester has no event yet: approve with no event selected — the comp is held and applied to their next event automatically.',
          'Approved trials do not auto-expire — remove the comp manually from the event if needed after the trial period.',
        ],
      },
      {
        id: 'op-accounts', icon: '🧑‍💼', title: 'Manage accounts',
        steps: [
          'Console → Accounts: every organisation with its members, roles, and event count.',
          'Suspend an org: all members lose access to its events immediately. Reversible — reactivate any time. No data is lost.',
          'Delete an org: permanently removes the org and all its events and data. Requires typing the org name to confirm. Irreversible.',
          'Per member actions: change role (Owner / Admin / Staff), remove from org, suspend user (blocks all sign-in), or delete user (removes account + disables sign-in).',
          'Guard rails: you cannot suspend or delete yourself, the last operator account, or the default org.',
          'View a member\'s full sign-in history and last active date from their profile.',
        ],
        warn: 'Org deletion is permanent and cannot be undone. Always confirm with the customer before deleting.',
      },
      {
        id: 'op-pricing', icon: '💲', title: 'Edit pricing & plans',
        steps: [
          'Console → Pricing: view and edit all event pass tiers and message credit packs.',
          'Edit a tier: change the display name, price (USD and/or NGN), guest cap, active/inactive status.',
          'Add a new tier: useful for custom enterprise plans.',
          'Message credit packs: edit the credits-per-pack, price, and active status.',
          'Changes apply immediately to the public pricing page and checkout.',
          'Deactivating a tier hides it from checkout but doesn\'t affect events already on that tier.',
        ],
      },
      {
        id: 'op-operators', icon: '👤', title: 'Manage operators',
        steps: [
          'Console → Operators: lists all accounts with platform superadmin access.',
          'Add an operator: enter their email address. They must already have a EventQR account.',
          'Revoke an operator: removes their superadmin access. You cannot revoke your own access.',
          'Keep the operator list minimal — operator accounts have unrestricted access to all organisations and data.',
        ],
        warn: 'Only grant operator access to trusted team members. Operators can view, modify, and delete any organisation\'s data.',
      },
    ],
  },
}
