// Build-time generator: flattens the SAME structured content that powers the
// in-app Help guide and /guide.html (frontend/src/guideContent.mjs) into a
// single markdown knowledge base for support-service's AI drafting prompt.
// No paywall redaction — HelpPage.jsx already renders all topic content
// (including "Paid" badge topics) as plain unrestricted text.
//
// Regenerate and commit the output whenever guideContent.mjs changes:
//   node support-service/scripts/build_knowledge_base.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { CONTENT } from '../../frontend/src/guideContent.mjs'

const ROLES = ['organizer', 'staff', 'guest', 'operator']

function topicMarkdown(t) {
  const lines = [`### ${t.title}`, '']
  if (t.intro) lines.push(t.intro, '')
  if (t.steps?.length) {
    lines.push(...t.steps.map((s, i) => `${i + 1}. ${s}`), '')
  }
  if (t.tip) lines.push(`Tip: ${t.tip}`, '')
  if (t.warn) lines.push(`Warning: ${t.warn}`, '')
  return lines.join('\n')
}

function roleMarkdown(key) {
  const r = CONTENT[key]
  if (!r) return ''
  return [
    `## ${r.label}`,
    '',
    r.blurb || '',
    '',
    ...r.topics.map(topicMarkdown),
  ].join('\n')
}

const doc = [
  '# Festio product documentation',
  '',
  'Generated from frontend/src/guideContent.mjs — do not edit by hand, run',
  'support-service/scripts/build_knowledge_base.mjs to regenerate.',
  '',
  ...ROLES.map(roleMarkdown),
].join('\n')

writeFileSync(new URL('../app/knowledge_base.md', import.meta.url), doc)

// Media Library is operator-only. Bundle the generated support knowledge and
// internal QA runbook into the frontend so operators can view/download them
// without exposing a public static URL. guideContent.mjs itself is imported
// with Vite's ?raw loader by MediaPage, so it keeps its own source of truth.
const runbook = readFileSync(new URL('../docs/QA_RELEASE_CERTIFICATION_RUNBOOK.md', import.meta.url), 'utf8')
const bundledDocs = [
  '// Generated by support-service/scripts/build_knowledge_base.mjs. Do not edit.',
  `export const KNOWLEDGE_BASE_MD = ${JSON.stringify(doc)}`,
  `export const QA_RELEASE_RUNBOOK_MD = ${JSON.stringify(runbook)}`,
  '',
].join('\n')
writeFileSync(new URL('../../frontend/src/generated/internalMediaDocs.mjs', import.meta.url), bundledDocs)
console.log(`wrote knowledge_base.md (${doc.length} chars)`)
