ALTER TABLE event_configs ADD COLUMN IF NOT EXISTS tax_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE event_configs ADD COLUMN IF NOT EXISTS tax_bps INTEGER NOT NULL DEFAULT 0;
ALTER TABLE event_configs ADD COLUMN IF NOT EXISTS tax_paid_by VARCHAR(20) NOT NULL DEFAULT 'buyer';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_amount INTEGER NOT NULL DEFAULT 0;
