import { useEffect, useMemo, useState } from 'react'
import { api } from '../../api'
import './DonationTrackerPanel.css'

const TYPES = [
  ['festio_pay','Festio Pay'],['cash_app','Cash App'],['zelle','Zelle'],['paypal','PayPal'],
  ['bank_transfer','Bank transfer'],['offline','Cash / cheque'],['pledge','Pledge now'],
]
const money = (minor, currency='USD') => new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:0}).format((minor||0)/100)
const baseChannel = ([type,label]) => ({type,label,enabled:['festio_pay','pledge'].includes(type),public_instructions:'',checkout_url:''})

export default function DonationTrackerPanel({ eventId, displays=[] }) {
  const [campaign,setCampaign]=useState(null), [rows,setRows]=useState([]), [error,setError]=useState(''), [busy,setBusy]=useState(false)
  const [filter,setFilter]=useState('all'), [selectedDisplay,setSelectedDisplay]=useState('')
  const [offline,setOffline]=useState({channel:'offline',amount:'',donor_name:'',status:'confirmed',anonymous_publicly:false,hide_amount_publicly:false})
  const [codeInput,setCodeInput]=useState(''), [codeBusy,setCodeBusy]=useState(false)
  async function load(){ try { const [c,r]=await Promise.all([api.donationCampaign(eventId),api.donationContributions(eventId)]); setCampaign(c);setRows(r);setSelectedDisplay((v)=>v||displays?.[0]?.id||'');setError('') } catch(e){setError(e.message)} }
  useEffect(()=>{load()},[eventId]) // eslint-disable-line react-hooks/exhaustive-deps
  const channelMap=useMemo(()=>new Map((campaign?.channels||[]).map((c)=>[c.type,c])),[campaign])
  const channels=TYPES.map((type)=>channelMap.get(type[0])||baseChannel(type))
  const visible=rows.filter((row)=>filter==='all'||row.status===filter)
  async function save(){setBusy(true);try{const payload={...campaign,channels,goal_minor:Number(campaign.goal_minor)||0};delete payload.id;delete payload.event_id;delete payload.public_token;delete payload.public_url;delete payload.event_name;delete payload.confirmed_minor;delete payload.pending_minor;delete payload.pledged_minor;delete payload.refunded_minor;delete payload.donation_count;delete payload.recent_public;delete payload.channel_totals;setCampaign(await api.saveDonationCampaign(eventId,payload));setError('')}catch(e){setError(e.message)}finally{setBusy(false)}}
  function updateChannel(type,patch){setCampaign((current)=>({...current,channels:TYPES.map((item)=>item[0]===type?{...(channelMap.get(type)||baseChannel(item)),...patch}:(channelMap.get(item[0])||baseChannel(item)))}))}
  async function transition(row,action){setBusy(true);try{await api[action](eventId,row.id,{});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function addOffline(e){e.preventDefault();setBusy(true);try{await api.addOfflineDonation(eventId,{...offline,amount_minor:Math.round(Number(offline.amount)*100),message:null,donor_email:null,donor_phone:null,expected_payment_channel:null,expected_payment_date:null,provider_reference:null});setOffline({...offline,amount:'',donor_name:''});await load()}catch(err){setError(err.message)}finally{setBusy(false)}}
  async function saveCode(e){e.preventDefault();if(!codeInput.trim())return;setCodeBusy(true);try{await api.setEventCode(eventId,codeInput.trim());await load();setCodeInput('')}catch(err){setError(err.message)}finally{setCodeBusy(false)}}
  async function present(){const display=displays.find((item)=>item.id===selectedDisplay);if(!display)return;setBusy(true);try{await api.liveUpdateDisplay(eventId,display.id,{scene:'donation_tracker',settings:{...(display.settings||{}),donation_token:campaign.public_token,donation_url:campaign.public_url,follow_activity:false}});setError('');alert(`Donation Tracker sent to ${display.name}`)}catch(e){setError(e.message)}finally{setBusy(false)}}
  if(!campaign)return <div className="dt-loading">{error||'Loading Donation Tracker…'}</div>
  const pct=campaign.goal_minor?Math.min(100,Math.round(campaign.confirmed_minor/campaign.goal_minor*100)):0
  return <div className="dt-wrap">
    <section className="dt-hero"><div><span>FESTIO LIVE GIVING</span><h2>Donation Tracker</h2><p>One Giving Hub, verified totals, privacy-safe projector moments.</p></div><label className="dt-switch"><input type="checkbox" checked={campaign.enabled} onChange={(e)=>setCampaign({...campaign,enabled:e.target.checked})}/><span>{campaign.enabled?'Enabled':'Disabled'}</span></label></section>
    {error&&<div className="dt-error">{error}</div>}
    <div className="dt-kpis"><button onClick={()=>setFilter('confirmed')}><span>Confirmed</span><strong>{money(campaign.confirmed_minor,campaign.currency)}</strong><small>{campaign.donation_count} received</small></button><button onClick={()=>setFilter('pending_verification')}><span>Pending</span><strong>{money(campaign.pending_minor,campaign.currency)}</strong><small>Awaiting verification</small></button><button className={filter==='pledged'?'selected':''} onClick={()=>setFilter('pledged')}><span>Pledged</span><strong>{money(campaign.pledged_minor,campaign.currency)}</strong><small>View pledge details</small></button><button><span>Goal</span><strong>{money(campaign.goal_minor,campaign.currency)}</strong><small>{pct}% confirmed</small></button></div>
    <div className="dt-grid"><section className="dt-panel"><h3>Campaign settings</h3><label><span>Campaign title</span><input value={campaign.title} onChange={(e)=>setCampaign({...campaign,title:e.target.value})}/></label><label><span>Description</span><textarea value={campaign.description||''} onChange={(e)=>setCampaign({...campaign,description:e.target.value})}/></label><div className="dt-two"><label><span>Goal ({campaign.currency})</span><input type="number" min="0" value={(campaign.goal_minor||0)/100} onChange={(e)=>setCampaign({...campaign,goal_minor:Math.round(Number(e.target.value)*100)})}/></label><label><span>Currency</span><select value={campaign.currency} onChange={(e)=>setCampaign({...campaign,currency:e.target.value})}><option>USD</option><option>NGN</option><option>CAD</option><option>GBP</option><option>EUR</option></select></label></div><div className="dt-checks"><label><input type="checkbox" checked={campaign.show_donor_names} onChange={(e)=>setCampaign({...campaign,show_donor_names:e.target.checked})}/> Show donor names</label><label><input type="checkbox" checked={campaign.show_donor_amounts} onChange={(e)=>setCampaign({...campaign,show_donor_amounts:e.target.checked})}/> Show donor amounts</label><label><input type="checkbox" checked={campaign.show_pledged_total} onChange={(e)=>setCampaign({...campaign,show_pledged_total:e.target.checked})}/> Show pledges separately</label><label><input type="checkbox" checked={campaign.celebrate_milestones} onChange={(e)=>setCampaign({...campaign,celebrate_milestones:e.target.checked})}/> Celebrate milestones</label></div><button className="dt-primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save campaign'}</button></section>
      <section className="dt-panel"><h3>Giving channels</h3><div className="dt-channels">{channels.map((item)=><article key={item.type}><label><input type="checkbox" checked={item.enabled} onChange={(e)=>updateChannel(item.type,{enabled:e.target.checked})}/><b>{item.label}</b></label>{item.enabled&&!['festio_pay','pledge','offline'].includes(item.type)&&<textarea placeholder="Public payment instructions" value={item.public_instructions||''} onChange={(e)=>updateChannel(item.type,{public_instructions:e.target.value})}/>} {item.enabled&&item.type==='festio_pay'&&<input placeholder="Secure checkout URL" value={item.checkout_url||''} onChange={(e)=>updateChannel(item.type,{checkout_url:e.target.value})}/>}</article>)}</div><div className="dt-link"><span>Guest Giving Hub</span><a href={campaign.public_url} target="_blank" rel="noreferrer">{campaign.public_url}</a></div><form className="dt-code" onSubmit={saveCode}><span>Custom short code (also used for self check-in)</span><div><input placeholder="e.g. iedpu26" value={codeInput} onChange={(e)=>setCodeInput(e.target.value)}/><button className="dt-primary" disabled={codeBusy||!codeInput.trim()}>{codeBusy?'Saving…':'Update link'}</button></div></form></section>
    </div>
    <section className="dt-panel dt-projector"><div><h3>Projector display</h3><p>Confirmed funds lead. Pledges remain a separately labelled secondary number.</p></div><select value={selectedDisplay} onChange={(e)=>setSelectedDisplay(e.target.value)}><option value="">Choose display</option>{displays.map((d)=><option value={d.id} key={d.id}>{d.name}</option>)}</select><button className="dt-primary" disabled={!campaign.enabled||!selectedDisplay||busy} onClick={present}>Display on screen</button></section>
    <section className="dt-panel"><div className="dt-table-head"><div><h3>{filter==='pledged'?'Pledge details':'Contribution ledger'}</h3><p>Confirmed, pending and pledged funds remain independently traceable.</p></div><select value={filter} onChange={(e)=>setFilter(e.target.value)}><option value="all">All statuses</option><option value="confirmed">Confirmed</option><option value="pending_verification">Pending verification</option><option value="pledged">Pledged</option><option value="failed">Failed</option><option value="cancelled">Cancelled</option></select></div><div className="dt-table"><div className="head"><span>Donor</span><span>Amount</span><span>Channel</span><span>Due date</span><span>Status</span><span>Actions</span></div>{visible.map((row)=><div className="row" key={row.id}><span><b>{row.donor_name||'Not provided'}</b><small>{row.reference}</small>{row.anonymous_publicly&&<small>Anonymous publicly</small>}</span><span>{money(row.amount_minor,row.currency)}{row.hide_amount_publicly&&<small>Hidden publicly</small>}</span><span>{row.expected_payment_channel||row.channel}</span><span>{row.expected_payment_date?new Date(row.expected_payment_date).toLocaleDateString():'—'}</span><span><em className={row.status}>{row.status.replaceAll('_',' ')}</em></span><span>{['pledged','pending_verification','initiated'].includes(row.status)&&<button disabled={busy} onClick={()=>transition(row,'verifyDonation')}>Mark received</button>}{row.status==='pending_verification'&&<button disabled={busy} onClick={()=>transition(row,'rejectDonation')}>Reject</button>}{['pledged','initiated'].includes(row.status)&&<button disabled={busy} onClick={()=>transition(row,'cancelDonation')}>Cancel</button>}</span></div>)}{!visible.length&&<p className="dt-empty">No contributions match this view.</p>}</div></section>
    <section className="dt-panel"><h3>Add offline donation or pledge</h3><form className="dt-offline" onSubmit={addOffline}><input required placeholder="Donor name" value={offline.donor_name} onChange={(e)=>setOffline({...offline,donor_name:e.target.value})}/><input required type="number" min="1" step=".01" placeholder="Amount" value={offline.amount} onChange={(e)=>setOffline({...offline,amount:e.target.value})}/><select value={offline.channel} onChange={(e)=>setOffline({...offline,channel:e.target.value})}><option value="offline">Cash / cheque</option><option value="bank_transfer">Bank transfer</option><option value="cash_app">Cash App</option><option value="zelle">Zelle</option><option value="pledge">Pledge</option></select><select value={offline.status} onChange={(e)=>setOffline({...offline,status:e.target.value})}><option value="confirmed">Confirmed</option><option value="pending_verification">Pending verification</option><option value="pledged">Pledged</option></select><label><input type="checkbox" checked={offline.anonymous_publicly} onChange={(e)=>setOffline({...offline,anonymous_publicly:e.target.checked})}/> Anonymous publicly</label><button className="dt-primary" disabled={busy}>Add record</button></form></section>
  </div>
}
