import { useEffect, useMemo, useState } from 'react'
import { api } from '../../api'
import './LiveContentWorkspace.css'

const DEFAULT_DESIGN = { title: 'Certificate of Participation', subtitle: 'This certificate is proudly presented to', body: 'For successful participation in this event', primary_color: '#075845', accent_color: '#dba92e', signature_name: 'Event Organizer', orientation: 'landscape' }

function Notice({ value }) { return value ? <div className={`lc-notice ${value.type || ''}`}>{value.text}</div> : null }
function Field({ label, children, help }) { return <label className="lc-field"><span>{label}</span>{children}{help && <small>{help}</small>}</label> }

export function PresenterMaterialsWorkspace({ eventId, sessions = [], displays = [] }) {
  const [materials, setMaterials] = useState([]), [notice, setNotice] = useState(null), [busy, setBusy] = useState(false)
  const [mode, setMode] = useState('upload')
  const [displayId, setDisplayId] = useState('')
  const [presenting, setPresenting] = useState(null)
  const [form, setForm] = useState({ title: '', session_step_id: '', kind: 'slides', visibility: 'production', availability: 'after_approval', url: '' })
  const [file, setFile] = useState(null)
  const load = () => api.listPresenterMaterials(eventId).then(setMaterials).catch((e) => setNotice({ type: 'error', text: e.message }))
  useEffect(() => { load() }, [eventId])
  const submit = async (e) => {
    e.preventDefault(); setBusy(true); setNotice(null)
    try {
      if (mode === 'upload') {
        if (!file) throw new Error('Choose a presentation or resource file.')
        await api.uploadPresenterMaterial(eventId, file, form)
      } else await api.addPresenterMaterialLink(eventId, { ...form, session_step_id: form.session_step_id || null })
      setForm((v) => ({ ...v, title: '', url: '' })); setFile(null); await load()
      setNotice({ type: 'success', text: 'Material saved. Review it before approving it for the event.' })
    } catch (e2) { setNotice({ type: 'error', text: e2.message }) } finally { setBusy(false) }
  }
  const update = async (row, patch) => { setBusy(true); try { await api.updatePresenterMaterial(eventId, row.id, patch); await load() } catch (e) { setNotice({type:'error', text:e.message}) } finally { setBusy(false) } }
  const present = async (row, patch = {}) => {
    const target = displayId || displays[0]?.id
    if (!target) { setNotice({ type: 'error', text: 'Create or select a Festio Live display channel first.' }); return }
    const current = presenting?.material?.id === row.id ? presenting : { material: row, page: 1, blackout: false }
    const next = { ...current, ...patch, material: row }
    setBusy(true)
    try {
      await api.liveUpdateDisplay(eventId, target, { scene: 'presentation', assigned_activity_id: null, settings: { control_mode: 'manual', follow_activity: false, presentation: { material_id: row.id, title: row.title, url: row.metadata?.present_url || row.source_url, content_type: row.content_type, kind: row.kind, page: next.page, blackout: next.blackout, autoplay: row.kind === 'video', total_pages: row.metadata?.page_count || null } } })
      setDisplayId(target); setPresenting(next); setNotice({ type: 'success', text: `${row.title} is live on ${displays.find((item) => item.id === target)?.name || 'the selected display'}.` })
    } catch (error) { setNotice({ type: 'error', text: error.message }) } finally { setBusy(false) }
  }
  return <section className="lc-workspace">
    <header className="lc-hero"><div><span>Presenter library</span><h2>Session materials</h2><p>Collect, review, present, and release every deck and handout from one event-scoped workspace.</p></div><div className="lc-stat"><strong>{materials.length}</strong><small>materials</small></div></header>
    <Notice value={notice}/>
    {!!displays.length && <div className="lc-presenter-bar"><Field label="Presentation display"><select value={displayId || displays[0]?.id || ''} onChange={e=>setDisplayId(e.target.value)}>{displays.map(display=><option key={display.id} value={display.id}>{display.name}{display.connected?' · connected':' · offline'}</option>)}</select></Field>{presenting&&<><div><small>Now presenting</small><strong>{presenting.material.title}</strong></div><button disabled={busy||presenting.page<=1} onClick={()=>present(presenting.material,{page:Math.max(1,presenting.page-1)})}>← Previous</button><b>Page {presenting.page}</b><button disabled={busy} onClick={()=>present(presenting.material,{page:presenting.page+1})}>Next →</button><button className={presenting.blackout?'active':''} disabled={busy} onClick={()=>present(presenting.material,{blackout:!presenting.blackout})}>{presenting.blackout?'Restore screen':'Blackout'}</button></>}</div>}
    <div className="lc-grid">
      <form className="lc-card lc-form" onSubmit={submit}>
        <div className="lc-card-head"><div><b>Add material</b><small>Files stay private until you approve their visibility.</small></div><div className="lc-switch"><button type="button" className={mode==='upload'?'active':''} onClick={()=>setMode('upload')}>Upload</button><button type="button" className={mode==='link'?'active':''} onClick={()=>setMode('link')}>Link</button></div></div>
        <Field label="Session"><select value={form.session_step_id} onChange={e=>setForm({...form,session_step_id:e.target.value})}><option value="">Event-wide resource</option>{sessions.map(s=><option key={s.id || s.source_step_id} value={s.id || s.source_step_id}>{s.title}</option>)}</select></Field>
        <Field label="Display title"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Leadership keynote deck"/></Field>
        {mode==='upload' ? <Field label="File" help="PDF, PowerPoint, Excel, images, or MP4 · maximum 100 MB"><input type="file" accept=".pdf,.ppt,.pptx,.xls,.xlsx,.jpg,.jpeg,.png,.webp,.mp4" onChange={e=>setFile(e.target.files?.[0]||null)}/></Field> : <Field label="Secure source link" help="Google Slides, Microsoft 365, video, sheet, or website link"><input required type="url" value={form.url} onChange={e=>setForm({...form,url:e.target.value})} placeholder="https://…"/></Field>}
        <Field label="Guest release"><select value={form.availability} onChange={e=>setForm({...form,availability:e.target.value})}><option value="after_approval">As soon as approved</option><option value="after_session_attendance">After this session is attended</option></select></Field><div className="lc-two"><Field label="Material type"><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}>{['slides','pdf','handout','sheet','video','link'].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Audience"><select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}><option value="presenter">Presenter only</option><option value="production">Production team</option><option value="attendees">GuestHub attendees</option></select></Field></div>
        <button className="rr-btn primary" disabled={busy}>{busy?'Saving…':'Add to presenter library'}</button>
      </form>
      <div className="lc-card"><div className="lc-card-head"><div><b>Review queue</b><small>Approved items are ready for presentation or configured attendee release.</small></div></div>
        {!materials.length && <div className="lc-empty"><b>No materials yet</b><span>Upload a deck or attach a cloud presentation to begin.</span></div>}
        <div className="lc-list">{materials.map(row=><article key={row.id} className="lc-row"><div className={`lc-file-icon ${row.kind}`}>{row.kind==='slides'?'▤':row.kind==='video'?'▶':'⌑'}</div><div className="lc-row-main"><strong>{row.title}</strong><small>{row.session_title||'Event-wide'} · {row.source_type} · {row.visibility}</small><span className={`lc-status ${row.status}`}>{row.status}</span></div><div className="lc-actions"><a href={row.source_url} target="_blank" rel="noreferrer">Preview</a>{row.status==='approved'&&<button disabled={busy||row.metadata?.processing_status==='conversion_failed'} title={row.metadata?.processing_status==='conversion_failed'?'PowerPoint conversion failed; download the original file instead.':''} onClick={()=>present(row)}>Present</button>}{row.status!=='approved'&&<button disabled={busy} onClick={()=>update(row,{status:'approved'})}>Approve</button>}<button disabled={busy} onClick={()=>update(row,{status:'archived'})}>Archive</button></div></article>)}</div>
      </div>
    </div>
  </section>
}

export function CertificatesWorkspace({ eventId, sessions: suppliedSessions = [] }) {
  const [templates,setTemplates]=useState([]),[selected,setSelected]=useState(null),[candidates,setCandidates]=useState([]),[certificates,setCertificates]=useState([]),[chosen,setChosen]=useState(new Set()),[notice,setNotice]=useState(null),[busy,setBusy]=useState(false),[report,setReport]=useState(null),[availableSessions,setAvailableSessions]=useState(suppliedSessions)
  const load = async () => { const ts=await api.listCertificateTemplates(eventId); setTemplates(ts); const template=selected ? ts.find(t=>t.id===selected.id)||ts[0] : ts[0]; setSelected(template||null); setCertificates(await api.listEventCertificates(eventId)); if(template) setCandidates(await api.listCertificateCandidates(eventId,template.id)) }
  useEffect(()=>{ load().catch(e=>setNotice({type:'error',text:e.message})); api.listLiveContentSessions(eventId).then(setAvailableSessions).catch(()=>setAvailableSessions(suppliedSessions)) },[eventId])
  useEffect(()=>{ if(selected) api.listCertificateCandidates(eventId,selected.id).then(setCandidates).catch(e=>setNotice({type:'error',text:e.message})) },[selected?.id])
  const eligible=useMemo(()=>candidates.filter(c=>c.eligible&&!c.issued),[candidates])
  const design={...DEFAULT_DESIGN,...(selected?.design||{})}, eligibility={minimum_sessions:1,require_event_checkin:true,required_session_ids:[],...(selected?.eligibility||{})}
  const save = async () => { setBusy(true); try { const row=await api.saveCertificateTemplate(eventId,selected.id,{name:selected.name,design,eligibility,active:selected.active}); setSelected(row); setNotice({type:'success',text:'Certificate design and eligibility rules saved.'}) } catch(e){setNotice({type:'error',text:e.message})} finally{setBusy(false)} }
  const editDesign=(key,value)=>setSelected({...selected,design:{...design,[key]:value}}), editEligibility=(key,value)=>setSelected({...selected,eligibility:{...eligibility,[key]:value}})
  const createTemplate=async()=>{setBusy(true);try{const row=await api.createCertificateTemplate(eventId,{name:`Certificate ${templates.length+1}`,design:DEFAULT_DESIGN,eligibility:{minimum_sessions:1,require_event_checkin:true,required_session_ids:[]},active:true});setTemplates([...templates,row]);setSelected(row);setNotice({type:'success',text:'New certificate template created.'})}catch(e){setNotice({type:'error',text:e.message})}finally{setBusy(false)}}
  const uploadAsset=async(key,file)=>{if(!file)return;setBusy(true);try{const result=await api.uploadCertificateAsset(eventId,file);editDesign(key,result.url);setNotice({type:'success',text:'Image uploaded. Save the template to apply it.'})}catch(e){setNotice({type:'error',text:e.message})}finally{setBusy(false)}}
  const loadReport=async()=>{setBusy(true);try{setReport(await api.certificateReport(eventId))}catch(e){setNotice({type:'error',text:e.message})}finally{setBusy(false)}}
  const issue=async(send_email)=>{setBusy(true);try{const ids=chosen.size?[...chosen]:eligible.map(c=>c.guest_id);const result=await api.issueEventCertificates(eventId,{template_id:selected.id,guest_ids:ids,eligible_only:true,send_email});setChosen(new Set());await load();setNotice({type:'success',text:`Issued ${result.issued} certificate${result.issued===1?'':'s'}${send_email?' and queued email delivery':''}.`})}catch(e){setNotice({type:'error',text:e.message})}finally{setBusy(false)}}
  if(!selected) return <div className="fl-loading">Preparing certificate studio…</div>
  return <section className="lc-workspace"><header className="lc-hero certificate"><div><span>Credential studio</span><h2>Participant certificates</h2><p>Qualify attendees from real event records, issue verifiable credentials, and deliver digital copies.</p></div><div className="lc-stat"><strong>{certificates.filter(c=>c.status==='issued').length}</strong><small>issued</small></div></header><Notice value={notice}/>
    <div className="lc-grid certificate-grid"><div className="lc-card lc-form"><div className="lc-card-head"><div><b>Design and rules</b><small>Changes apply to future certificates; issued snapshots remain unchanged.</small></div><button type="button" onClick={createTemplate} disabled={busy}>+ New template</button></div>
      <Field label="Template"><select value={selected.id} onChange={e=>setSelected(templates.find(t=>t.id===e.target.value))}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}{t.active?'':' · inactive'}</option>)}</select></Field>
      <Field label="Certificate name"><input value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/></Field><Field label="Heading"><input value={design.title} onChange={e=>editDesign('title',e.target.value)}/></Field><Field label="Recognition text"><input value={design.body} onChange={e=>editDesign('body',e.target.value)}/></Field><div className="lc-two"><Field label="Primary color"><input type="color" value={design.primary_color} onChange={e=>editDesign('primary_color',e.target.value)}/></Field><Field label="Accent color"><input type="color" value={design.accent_color} onChange={e=>editDesign('accent_color',e.target.value)}/></Field></div><Field label="Signature label"><input value={design.signature_name} onChange={e=>editDesign('signature_name',e.target.value)}/></Field>
      <div className="lc-assets"><Field label="Logo"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadAsset('logo_url',e.target.files?.[0])}/>{design.logo_url&&<small>Logo ready</small>}</Field><Field label="Background"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadAsset('background_url',e.target.files?.[0])}/>{design.background_url&&<small>Background ready</small>}</Field><Field label="Signature image"><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>uploadAsset('signature_url',e.target.files?.[0])}/>{design.signature_url&&<small>Signature ready</small>}</Field></div>
      <div className="lc-rule"><label><input type="checkbox" checked={!!eligibility.auto_issue} onChange={e=>editEligibility('auto_issue',e.target.checked)}/> Automatically issue when all rules are met</label><label><input type="checkbox" checked={eligibility.require_event_checkin} onChange={e=>editEligibility('require_event_checkin',e.target.checked)}/> Require convention check-in</label><Field label="Minimum sessions attended"><input type="number" min="0" value={eligibility.minimum_sessions} onChange={e=>editEligibility('minimum_sessions',Number(e.target.value))}/></Field>{!!availableSessions.length&&<Field label="Required sessions" help="Leave all unchecked to use only the minimum attendance count."><div className="lc-session-rules">{availableSessions.map(session=>{const id=session.id||session.source_step_id;return <label key={id}><input type="checkbox" checked={eligibility.required_session_ids.includes(id)} onChange={e=>editEligibility('required_session_ids',e.target.checked?[...eligibility.required_session_ids,id]:eligibility.required_session_ids.filter(v=>v!==id))}/>{session.title}</label>})}</div></Field>}</div><button className="rr-btn primary" onClick={save} disabled={busy}>Save design and rules</button>
    </div><div className="lc-card lc-preview-wrap"><div className="lc-card-head"><div><b>Live certificate preview</b><small>Uses sample participant data.</small></div></div><div className="lc-certificate" style={{'--cert-primary':design.primary_color,'--cert-accent':design.accent_color,backgroundImage:design.background_url?`linear-gradient(#fffdf7dd,#fffdf7dd), url(${design.background_url})`:undefined}}>{design.logo_url&&<img className="lc-cert-logo" src={design.logo_url} alt="Certificate logo"/>}<span>{design.title}</span><small>{design.subtitle}</small><h3>Amara Participant</h3><h2>Event certificate</h2><p>{design.body}</p><footer><b>{design.signature_url&&<img className="lc-cert-signature" src={design.signature_url} alt="Signature"/>}{design.signature_name}</b><b>▦<br/>Scan to verify</b><b>FESTIO-2026-PREVIEW</b></footer></div></div></div>
    <div className="lc-card lc-candidates"><div className="lc-card-head"><div><b>Eligibility and issuance</b><small>{eligible.length} attendee{eligible.length===1?' is':'s are'} ready under the current rules.</small></div><div className="lc-actions"><button onClick={()=>issue(false)} disabled={busy||!eligible.length}>Issue selected</button><button className="primary" onClick={()=>issue(true)} disabled={busy||!eligible.length}>Issue & email</button></div></div><div className="lc-table"><table><thead><tr><th></th><th>Participant</th><th>Check-in</th><th>Sessions</th><th>Certificate</th></tr></thead><tbody>{candidates.map(c=><tr key={c.guest_id}><td><input type="checkbox" disabled={!c.eligible||c.issued} checked={chosen.has(c.guest_id)} onChange={e=>setChosen(prev=>{const n=new Set(prev);e.target.checked?n.add(c.guest_id):n.delete(c.guest_id);return n})}/></td><td><strong>{c.name}</strong><small>{c.email||'No email'}</small></td><td>{c.admitted?'Confirmed':'Not recorded'}</td><td>{c.sessions_attended}</td><td><span className={`lc-status ${c.issued?'approved':c.eligible?'ready':'draft'}`}>{c.issued?'Issued':c.eligible?'Eligible':'Pending'}</span></td></tr>)}</tbody></table></div></div>
    {!!certificates.length&&<div className="lc-card"><div className="lc-card-head"><div><b>Issued credentials</b><small>Verification and downloadable PDF remain available unless revoked.</small></div><button type="button" onClick={loadReport} disabled={busy}>Refresh report</button></div>{report&&<div className="lc-report">{Object.entries(report.summary).map(([key,value])=><span key={key}><b>{value}</b><small>{key}</small></span>)}</div>}<div className="lc-list">{certificates.map(c=><article className="lc-row" key={c.id}><div className="lc-file-icon pdf">✓</div><div className="lc-row-main"><strong>{c.guest_name}</strong><small>{c.certificate_number} · {new Date(c.issued_at).toLocaleDateString()}</small><span className={`lc-status ${c.status==='issued'?'approved':'draft'}`}>{c.status}</span></div><div className="lc-actions"><a href={c.document_url} target="_blank" rel="noreferrer">PDF</a><a href={c.verification_url} target="_blank" rel="noreferrer">Verify</a></div></article>)}</div></div>}
  </section>
}
