import { useEffect, useState } from 'react';
import { api } from '../../api';
import templates from './templates.json';
import '../guesthub/EventForms.css';
const initial = {title:'',body:'',kind:'consent',required:true,timing:'before_arrival',signer_policy:'adult_or_guardian',audience_kind:'everyone',conditions:{},questions:[],zone_id:null,step_id:null};
const clean = row => Object.fromEntries(Object.keys(initial).map(k=>[k,row[k] ?? initial[k]]));
export default function EventFormsAdmin({ eventId }) {
  const [items,setItems]=useState([]),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [options,setOptions]=useState({zones:[],sessions:[],tickets:[]}),[people,setPeople]=useState([]),[grants,setGrants]=useState([]),[records,setRecords]=useState(null),[history,setHistory]=useState(false),[search,setSearch]=useState('');
  const [grant,setGrant]=useState({guest_id:'',signer_guest_id:'',relationship:'parent',active:true,verified:false});
  async function load(){const [forms,opts,authority]=await Promise.all([api.listEventForms(eventId),api.eventFormOptions(eventId),api.eventConsentAuthorities(eventId)]);setItems(forms);setOptions(opts);setGrants(authority);}
  async function run(task,msg){setBusy(true);setError('');setNotice('');try{await task();if(msg)setNotice(msg)}catch(e){setError(e.message)}finally{setBusy(false)}}
  useEffect(()=>{setDraft(null);setRecords(null);setPeople([]);run(load);},[eventId]);
  useEffect(()=>{let active=true;const timer=setTimeout(()=>api.eventFormPeople(eventId,search).then(rows=>{if(active)setPeople(old=>[...new Map([...old,...rows].map(p=>[p.id,p])).values()])}).catch(e=>{if(active)setError(e.message)}),250);return()=>{active=false;clearTimeout(timer)}},[eventId,search]);
  const unsaved = draft?.id && JSON.stringify(clean(draft)) !== JSON.stringify(clean(items.find(f => f.id === draft.id) || initial));
  const patch = change => setDraft(old=>({...old,...change}));
  async function save(){const row=draft.id?await api.reviseEventForm(eventId,draft.id,{...clean(draft),expected_version:draft.version}):await api.createEventForm(eventId,clean(draft));setDraft(row);await load()}
  function exportRecords(){const cells=x=>'"'+String(x??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const lines=[['Form','Version','Attendee','Status','Signer','Time','Answers'],...(records||[]).map(r=>[r.title,r.version,r.guest_name,r.status,r.signer_name,r.signed_at,JSON.stringify(r.answers||{})])];const url=URL.createObjectURL(new Blob([lines.map(row=>row.map(cells).join(',')).join('\r\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='event-form-records.csv';a.click();URL.revokeObjectURL(url)}
  return <section className="form-admin event-forms" aria-label="Multiple event forms"><h2>Forms & consent</h2><p>Create independent forms for the event, meals and activities. Saving creates a draft version; guests see only a published version. Existing consent records remain below.</p>
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <div className="form-buttons"><button disabled={busy} onClick={()=>setDraft({...initial})}>New blank form</button><select aria-label="Choose draft template" defaultValue="" onChange={e=>{if(e.target.value!=='')setDraft({...initial,...templates[Number(e.target.value)]});e.target.value=''}}><option value="">Start from a draft template…</option>{templates.map((t,i)=><option key={t.title} value={i}>{t.title}</option>)}</select></div>
    <div className="form-columns"><div className="form-list">{items.map(f=><button key={f.id} onClick={()=>setDraft(f)}><strong>{f.title}</strong><small>{f.archived?'Archived':f.published_version?'Published v'+f.published_version:'Unpublished'} · Latest v{f.version}</small></button>)}</div>
    {draft&&<form onSubmit={e=>{e.preventDefault();run(save,'Draft saved. Review and publish when ready.')}}>
      <label>Form title<input required maxLength={255} value={draft.title} onChange={e=>patch({title:e.target.value})}/></label>
      <label>Wording<textarea required rows={10} value={draft.body} onChange={e=>patch({body:e.target.value})}/></label>
      <p>Templates are draft wording for organizer review. Confirm activity details and suitability before publishing.</p>
      <label>Form type<select value={draft.kind} onChange={e=>patch({kind:e.target.value})}><option value="consent">Consent with typed signature</option><option value="information">Information and acknowledgement</option></select></label>
      <label>Available<select value={draft.timing} onChange={e=>patch({timing:e.target.value})}><option value="before_arrival">After registration, before arrival</option><option value="after_admission">After check-in only</option></select></label>
      <label>Audience<select value={draft.audience_kind} onChange={e=>patch({audience_kind:e.target.value})}><option value="everyone">Everyone matching the rules below</option><option value="adults">Adults</option><option value="juniors">Juniors</option></select></label>
      <label>Who signs<select value={draft.signer_policy} onChange={e=>patch({signer_policy:e.target.value})}><option value="adult_or_guardian">Adult for self; authorized parent/legal guardian for child</option><option value="guardian">Authorized parent/legal guardian only</option></select></label>
      <label>Eligible age groups (comma separated)<input value={draft.ageInput ?? (draft.conditions.age_groups_include||[]).join(', ')} onChange={e=>patch({ageInput:e.target.value,conditions:{...draft.conditions,age_groups_include:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)}})} /></label>
      <label>Participant group tags (comma separated)<input value={draft.tagInput ?? (draft.conditions.guest_tags_include||[]).join(', ')} onChange={e=>patch({tagInput:e.target.value,conditions:{...draft.conditions,guest_tags_include:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)}})} placeholder="For example: registered-sports"/></label>
      <label>Ticket types (no selection means all)<select multiple value={draft.conditions.ticket_type_id||[]} onChange={e=>patch({conditions:{...draft.conditions,ticket_type_id:[...e.target.selectedOptions].map(x=>x.value)}})}>{options.tickets.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
      <label className="form-check"><input type="checkbox" checked={draft.required} onChange={e=>patch({required:e.target.checked})}/>Required for matching attendees</label>
      <label>Require completion before entering zone<select value={draft.zone_id||''} onChange={e=>patch({zone_id:e.target.value||null})}><option value="">No zone restriction</option>{options.zones.map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select></label>
      <label>Require completion before session attendance<select value={draft.step_id||''} onChange={e=>patch({step_id:e.target.value||null})}><option value="">No session restriction</option>{options.sessions.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label>
      {draft.questions.map((q,i)=><fieldset key={q.key}><legend>Question {i+1}</legend><label>Question<input required value={q.label} onChange={e=>patch({questions:draft.questions.map((v,n)=>n===i?{...v,label:e.target.value}:v)})}/></label><label>Answer type<select value={q.type} onChange={e=>patch({questions:draft.questions.map((v,n)=>n===i?{...v,type:e.target.value,options:v.options||[]}:v)})}>{['text','textarea','select','checkbox'].map(t=><option key={t}>{t}</option>)}</select></label>{q.type==='select'&&<label>Options (one per line)<textarea required value={(q.options||[]).join('\n')} onChange={e=>patch({questions:draft.questions.map((v,n)=>n===i?{...v,options:e.target.value.split('\n')}:v)})}/></label>}<label className="form-check"><input type="checkbox" checked={q.required} onChange={e=>patch({questions:draft.questions.map((v,n)=>n===i?{...v,required:e.target.checked}:v)})}/>Required answer</label><button type="button" onClick={()=>patch({questions:draft.questions.filter((_,n)=>n!==i)})}>Remove question</button></fieldset>)}
      <div className="form-buttons"><button type="button" onClick={()=>patch({questions:[...draft.questions,{key:'q_'+Date.now(),label:'',type:'text',required:false,options:[]}]})}>Add question</button><button disabled={busy}>Save draft version</button>{draft.id&&<button type="button" disabled={busy || unsaved} onClick={()=>run(async()=>{const f=await api.publishEventForm(eventId,draft.id,draft.version);setDraft(f);await load()},'Saved version published. Matching attendees can now complete it.')}>Publish saved version {draft.version}</button>}{draft.id&&!draft.archived&&<button type="button" disabled={busy} onClick={()=>run(async()=>{await api.archiveEventForm(eventId,draft.id);await load();setDraft(null)},'Form archived; submissions retained.')}>Archive form</button>}</div>
      {draft.id&&<p>Publish uses the saved version. Save any edits first. Publishing a new version requires fresh completion.</p>}
    </form>}
    </div>
    <details><summary>Parent / legal guardian signing permissions</summary><p>After verifying the relationship, grant permission for this attendee. Pickup permissions do not grant consent-signing rights.</p><label>Find attendees<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name"/></label><label>Child / attendee<select value={grant.guest_id} onChange={e=>setGrant({...grant,guest_id:e.target.value,verified:false})}><option value="">Choose attendee</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Parent / legal guardian<select value={grant.signer_guest_id} onChange={e=>setGrant({...grant,signer_guest_id:e.target.value,verified:false})}><option value="">Choose adult</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Relationship<select value={grant.relationship} onChange={e=>setGrant({...grant,relationship:e.target.value})}><option value="parent">Parent</option><option value="legal_guardian">Legal guardian</option></select></label><label className="form-check"><input type="checkbox" checked={grant.verified} onChange={e=>setGrant({...grant,verified:e.target.checked})}/>I have verified this adult's authority to sign for the attendee.</label><button disabled={busy||!grant.verified||!grant.guest_id||!grant.signer_guest_id} onClick={()=>run(async()=>{await api.saveConsentAuthority(eventId,grant);await load();setGrant({...grant,verified:false})},'Consent-signing permission saved.')}>Grant signing permission</button>{grants.filter(g=>g.active).map(g=><p key={g.id}>{people.find(p=>p.id===g.signer_guest_id)?.name||g.signer_guest_id} → {people.find(p=>p.id===g.guest_id)?.name||g.guest_id} ({g.relationship}) <button disabled={busy} onClick={()=>run(async()=>{await api.saveConsentAuthority(eventId,{guest_id:g.guest_id,signer_guest_id:g.signer_guest_id,relationship:g.relationship,active:false,verified:true});await load()},'Signing permission revoked.')}>Revoke</button></p>)}</details>
    <details><summary>Completion records and export</summary><div className="form-buttons"><button disabled={busy} onClick={()=>run(async()=>{setRecords(await api.eventFormRecords(eventId));setHistory(false)})}>Current completion status</button><button disabled={busy} onClick={()=>run(async()=>{setRecords(await api.eventFormRecords(eventId,true));setHistory(true)})}>Historical submissions</button>{records&&<button onClick={exportRecords}>Export CSV</button>}</div>{records&&<div className="table-scroll"><p>{history?'All recorded versions':'Current published forms'} · {records.length} records</p><table><thead><tr><th>Attendee</th><th>Form</th><th>Status</th><th>Signer</th><th>Answers</th></tr></thead><tbody>{records.map((r,i)=><tr key={i}><td>{r.guest_name}</td><td>{r.title} v{r.version}</td><td>{r.status}</td><td>{r.signer_name||'—'}</td><td>{r.answers&&<details><summary>View answers</summary><pre style={{whiteSpace:'pre-wrap'}}>{JSON.stringify(r.answers,null,2)}</pre></details>}</td></tr>)}</tbody></table></div>}</details>
  </section>;
}
