import { useMemo, useState } from 'react'
import './TicketDeliveryStudio.css'

const TOKENS=[['Event name','{{event_name}}'],['Order ID','{{order_id}}'],['First name','{{first_name}}'],['Last name','{{last_name}}'],['Ticket link','{{ticket_link}}']]
const sample={event_name:'NCNMO 2026',order_id:'6EDEA02F',first_name:'Alao',last_name:'Alao',ticket_link:'staging.festio.events/scan/demo'}
const render=value=>Object.entries(sample).reduce((text,[key,replacement])=>text.replaceAll(`{{${key}}}`,replacement),value||'')

export default function TicketDeliveryStudio({value,onChange,onSave,busy,eventName}){
  const [tab,setTab]=useState('email'), [saved,setSaved]=useState(JSON.stringify(value||{}))
  const dirty=JSON.stringify(value||{})!==saved
  const preview=useMemo(()=>({...sample,event_name:eventName||sample.event_name}),[eventName])
  const interpolate=text=>Object.entries(preview).reduce((out,[key,replacement])=>out.replaceAll(`{{${key}}}`,replacement),text||'')
  const update=(key,next)=>onChange({...value,[key]:next})
  const insert=(key,token)=>update(key,`${value[key]||''}${value[key]?' ':''}${token}`)
  async function submit(e){e.preventDefault();await onSave(value);setSaved(JSON.stringify(value))}
  return <form className="tds" onSubmit={submit} aria-labelledby="ticket-message-studio-title">
    <header className="tds-head"><div><span>Ticket communications</span><h3 id="ticket-message-studio-title">Delivery message studio</h3><p>Separate from RSVP and invitation templates. Every enabled channel sends after a paid or complimentary ticket is issued.</p></div><i className={dirty?'dirty':'saved'}>{dirty?'Unsaved changes':'Saved'}</i></header>
    <div className="tds-channels" role="tablist" aria-label="Delivery channels">
      {[['email','Email','QR included'],['sms','SMS','Phone required'],['whatsapp','WhatsApp','Phone required'],['pass','FestioPass','Design & preview']].map(([id,label,help])=><button type="button" role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><span className={`tds-dot ${id==='pass'||value[`${id}_enabled`]?'on':''}`}/><b>{label}</b><small>{help}</small>{id!=='pass'&&<input aria-label={`Enable ${label}`} type="checkbox" checked={!!value[`${id}_enabled`]} onClick={e=>e.stopPropagation()} onChange={e=>update(`${id}_enabled`,e.target.checked)}/>}</button>)}
    </div>
    <div className="tds-workspace"><section className="tds-editor">
      <div className="tds-editor-title"><div><b>{tab==='email'?'Ticket email':tab==='sms'?'Ticket SMS':tab==='whatsapp'?'Ticket WhatsApp':'FestioPass designer'}</b><small>{tab==='pass'?'Customize the actual mobile pass guests open.':'Customize the message sent specifically for ticket delivery.'}</small></div><span>{tab==='pass'?'Live design':value[`${tab}_enabled`]?'Enabled':'Disabled'}</span></div>
      {tab==='pass'?<div className="tds-pass-fields"><label><span>Header eyebrow</span><input value={value.pass_design?.eyebrow||''} onChange={e=>update('pass_design',{...value.pass_design,eyebrow:e.target.value})}/></label><label><span>Attendee label</span><input value={value.pass_design?.attendee_label||''} onChange={e=>update('pass_design',{...value.pass_design,attendee_label:e.target.value})}/></label><label><span>Text below QR code</span><textarea rows="3" value={value.pass_design?.qr_instruction||''} onChange={e=>update('pass_design',{...value.pass_design,qr_instruction:e.target.value})}/></label><label><span>Primary button text</span><input value={value.pass_design?.button_label||''} onChange={e=>update('pass_design',{...value.pass_design,button_label:e.target.value})}/></label><label><span>Footer message</span><textarea rows="3" placeholder="Optional terms, sponsor text or arrival note" value={value.pass_design?.footer_message||''} onChange={e=>update('pass_design',{...value.pass_design,footer_message:e.target.value})}/></label><label><span>Accent color</span><div className="tds-color"><input type="color" value={value.pass_design?.accent_color||'#14b8a6'} onChange={e=>update('pass_design',{...value.pass_design,accent_color:e.target.value})}/><input value={value.pass_design?.accent_color||'#14b8a6'} onChange={e=>update('pass_design',{...value.pass_design,accent_color:e.target.value})}/></div></label></div>:<>
      {tab==='email'&&<label><span>Subject line</span><input required={value.email_enabled} maxLength="180" value={value.email_subject||''} onChange={e=>update('email_subject',e.target.value)}/></label>}
      <label><span>{tab==='email'?'Introduction':'Message'}</span><textarea required={value[`${tab}_enabled`]} rows="7" maxLength={tab==='email'?2000:500} placeholder={tab==='email'?'Your admission is confirmed. QR codes and pass links appear below automatically.':''} value={value[`${tab}_body`]||''} onChange={e=>update(`${tab}_body`,e.target.value)}/><small className="tds-count">{(value[`${tab}_body`]||'').length}/{tab==='email'?2000:500}</small></label>
      {tab==='email'&&<label><span>Text displayed under every QR code</span><input maxLength="300" value={value.email_qr_caption||''} onChange={e=>update('email_qr_caption',e.target.value)}/></label>}
      <div className="tds-tokens"><span>Insert:</span>{TOKENS.map(([label,token])=><button type="button" onClick={()=>insert(`${tab}_body`,token)} key={token}>{label}</button>)}</div>
      {tab==='email'&&<div className="tds-locked"><span>🔒</span><div><b>QR pass block</b><small>Attendee name, scannable QR and mobile-pass link are securely inserted for every ticket and cannot be removed.</small></div></div>}</>}
    </section><aside className="tds-preview"><div className="tds-preview-label"><b>Live preview</b><span>{tab==='email'?'Desktop email':tab==='pass'?'Guest mobile pass':'Mobile message'}</span></div>{tab==='email'?<div className="tds-email"><header><small>FESTIO TICKET</small><h4>{interpolate(value.email_subject||'Your tickets for {{event_name}}')}</h4></header><main><p>{interpolate(value.email_body||'Your admission is confirmed.')}</p><div className="tds-pass"><b>{preview.first_name} {preview.last_name}</b><div className="tds-qr" aria-label="Sample QR code"/><small>{interpolate(value.email_qr_caption||'Show this QR code at the entrance.')}</small><a>Open mobile pass</a></div><small>Each attendee presents their own QR at check-in.</small></main></div>:tab==='pass'?<div className="tds-festio-pass" style={{'--pass-accent':value.pass_design?.accent_color||'#14b8a6'}}><header><span>● Valid Ticket</span><small>{value.pass_design?.eyebrow||"You're invited to"}</small><h4>{preview.event_name}</h4></header><main><small>{value.pass_design?.attendee_label||'Guest'}</small><b>{preview.first_name} {preview.last_name}</b><div className="tds-qr"/><p>{value.pass_design?.qr_instruction||'Show this code to the check-in official at the entrance.'}</p><button type="button">{value.pass_design?.button_label||'Open FestioHub'}</button>{value.pass_design?.footer_message&&<footer>{value.pass_design.footer_message}</footer>}</main></div>:<div className={`tds-phone ${tab}`}><div className="tds-phone-top">{tab==='sms'?'Messages':'WhatsApp'}</div><div className="tds-bubble">{interpolate(value[`${tab}_body`]||'Your ticket is ready.')}</div><small>Preview uses sample attendee details.</small></div>}</aside></div>
    <footer className="tds-actions"><p>{value.email_enabled||value.sms_enabled||value.whatsapp_enabled?'At least one delivery channel is enabled.':'Choose at least one delivery channel.'}</p><button type="submit" disabled={busy||!dirty||!(value.email_enabled||value.sms_enabled||value.whatsapp_enabled)}>{busy?'Saving…':'Save ticket messages'}</button></footer>
  </form>
}
