events {}

http {
  upstream engagement_load_api {
    least_conn;
    server festio-live-load-308-api-a:8060;
    server festio-live-load-308-api-b:8060;
  }

  server {
    listen 8060;
    location / {
      proxy_pass http://engagement_load_api;
      proxy_http_version 1.1;
      proxy_buffering off;
      proxy_read_timeout 190m;
    }
  }
}
