import { useState } from 'react';
import { icons } from './icons.mjs';
import { asTime } from './appModel.mjs';
import { sessionKind, sessionLive, dayHighlights, activityLabels, activityHref } from './programmeView.mjs';
const Icon=({name})=><svg aria-hidden="true" viewBox="0 0 24 24" dangerouslySetInnerHTML={{__html:name==='book'?'<path d="M12 5v16M12 5C8 2 4 3 2 4v15c4-2 7-1 10 2 3-3 6-4 10-2V4c-2-1-6-2-10 1ZM5 8l4 1m-4 3 4 1m6-4 4-1m-4 5 4-1"/>':icons[name]||icons.calendar}}/>;
export function SessionActivities({session, activities=[], forms=[], eventId, token, onForm, disabled=false}) {
 const linked=activities.filter(a=>a.session_id===session.step_id);
 const linkedForms=forms.filter(f=>f.step_id===session.step_id);
 if(!linked.length&&!linkedForms.length)return null;
 return <div className="pg-activities" aria-label={`Activities for ${session.title}`}>{linked.map(a=>{
  const live=a.status==='live',label=activityLabels[a.type]||'Open activity',status=live?'Live now':a.status==='scheduled'?'Opens later':a.status==='paused'?'Paused':'Closed';
  const content=<><span><strong>{label}</strong><small>{a.title}</small></span><span className="pg-activity-status">{live?'● ':''}{status}{live?' ↗':''}</span></>;
  const href=disabled?'':activityHref(eventId,token,a);
  return href?<a className="pg-activity is-live" key={a.id} href={href}>{content}</a>:<button className="pg-activity" key={a.id} disabled>{content}</button>;
 })}{linkedForms.map(f=><button className="pg-activity" key={f.id+f.guest_id} onClick={()=>onForm(f)} disabled={disabled}><span><strong>{f.kind==='consent'?'Review consent':'Review form'}</strong><small>{f.title} · {f.guest_name}</small></span><span className="pg-activity-status">{f.status==='complete'?'Completed':'Review'} →</span></button>)}</div>;
}
export default function ProgrammeView({days,selectedDay,timeline,now,zone,time,date,onDay,onSession,audienceControl,search,onSearch,saved,onSave,activityProps,activityError,onRetry,bookmarkNotice}) {
 const [filter,setFilter]=useState('all');
 const sessions=selectedDay?.segments||timeline;
 const {current,featured,next}=dayHighlights(sessions,now);
 const kinds=[...new Set(sessions.map(s=>sessionKind(s).label))];
 const activeFilter=kinds.includes(filter)||['all','saved'].includes(filter)?filter:'all';
 const visible=sessions.filter(s=>(activeFilter==='all'||activeFilter==='saved'&&saved.includes(String(s.step_id))||sessionKind(s).label===activeFilter)&&[s.title,s.room,s.speaker,...(s.age_groups||[])].join(' ').toLowerCase().includes(search.toLowerCase()));
 const dayDate=d=>new Date(`${d.date}T12:00:00Z`);
 const dayLabel=(d,options)=>dayDate(d).toLocaleDateString(undefined,{...options,timeZone:'UTC'});
 return <section className="pg-view" aria-label="Event programme">
 <div className="pg-heading"><div><span className="eyebrow">YOUR EVENT. YOUR OWN JOURNEY.</span><h1>Your programme</h1><p>Find your moments. Know where to be next.</p></div><div className="pg-clock"><small>Event time</small><strong>{time(new Date(now).toISOString())}</strong><small>{zone}</small></div></div>
 <div className="pg-days days" aria-label="Programme days">{days.map(d=><button className={`pg-day day ${selectedDay?.date===d.date?'active':''}`} key={d.date} aria-pressed={selectedDay?.date===d.date} onClick={()=>onDay(d.date)} aria-label={d.label||d.date}><small>{dayLabel(d,{weekday:'short'})}</small><strong>{dayLabel(d,{day:'numeric'})} <span>{dayLabel(d,{month:'short'})}</span></strong><span className="pg-day-count">{d.segments?.length||0} {d.segments?.length===1?'session':'sessions'}</span><span className="pg-day-line"/></button>)}</div>
 {audienceControl}
 {featured&&<div className="pg-lead"><section className="pg-spotlight"><span className="pg-live-tag">{current.length?`● HAPPENING NOW${current.length>1?` · ${current.length} parallel sessions`:''}`:asTime(featured.ends_at)<=now?'FROM THIS DAY':'COMING UP'}</span><h2>{featured.title}</h2><p>{time(featured.starts_at)} – {time(featured.ends_at)} · {featured.room||featured.location||'Room to be announced'}</p><div className="pg-spotlight-foot"><button className="primary" onClick={()=>onSession(featured)}>View session →</button>{current.length>0&&<span>{Math.max(1,Math.ceil((asTime(featured.ends_at)-now)/60000))} min remaining</span>}</div>{current.length>0&&<><progress aria-label="Session time elapsed" max="100" value={Math.min(100,Math.max(0,(now-asTime(featured.starts_at))/(asTime(featured.ends_at)-asTime(featured.starts_at))*100))}/><div className="pg-progress-label"><span>{time(featured.starts_at)}</span><span>{time(featured.ends_at)}</span></div></>}</section><section className="pg-next"><span className="eyebrow">UP NEXT{next&&asTime(next.starts_at)-now<86400000?` · IN ${Math.max(1,Math.ceil((asTime(next.starts_at)-now)/60000))} MIN`:''}</span><h3>{next?.title||'Time to make a connection'}</h3><p>{next?`${time(next.starts_at)} · ${next.room||'Room to be announced'}`:'No further upcoming sessions in this day’s view. Explore another day or audience.'}</p>{next&&<button className="text-button" onClick={()=>onSession(next)}>Details →</button>}</section></div>}
 {activityError&&<p className="notice" role="status">{activityError} <button className="text-button" onClick={onRetry}>Retry activities</button></p>}{bookmarkNotice&&<p role="status" className="notice">{bookmarkNotice}</p>}
 <div className="pg-section-heading"><div><h2>{selectedDay?dayLabel(selectedDay,{weekday:'short',month:'long',day:'numeric'}):'Programme'}</h2><p>All times in {zone}</p></div><span className="pg-count" role="status">{visible.length} {visible.length===1?'session':'sessions'}</span></div>
 <div className="pg-filters"><button className={activeFilter==='all'?'active':''} aria-pressed={activeFilter==='all'} onClick={()=>setFilter('all')}>All sessions</button>{kinds.map(k=><button key={k} className={activeFilter===k?'active':''} aria-pressed={activeFilter===k} onClick={()=>setFilter(k)}>{k}</button>)}<button className={activeFilter==='saved'?'active':''} aria-pressed={activeFilter==='saved'} onClick={()=>setFilter('saved')}>♡ Saved {saved.length}</button><label className="search"><Icon name="search"/><input type="search" aria-label="Search programme" placeholder="Find a session or room…" value={search} onChange={e=>onSearch(e.target.value)}/></label></div>
 <div className="pg-agenda"><div><div className="pg-timeline schedule-list">{visible.map(s=>{const kind=sessionKind(s),live=sessionLive(s,now);return <article className={`pg-slot ${live?'is-live':''}`} key={s.step_id}><div className="pg-stamp">{time(s.starts_at)}</div><div className="pg-session"><div className={`pg-art ${kind.tone}`}><Icon name={kind.icon}/></div><div className="pg-session-body"><div className="pg-session-top"><span>{kind.label}</span><button className="pg-bookmark" aria-label={`${saved.includes(String(s.step_id))?'Unsave':'Save'} ${s.title}`} aria-pressed={saved.includes(String(s.step_id))} onClick={()=>onSave(String(s.step_id))}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h12v18l-6-4-6 4Z"/></svg></button></div><button className="pg-title" onClick={()=>onSession(s)}>{s.title}</button><p><Icon name="pin"/>{s.room||s.location||'Room to be announced'}{asTime(s.ends_at)>asTime(s.starts_at)&&<span> · {Math.round((asTime(s.ends_at)-asTime(s.starts_at))/60000)} min</span>}</p>{s.speaker&&<p>{s.speaker}</p>}<div className="pg-tags">{live&&<span className="pg-now">● Happening now</span>}{s.age_groups?.length>0&&<span>{s.age_groups.join(', ')}</span>}</div><SessionActivities session={s} {...activityProps}/></div></div></article>})}</div>{!visible.length&&<div className="empty"><h3>No matching sessions</h3><p>Try another day or choose All programmes to explore other groups.</p><button className="text-button" onClick={()=>{setFilter('all');onSearch('')}}>Clear search and filters →</button></div>}<p className="fine">The timetable does not grant admission to restricted sessions. Saved sessions are bookmarks on this device, not seat reservations.</p></div><aside className="pg-rail"><div className="card"><span className="eyebrow">YOUR DAY AT A GLANCE</span><h3>{sessions.length} {sessions.length===1?'moment':'moments'} to explore</h3><div className="pg-mix">{kinds.map(k=><span key={k} style={{flex:sessions.filter(s=>sessionKind(s).label===k).length}} title={k}/>)}</div>{kinds.map(k=><div className="pg-legend" key={k}><span>{k}</span><b>{sessions.filter(s=>sessionKind(s).label===k).length}</b></div>)}</div><div className="card pg-tip"><Icon name="people"/><h3>A programme for everyone</h3><p>Choose a family member to see their sessions alongside shared activities.</p></div><div className="card"><Icon name="star"/><h3>Keep your favourites close</h3><p>Save a session to find it quickly. Activities appear when linked by your organizer and available to your guest access.</p></div></aside></div>
 </section>;
}
