import { useState, useEffect } from 'react';
import { icons } from './icons.mjs';
import { asTime } from './appModel.mjs';
import { sessionKind, sessionLive, dayHighlights, activityLabels, activityHref, groupSessions, programmePeriods, programmeGroups, programmeRoom, timezoneLabel, startsIn } from './programmeView.mjs';
const Icon=({name})=><svg aria-hidden="true" viewBox="0 0 24 24" dangerouslySetInnerHTML={{__html:name==='book'?'<path d="M12 5v16M12 5C8 2 4 3 2 4v15c4-2 7-1 10 2 3-3 6-4 10-2V4c-2-1-6-2-10 1ZM5 8l4 1m-4 3 4 1m6-4 4-1m-4 5 4-1"/>':icons[name]||icons.calendar}}/>;
export function SessionActivities({session, activities=[], forms=[], eventId, token, onForm, onActivity, disabled=false}) {
 const linked=activities.filter(a=>a.session_id===session.step_id);
 const linkedForms=forms.filter(f=>f.step_id===session.step_id);
 if(!linked.length&&!linkedForms.length)return null;
 return <div className="pg-activities" aria-label={`Activities for ${session.title}`}>{linked.map(a=>{
  const live=a.status==='live',label=activityLabels[a.type]||'Open activity',status=live?'Live now':a.status==='scheduled'?'Opens later':a.status==='paused'?'Paused':'Closed';
  const content=<><span><strong>{label}</strong><small>{a.title}</small></span><span className="pg-activity-status">{live?'● ':''}{status}{live?(onActivity?' →':' ↗'):''}</span></>;
  const href=disabled?'':activityHref(eventId,token,a);
  return href?<a className="pg-activity is-live" key={a.id} href={onActivity ? `#/live?${new URLSearchParams({activity:a.id,session:a.session_id})}` : href} onClick={onActivity ? e=>{e.preventDefault();onActivity(a)} : undefined}>{content}</a>:<button className="pg-activity" key={a.id} disabled>{content}</button>;
 })}{linkedForms.map(f=><button className="pg-activity" key={f.id+f.guest_id} onClick={()=>onForm(f)} disabled={disabled}><span><strong>{f.kind==='consent'?'Review consent':'Review form'}</strong><small>{f.title} · {f.guest_name}</small></span><span className="pg-activity-status">{f.status==='complete'?'Completed':'Review'} →</span></button>)}</div>;
}
export default function ProgrammeView({days,selectedDay,timeline,now,zone,time,date,onDay,onSession,audienceControl,search,onSearch,saved,onSave,activityProps,activityError,onRetry,bookmarkNotice,onForms,formsAvailable}) {
 const [filter,setFilter]=useState('all'),[savedOnly,setSavedOnly]=useState(false);
 const [room,setRoom]=useState('all'),[age,setAge]=useState('all');
 const [expanded,setExpanded]=useState({}),[periodExpanded,setPeriodExpanded]=useState({});
 useEffect(()=>{setRoom('all');setAge('all');setExpanded({});setPeriodExpanded({});},[selectedDay?.date]);
 const sessions=selectedDay?.segments||timeline;
 const kinds=[...new Set(sessions.map(s=>sessionKind(s).label))];
 const activeFilter=kinds.includes(filter)?filter:'all';
 const rooms=[...new Set(sessions.map(programmeRoom))],ages=[...new Set(sessions.flatMap(programmeGroups))];
 const chosenRoom=rooms.includes(room)?room:'all',chosenAge=ages.includes(age)?age:'all';
 const visible=sessions.filter(s=>(chosenRoom==='all'||programmeRoom(s)===chosenRoom)&&(chosenAge==='all'||programmeGroups(s).includes(chosenAge))&&(activeFilter==='all'||sessionKind(s).label===activeFilter)&&(!savedOnly||saved.includes(String(s.step_id)))&&[s.title,s.room,s.speaker,...(s.age_groups||[])].join(' ').toLowerCase().includes(search.toLowerCase()));
 const {current,featured,next}=dayHighlights(visible,now);
 const groups=groupSessions(visible),periods=programmePeriods(visible,zone);
 const jumpGroup=groups.find(g=>g.sessions.some(s=>sessionLive(s,now)))||groups.find(g=>asTime(g.starts_at)>now)||groups[0];
 function jump(){if(!jumpGroup)return;const period=periods.find(p=>p.groups.some(g=>g.key===jumpGroup.key));setPeriodExpanded(x=>({...x,[period.label]:true}));setExpanded(x=>({...x,[jumpGroup.key]:true}));requestAnimationFrame(()=>{const el=document.getElementById('programme-time-'+jumpGroup.key);el?.scrollIntoView({block:'start'});el?.focus({preventScroll:true})});}
 const dayDate=d=>new Date(`${d.date}T12:00:00Z`);
 const dayLabel=(d,options)=>dayDate(d).toLocaleDateString(undefined,{...options,timeZone:'UTC'});
 const pendingForms=(activityProps?.forms||[]).filter(f=>f.required&&f.status!=='complete').length;
 const renderSession=s=>{const kind=sessionKind(s),live=sessionLive(s,now);return <article className={`pg-slot ${live?'is-live':''}`} key={s.step_id}><div className="pg-session"><div className="pg-session-top"><div className={`pg-art ${kind.tone}`}><Icon name={kind.icon}/></div><div><span className="pg-category">{kind.label}</span>{s.age_groups?.length>0&&<span className="pg-audience-label">{s.age_groups.join(', ')}</span>}</div><button className="pg-bookmark" aria-label={`${saved.includes(String(s.step_id))?'Unsave':'Save'} ${s.title}`} aria-pressed={saved.includes(String(s.step_id))} onClick={()=>onSave(String(s.step_id))}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h12v18l-6-4-6 4Z"/></svg></button></div><div className="pg-session-body"><button className="pg-title" onClick={()=>onSession(s)}>{s.title}</button><p className="pg-facts"><Icon name="pin"/>{programmeRoom(s)}<span> · {time(s.starts_at)}{Number.isFinite(asTime(s.ends_at))?`–${time(s.ends_at)}`:''}</span></p>{s.speaker&&<p className="pg-speaker">{s.speaker}</p>}{s.description&&!s.description.startsWith('DEMO DRAFT:')&&<p className="pg-description">{s.description}</p>}{live&&<span className="pg-now">● Happening now</span>}<SessionActivities session={s} {...activityProps}/><button className="text-button pg-details" onClick={()=>onSession(s)}>Session details ↗</button></div></div></article>};
 return <section className="pg-view" aria-label="Event programme">
 <header className="pg-heading"><div><span className="eyebrow">MAKE SPACE FOR WHAT MATTERS</span><h1>Your programme</h1><p>Find your moments. Know where to be next.</p></div><div className="pg-clock"><Icon name="clock"/><span>{timezoneLabel(zone,now)}</span></div></header>
 {sessions.some(s=>s.description?.startsWith('DEMO DRAFT:')||/^DEMO[ ·]/.test(s.title))&&<p className="pg-demo"><b>Demo programme — not the final timetable.</b> Times and rooms await organizer approval.</p>}
 <div className="pg-days days" aria-label="Programme days">{days.map(d=><button className={`pg-day day ${selectedDay?.date===d.date?'active':''}`} key={d.date} aria-pressed={selectedDay?.date===d.date} onClick={()=>onDay(d.date)} aria-label={d.label||d.date}><small>{dayLabel(d,{weekday:'short'})}</small><strong>{dayLabel(d,{day:'numeric'})} <span>{dayLabel(d,{month:'short'})}</span></strong><span className="pg-day-count">{d.segments?.length||0} {d.segments?.length===1?'session':'sessions'}</span></button>)}</div>
 {featured&&<section className="pg-spotlight"><span className="pg-focus-icon"><Icon name={sessionKind(featured).icon}/></span><div className="pg-focus-copy"><span className="pg-live-tag">{current.length?`● HAPPENING NOW${current.length>1?` · ${current.length} parallel sessions`:''}`:asTime(featured.ends_at)<=now?'FROM THIS DAY':'COMING UP'}</span><h2>{featured.title}</h2><p>{time(featured.starts_at)}{Number.isFinite(asTime(featured.ends_at))?`–${time(featured.ends_at)}`:''} · {programmeRoom(featured)}</p></div><button className="primary" onClick={()=>onSession(featured)}>View session →</button></section>}
 {activityError&&<p className="notice" role="status">{activityError} <button className="text-button" onClick={onRetry}>Retry activities</button></p>}{bookmarkNotice&&<p role="status" className="notice">{bookmarkNotice}</p>}
 <div className="pg-toolbar">{audienceControl}<div className="pg-searchtools"><label className="search"><Icon name="search"/><input type="search" aria-label="Search programme" placeholder="Search this day’s sessions…" value={search} onChange={e=>onSearch(e.target.value)}/></label><details className="pg-filter-panel"><summary><Icon name="grid"/>Filters{activeFilter!=='all'||chosenRoom!=='all'||chosenAge!=='all'?' •':''}</summary><div className="pg-refine"><label>Session type<select aria-label="Filter programme by type" value={activeFilter} onChange={e=>setFilter(e.target.value)}><option value="all">All session types</option>{kinds.map(k=><option key={k}>{k}</option>)}</select></label>{rooms.length>1&&<label>Room<select aria-label="Filter programme by room" value={chosenRoom} onChange={e=>setRoom(e.target.value)}><option value="all">All rooms</option>{rooms.map(r=><option key={r}>{r}</option>)}</select></label>}{ages.length>1&&<label>Age group<select aria-label="Filter programme by age group" value={chosenAge} onChange={e=>setAge(e.target.value)}><option value="all">All age groups</option>{ages.map(a=><option key={a}>{a}</option>)}</select></label>}<button className="text-button" onClick={()=>{setFilter('all');setRoom('all');setAge('all')}}>Reset filters</button></div></details></div></div>
 <div className="pg-subtools"><span>{selectedDay?dayLabel(selectedDay,{weekday:'short',month:'long',day:'numeric'}):'Programme'} · {timezoneLabel(zone,now)}</span><button className={savedOnly?'active':''} aria-pressed={savedOnly} onClick={()=>setSavedOnly(v=>!v)}>♡ Saved {saved.length}</button>{groups.length>1&&<button onClick={jump}>Jump to {current.length?'now':'next time'} →</button>}<span className="pg-count" role="status">{visible.length} {visible.length===1?'session':'sessions'}</span></div>
 <div className="pg-agenda"><div><div className="pg-timeline schedule-list">{periods.map(period=>{
 const shown=periodExpanded[period.label]?period.groups:period.groups.slice(0,3);
 return <section className="pg-period" key={period.label}><header className="pg-period-heading"><span className="pg-period-symbol"><Icon name={period.label==='Evening'?'moon':'sun'}/></span><div><h2>{period.label}</h2><p>{period.label==='Morning'?'Arrive with curiosity.':period.label==='Afternoon'?'Learn, pause, reconnect.':period.label==='Evening'?'Come together.':'Check back for timing.'}</p></div><span className="pg-period-line"/></header>{shown.map(g=><div className="pg-time-group" id={'programme-time-'+g.key} tabIndex={-1} key={g.key}><div className="pg-stamp">{time(g.starts_at)}</div><div className="pg-stack">{g.sessions.length>1&&<p className="pg-parallel"><Icon name="people"/>{g.sessions.length} sessions at this time · Choose your group or room</p>}<div className="pg-time-sessions">{(expanded[g.key]?g.sessions:g.sessions.slice(0,2)).map(renderSession)}</div>{g.sessions.length>2&&<button className="pg-reveal" aria-expanded={!!expanded[g.key]} onClick={()=>setExpanded(x=>({...x,[g.key]:!x[g.key]}))}>{expanded[g.key]?'Show fewer sessions':`Show all ${g.sessions.length} sessions`} {expanded[g.key]?'−':'+'}</button>}</div></div>)}{period.groups.length>3&&<button className="pg-period-more" aria-expanded={!!periodExpanded[period.label]} onClick={()=>setPeriodExpanded(x=>({...x,[period.label]:!x[period.label]}))}>{periodExpanded[period.label]?`Show less of the ${period.label.toLowerCase()}`:`Explore the rest of the ${period.label.toLowerCase()} · ${period.groups.length-3} more times`} {periodExpanded[period.label]?'−':'→'}</button>}</section>;
 })}</div>{!visible.length&&<div className="empty"><h3>No matching sessions</h3><p>Try another day or choose All programmes to explore other groups.</p><button className="text-button" onClick={()=>{setFilter('all');setRoom('all');setAge('all');setSavedOnly(false);onSearch('')}}>Clear search and filters →</button></div>}<p className="fine">The timetable does not grant admission to restricted sessions. Saved sessions are bookmarks on this device, not seat reservations.</p></div><aside className="pg-rail">{formsAvailable&&pendingForms>0&&<div className="card pg-preparation"><span className="eyebrow">A LITTLE PREPARATION</span><h3>Ready for your family’s day?</h3><p>{pendingForms} required {pendingForms===1?'form needs':'forms need'} attention.</p><button className="text-button" onClick={onForms}>Review forms & consent →</button></div>}{next&&<div className="card pg-next"><span className="eyebrow">UP NEXT · {startsIn(next.starts_at,now)}</span><h3>{next.title}</h3><p>{time(next.starts_at)} · {programmeRoom(next)}</p><button className="text-button" onClick={()=>onSession(next)}>Session details →</button></div>}<div className="card pg-tip"><Icon name="people"/><h3>A programme for everyone</h3><p>Choose My family to see their sessions alongside shared activities.</p></div><div className="card"><Icon name="star"/><h3>Keep your favourites close</h3><p>Save a session to find it quickly. Linked activities appear when published by your organizer.</p></div></aside></div>
 </section>;
}
