import Images from './Images';
import {FLYER_LAYOUTS,FLYER_SIZES,flyerSettings,eventFlyerWording} from './flyerModel.mjs';
import {FONTS} from './model.mjs';
export default function FlyerControls({draft,event,eventId,onAssets,onWording,onBusy,disabled,onDownload,downloading}){
 const a=draft.asset_config||{},s=flyerSettings(a),defaults=eventFlyerWording(event);
 const update=patch=>onAssets({flyer_settings:{...s,...patch}});
 const artwork=s.composition==='artwork-only';
 return <section className="studio-flyer-controls" aria-label="Flyer design controls"><h2>Your flyer</h2><p>One design, composed for every format.</p><div className="studio-flyer-layouts">{Object.entries(FLYER_LAYOUTS).map(([id,[name,description]])=><button type="button" key={id} aria-pressed={s.composition===id} className={`studio-layout ${s.composition===id?'selected':''}`} onClick={()=>update({composition:id,artworkOnly:id==='artwork-only'})}><span className={`studio-flyer-mini ${id}`} aria-hidden="true"/><span><strong>{name}</strong><small>{description}</small></span></button>)}</div><label className="studio-field">Flyer format<select aria-label="Flyer format" value={s.size} onChange={e=>update({size:e.target.value})}>{Object.entries(FLYER_SIZES).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
 {!artwork&&<><label className="studio-field">Flyer colours<select aria-label="Flyer colours" disabled={s.composition==='legacy'} value={s.palette} onChange={e=>update({palette:e.target.value})}><option value="event">Use event colours</option><option value="forest">Forest and gold</option><option value="navy">Ivory and navy</option><option value="clay">Warm terracotta</option></select></label>{s.composition==='legacy'&&<p>Existing templates use the shared event colours and their original composition.</p>}<label className="studio-field">Flyer typography<select aria-label="Flyer typography" value={s.fontPairing||(s.composition==='legacy'?'event': 'classic-serif')} onChange={e=>update({fontPairing:e.target.value})}><option value="event">Use shared typography</option>{Object.keys(FONTS).map(f=><option key={f} value={f}>{f.replaceAll('-',' ')}</option>)}</select></label><label className="studio-toggle">Show event logo<input type="checkbox" disabled={s.composition==='legacy'} checked={s.showLogo} onChange={e=>update({showLogo:e.target.checked})}/></label><label className="studio-toggle">Show registration QR<input type="checkbox" checked={s.qr} onChange={e=>update({qr:e.target.checked})}/></label>{s.qr&&<label className="studio-field">QR position<select aria-label="QR position" value={s.qrPosition} onChange={e=>update({qrPosition:e.target.value})}><option value="bottom-right">Bottom right</option><option value="bottom-left">Bottom left</option><option value="center-bottom">Bottom centre</option></select></label>}</>}
 <Images eventId={eventId} assets={a} onChange={onAssets} disabled={disabled} onBusy={onBusy} kinds={artwork?['artwork']:['cover','logo']}/>
 {artwork?<p className="studio-notice">Your finished flyer is kept whole. No extra title, decoration or QR is added.</p>:<details><summary>Flyer wording</summary>{[['eventTitle','Event title',180],['eventSubtitle','Subtitle',200],['hostName','Organizer',100],['inviteLabel','Invitation label',90],['date','Dates',120],['time','Time',90],['venue','Venue',120],['address','Address',200],['ctaLabel','Registration heading',90],['rsvpNote','Registration note',240],['footerMessage','Artwork message',180]].map(([key,label,max])=><label className="studio-field" key={key}>{label}{['eventTitle','eventSubtitle','footerMessage'].includes(key)?<textarea aria-label={label} value={draft.wording_config?.[key]||''} placeholder={defaults[key]||''} maxLength={max} onChange={e=>onWording(key,e.target.value)}/>:<input aria-label={label} value={draft.wording_config?.[key]||''} placeholder={defaults[key]||''} maxLength={max} onChange={e=>onWording(key,e.target.value)}/>}</label>)}</details>}
 <div className="studio-flyer-downloads"><button type="button" disabled={disabled||downloading} onClick={()=>onDownload('png')}>{downloading?'Rendering…':'Download PNG'}</button><button type="button" disabled={disabled||downloading} onClick={()=>onDownload('pdf')}>Download PDF</button></div><p>Downloads use this draft. Publish separately to update guest-facing branding.</p></section>
}
