apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tutor.name" . }}
  namespace: {{ include "tutor.namespace" . }}
  labels:
{{ include "tutor.labels" . | indent 4 }}

spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
{{ include "tutor.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "tutor.selectorLabels" . | indent 8 }}

    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
