apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tutor.name" . }}
  namespace: {{ include "tutor.namespace" . }}
  labels:
{{ include "tutor.labels" . | indent 4 }}

spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tutor
                port:
                  number: {{ .Values.service.port }}
