apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tutor
  namespace: dev-{{ .Values.app.team }}-{{ .Values.app.name }}

spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tutor
                port:
                  number: {{ .Values.service.port }}
