apiVersion: v1
kind: Service
metadata:
  name: tutor
  naespace: dev-{{ .Values.app.team }}-{{ .Values.app.name }}

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tutor
    app.kubernetes.io/team: platform
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
