apiVersion: v1
kind: Service
metadata:
  name: {{ include "tutor.name" . }}
  namespace: {{ include "tutor.namespace" . }}
  labels:
{{ include "tutor.labels" . | indent 4 }}

spec:
  selector:
{{ include "tutor.selectorLabels" . | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
