{{- if .Values.postgres.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "event-checkin.name" . }}-postgres
  namespace: {{ include "event-checkin.namespace" . }}
  labels:
{{ include "event-checkin.postgresLabels" . | indent 4 }}
spec:
  serviceName: {{ include "event-checkin.name" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.name }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
{{ include "event-checkin.postgresLabels" . | indent 8 }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_DB
              value: checkin
            - name: POSTGRES_USER
              value: checkin
            - name: POSTGRES_PASSWORD
              value: checkin
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "checkin"]
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "checkin"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: {{ .Values.postgres.resources.requests.cpu }}
              memory: {{ .Values.postgres.resources.requests.memory }}
            limits:
              cpu: {{ .Values.postgres.resources.limits.cpu }}
              memory: {{ .Values.postgres.resources.limits.memory }}
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-checkin.name" . }}-postgres
  namespace: {{ include "event-checkin.namespace" . }}
  labels:
{{ include "event-checkin.postgresLabels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/component: postgres
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
