apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-dev
  namespace: argocd
spec:
  description: Dev platform workloads

  sourceRepos:
    - https://github.com/devopclinics/platform-tutor.git

  destinations:
    - namespace: dev-platform-*
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: networking.k8s.io
      kind: Ingress
