apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-checkin-dev
  namespace: argocd
spec:
  project: platform-dev
  source:
    repoURL: https://github.com/devopclinics/platform-tutor.git
    targetRevision: main
    path: charts/event-checkin
    helm:
      valueFiles:
        - ../../env/dev/workloads/event-checkin/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-platform-event-checkin

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
        - /spec/ipFamilies
        - /spec/ipFamilyPolicy
        - /spec/internalTrafficPolicy
